import { cloneSerializable } from '../framework/clone-serializable.mjs';

const enemyCombatRuntimeConfig = Object.freeze({
  defaultWidth: 480,
  defaultHeight: 600
});

function buildRuntimeSnippet(config){
  const runtimeJson = JSON.stringify(config, null, 2);
  return [
    '(function(){',
    '  function createEnemyCombatRuntime(config){',
    '    var defaultWidth = Math.max(200, Number(config.defaultWidth) || 480);',
    '    var defaultHeight = Math.max(200, Number(config.defaultHeight) || 600);',
    '',
    '    function clampValue(value, min, max){',
    '      return Math.max(min, Math.min(max, value));',
    '    }',
    '',
    '    function fireEnemy(payload){',
    '      if(!payload || !payload.enemy || typeof payload.spawnEnemyShot !== "function"){',
    '        return false;',
    '      }',
    '',
    '      var enemy = payload.enemy;',
    '      var state = payload.state || null;',
    '      if(enemy.fireMode === "none") return true;',
    '',
    '      var cx = enemy.x + enemy.w * 0.5;',
    '      var cy = enemy.y + enemy.h;',
    '',
    '      if(enemy.fireMode === "single"){',
    '        payload.spawnEnemyShot(cx - 2, cy, 0, enemy.bulletSpeed, 4, 10, "#ff8f00");',
    '        return true;',
    '      }',
    '',
    '      if(enemy.fireMode === "spread"){',
    '        payload.spawnEnemyShot(cx - 2, cy, -0.7, enemy.bulletSpeed, 4, 10, "#ff7f50");',
    '        payload.spawnEnemyShot(cx - 2, cy, 0.7, enemy.bulletSpeed, 4, 10, "#ff7f50");',
    '        return true;',
    '      }',
    '',
    '      if(enemy.fireMode === "burst"){',
    '        payload.spawnEnemyShot(cx - 3, cy, -0.3, enemy.bulletSpeed, 5, 12, "#ffbf40");',
    '        payload.spawnEnemyShot(cx - 1, cy, 0, enemy.bulletSpeed + 0.5, 5, 13, "#ffbf40");',
    '        payload.spawnEnemyShot(cx + 1, cy, 0.3, enemy.bulletSpeed, 5, 12, "#ffbf40");',
    '        return true;',
    '      }',
    '',
    '      if(enemy.fireMode === "aim" && state && state.player){',
    '        var px = state.player.x + state.player.w * 0.5;',
    '        var py = state.player.y + state.player.h * 0.5;',
    '        var dx = px - cx;',
    '        var dy = py - cy;',
    '        var d = Math.sqrt(dx * dx + dy * dy) || 1;',
    '        var speed = enemy.bulletSpeed;',
    '        payload.spawnEnemyShot(cx - 2, cy, dx / d * speed, dy / d * speed, 4, 12, "#ff5252");',
    '        return true;',
    '      }',
    '',
    '      if(enemy.fireMode === "fan"){',
    '        var i;',
    '        for(i = -2; i <= 2; i++){',
    '          var angle = Math.PI * 0.5 + i * 0.2;',
    '          payload.spawnEnemyShot(',
    '            cx - 2,',
    '            cy,',
    '            Math.cos(angle) * enemy.bulletSpeed * 0.85,',
    '            Math.sin(angle) * enemy.bulletSpeed,',
    '            5,',
    '            11,',
    '            "#ff79f2"',
    '          );',
    '        }',
    '        return true;',
    '      }',
    '',
    '      return false;',
    '    }',
    '',
    '    function updateEnemy(payload){',
    '      if(!payload || !payload.enemy || !payload.state){',
    '        return true;',
    '      }',
    '',
    '      var enemy = payload.enemy;',
    '      var state = payload.state;',
    '      var width = Math.max(200, Number(payload.width) || defaultWidth);',
    '      var height = Math.max(200, Number(payload.height) || defaultHeight);',
    '      var rand = typeof payload.rand === "function" ? payload.rand : Math.random;',
    '      var randInt = typeof payload.randInt === "function"',
    '        ? payload.randInt',
    '        : function(min, max){ return min + Math.floor(rand() * (max - min + 1)); };',
    '      var clamp = typeof payload.clamp === "function" ? payload.clamp : clampValue;',
    '      var fireEnemyFn = typeof payload.fireEnemy === "function"',
    '        ? payload.fireEnemy',
    '        : function(enemyRef){',
    '            fireEnemy({ enemy: enemyRef, state: state, spawnEnemyShot: payload.spawnEnemyShot || function(){} });',
    '          };',
    '',
    '      enemy.age++;',
    '',
    '      if(enemy.motion === "dive"){',
    '        if(!enemy.diving){',
    '          enemy.diveDelay--;',
    '          enemy.y += enemy.speed * 0.7;',
    '          enemy.x += Math.sin((state.tick + enemy.phase) / 14) * 1.1;',
    '          if(enemy.diveDelay <= 0 || enemy.y > 170){',
    '            enemy.diving = true;',
    '            var px = state.player.x + state.player.w * 0.5;',
    '            enemy.vx = (px - (enemy.x + enemy.w * 0.5)) * 0.012;',
    '            enemy.vy = enemy.speed * 1.4;',
    '          }',
    '        } else {',
    '          enemy.vy += 0.028;',
    '          enemy.x += enemy.vx;',
    '          enemy.y += enemy.vy;',
    '        }',
    '      } else if(enemy.motion === "zigzag"){',
    '        enemy.y += enemy.speed;',
    '        enemy.x += enemy.dir * (1.1 + enemy.speed * 0.14);',
    '        if(enemy.x < 8 || enemy.x > width - enemy.w - 8){',
    '          enemy.dir *= -1;',
    '        }',
    '      } else if(enemy.motion === "hover"){',
    '        enemy.y += enemy.speed * 0.7;',
    '        enemy.x += Math.sin((state.tick + enemy.phase) / 20) * 1.2;',
    '      } else if(enemy.motion === "march"){',
    '        enemy.y += enemy.speed;',
    '        enemy.x += enemy.dir * 0.45;',
    '        if(enemy.x < 8 || enemy.x > width - enemy.w - 8){',
    '          enemy.dir *= -1;',
    '        }',
    '      } else {',
    '        enemy.y += enemy.speed;',
    '        enemy.x += Math.sin((state.tick + enemy.phase) / 24) * 0.9;',
    '      }',
    '',
    '      if(enemy.y > height + 90){',
    '        enemy.y = -enemy.h - randInt(20, 140);',
    '        enemy.x = 16 + rand() * (width - enemy.w - 32);',
    '        enemy.fireCooldown = Math.max(20, Math.floor(enemy.fireRate * 0.5));',
    '        if(enemy.motion === "dive"){',
    '          enemy.diving = false;',
    '          enemy.vx = 0;',
    '          enemy.vy = 0;',
    '          enemy.diveDelay = 50 + randInt(0, 90);',
    '        }',
    '      }',
    '',
    '      if(enemy.x < -enemy.w - 26 || enemy.x > width + 26){',
    '        enemy.dir *= -1;',
    '        enemy.x = clamp(enemy.x, -enemy.w * 0.35, width - enemy.w * 0.65);',
    '      }',
    '',
    '      enemy.fireCooldown--;',
    '      if(enemy.fireCooldown <= 0){',
    '        fireEnemyFn(enemy);',
    '        enemy.fireCooldown = enemy.fireRate + randInt(0, Math.floor(enemy.fireRate * 0.35));',
    '      }',
    '',
    '      return true;',
    '    }',
    '',
    '    return {',
    '      fireEnemy: fireEnemy,',
    '      updateEnemy: updateEnemy',
    '    };',
    '  }',
    '',
    `  var runtimeConfig = ${runtimeJson};`,
    '  var runtimeHooks = game.__astroV2RuntimeHooks || {};',
    '  runtimeHooks.enemyCombat = createEnemyCombatRuntime(runtimeConfig);',
    '  game.__astroV2RuntimeHooks = runtimeHooks;',
    '  if(typeof game.setV2RuntimeHooks === "function"){',
    '    game.setV2RuntimeHooks(runtimeHooks);',
    '  }',
    '',
    '  runtimePatch.runtime = runtimePatch.runtime || {};',
    '  runtimePatch.runtime.enemyCombat = {',
    '    module: "enemy-combat-runtime-hooks",',
    '    status: "active",',
    '    behaviorParity: "legacy-v1-enemy-combat"',
    '  };',
    '})();'
  ].join('\n');
}

export const enemyCombatRuntimeModule = {
  id: 'enemy-combat-runtime-hooks',
  priority: 34,
  description: 'Injects runtime hooks for enemy firing and movement update logic.',
  apply(artifact){
    artifact.runtimePatch.runtime = artifact.runtimePatch.runtime || {};
    artifact.runtimePatch.runtime.enemyCombatConfig = cloneSerializable(enemyCombatRuntimeConfig);

    artifact.runtimeSnippets = artifact.runtimeSnippets || [];
    artifact.runtimeSnippets.push(buildRuntimeSnippet(enemyCombatRuntimeConfig));
    return artifact;
  }
};
