import { cloneSerializable } from '../framework/clone-serializable.mjs';

const powerupsRuntimeConfig = Object.freeze({
  initialPowerLevel: 1,
  maxPowerLevel: 3,
  spreadPowerDurationFrames: 720,
  lifePickupType: 'life',
  spreadPickupType: 'spread',
  thrusterPickupType: 'thruster',
  multiplierPickupType: 'multiplier',
  thrusterIntroFrames: 180,
  fireUnlockIntroFrames: 180,
  initialFireCadenceTier: 0,
  autoFireUnlockTier: 4,
  maxFireCadenceTier: 7,
  fireCadenceCooldowns: [14, 12, 11, 10, 9, 8, 7, 6],
  spreadDropChance: 0.78,
  pickupSize: 16,
  pickupBaseDy: 1.2,
  pickupDyVariance: 0.7,
  pickupDriftDivisor: 10,
  pickupDriftAmplitude: 0.45,
  pickupExpireOffsetY: 28,
  shotProfiles: {
    powerLevel1: {
      cooldown: 8,
      centerDamage: 1,
      centerColor: '#fff08f',
      includeSideShots: false,
      includeWingShots: false
    },
    powerLevel2: {
      cooldown: 8,
      centerDamage: 1,
      centerColor: '#fff08f',
      includeSideShots: true,
      includeWingShots: false
    },
    powerLevel3: {
      cooldown: 6,
      centerDamage: 2,
      centerColor: '#fff08f',
      includeSideShots: true,
      includeWingShots: true
    }
  }
});

function buildRuntimeSnippet(config){
  const runtimeJson = JSON.stringify(config, null, 2);
  return [
    '(function(){',
    '  function createPowerupsRuntime(config){',
    '    var maxPowerLevel = Math.max(1, Number(config.maxPowerLevel) || 3);',
    '    var lifePickupType = config.lifePickupType || "life";',
    '    var spreadPickupType = config.spreadPickupType || "spread";',
    '    var thrusterPickupType = config.thrusterPickupType || "thruster";',
    '    var multiplierPickupType = config.multiplierPickupType || "multiplier";',
    '    var thrusterIntroFrames = Math.max(1, Number(config.thrusterIntroFrames) || 180);',
    '    var fireUnlockIntroFrames = Math.max(1, Number(config.fireUnlockIntroFrames) || 180);',
    '    var initialFireCadenceTier = Math.max(0, Math.floor(Number(config.initialFireCadenceTier) || 0));',
    '    var autoFireUnlockTier = Math.max(1, Math.floor(Number(config.autoFireUnlockTier) || 4));',
    '    var maxFireCadenceTier = Math.max(autoFireUnlockTier, Math.floor(Number(config.maxFireCadenceTier) || 7));',
    '    var fireCadenceCooldowns = Array.isArray(config.fireCadenceCooldowns) && config.fireCadenceCooldowns.length',
    '      ? config.fireCadenceCooldowns',
    '      : [14, 12, 11, 10, 9, 8, 7, 6];',
    '    var spreadDropChance = Number(config.spreadDropChance);',
    '    if(!isFinite(spreadDropChance)) spreadDropChance = 0.78;',
    '    var pickupSize = Math.max(8, Number(config.pickupSize) || 16);',
    '    var pickupBaseDy = Number(config.pickupBaseDy);',
    '    if(!isFinite(pickupBaseDy)) pickupBaseDy = 1.2;',
    '    var pickupDyVariance = Number(config.pickupDyVariance);',
    '    if(!isFinite(pickupDyVariance)) pickupDyVariance = 0.7;',
    '    var pickupDriftDivisor = Number(config.pickupDriftDivisor);',
    '    if(!isFinite(pickupDriftDivisor) || pickupDriftDivisor === 0) pickupDriftDivisor = 10;',
    '    var pickupDriftAmplitude = Number(config.pickupDriftAmplitude);',
    '    if(!isFinite(pickupDriftAmplitude)) pickupDriftAmplitude = 0.45;',
    '    var pickupExpireOffsetY = Number(config.pickupExpireOffsetY);',
    '    if(!isFinite(pickupExpireOffsetY)) pickupExpireOffsetY = 28;',
    '    var spreadPowerDurationFrames = Math.max(1, Number(config.spreadPowerDurationFrames) || 720);',
    '    var shotProfiles = config.shotProfiles || {};',
    '',
    '    function clampPowerLevel(level){',
    '      var parsed = Number(level);',
    '      if(!isFinite(parsed)) return 1;',
    '      parsed = Math.floor(parsed);',
    '      if(parsed < 1) return 1;',
    '      if(parsed > maxPowerLevel) return maxPowerLevel;',
    '      return parsed;',
    '    }',
    '',
    '    function clampFireCadenceTier(tier){',
    '      var parsed = Number(tier);',
    '      if(!isFinite(parsed)) return 0;',
    '      parsed = Math.floor(parsed);',
    '      if(parsed < 0) return 0;',
    '      if(parsed > maxFireCadenceTier) return maxFireCadenceTier;',
    '      return parsed;',
    '    }',
    '',
    '    function resolveCadenceCooldown(tier, fallback){',
    '      var clamped = clampFireCadenceTier(tier);',
    '      var configured = Number(fireCadenceCooldowns[clamped]);',
    '      if(!isFinite(configured)){',
    '        var last = Number(fireCadenceCooldowns[fireCadenceCooldowns.length - 1]);',
    '        configured = isFinite(last) ? last : Number(fallback);',
    '      }',
    '      if(!isFinite(configured)) configured = 8;',
    '      return Math.max(1, Math.floor(configured));',
    '    }',
    '',
    '    function isAutoFireUnlocked(tier){',
    '      return clampFireCadenceTier(tier) >= autoFireUnlockTier;',
    '    }',
    '',
    '    function pickShotProfile(level){',
    '      var clamped = clampPowerLevel(level);',
    '      if(clamped >= 3 && shotProfiles.powerLevel3) return shotProfiles.powerLevel3;',
    '      if(clamped >= 2 && shotProfiles.powerLevel2) return shotProfiles.powerLevel2;',
    '      return shotProfiles.powerLevel1 || { cooldown: 8, centerDamage: 1, centerColor: "#fff08f" };',
    '    }',
    '',
    '    function getInitialState(){',
    '      return {',
    '        powerups: [],',
    '        powerLevel: clampPowerLevel(config.initialPowerLevel),',
    '        powerTimer: 0,',
    '        fireCadenceTier: clampFireCadenceTier(initialFireCadenceTier),',
    '        fireAutoUnlocked: isAutoFireUnlocked(initialFireCadenceTier),',
    '        fireAutoUnlockTier: autoFireUnlockTier,',
    '        maxFireCadenceTier: maxFireCadenceTier',
    '      };',
    '    }',
    '',
    '    function getPlayerShotPattern(state, player){',
    '      if(!state || !player) return null;',
    '      var profile = pickShotProfile(state.powerLevel);',
    '      var centerX = player.x + player.w * 0.5 - 2;',
    '      var baseY = player.y - 6;',
    '      var shots = [',
    '        { x: centerX, y: baseY, vx: 0, vy: -7.4, damage: profile.centerDamage || 1, color: profile.centerColor || "#fff08f" }',
    '      ];',
    '      if(profile.includeSideShots){',
    '        shots.push({ x: player.x + 1, y: baseY + 8, vx: -0.4, vy: -6.9, damage: 1, color: "#7efcff" });',
    '        shots.push({ x: player.x + player.w - 5, y: baseY + 8, vx: 0.4, vy: -6.9, damage: 1, color: "#7efcff" });',
    '      }',
    '      if(profile.includeWingShots){',
    '        shots.push({ x: centerX - 8, y: baseY + 12, vx: -1.05, vy: -6.3, damage: 1, color: "#ffde59" });',
    '        shots.push({ x: centerX + 8, y: baseY + 12, vx: 1.05, vy: -6.3, damage: 1, color: "#ffde59" });',
    '      }',
    '      var profileCooldown = Number(profile.cooldown);',
    '      if(!isFinite(profileCooldown)) profileCooldown = 8;',
    '      var fireCadenceTier = clampFireCadenceTier(state.fireCadenceTier);',
    '      return {',
    '        cooldown: resolveCadenceCooldown(fireCadenceTier, profileCooldown),',
    '        shots: shots',
    '      };',
    '    }',
    '',
    '    function maybeDrop(payload){',
    '      if(!payload || !payload.state || !payload.enemy) return;',
    '      var state = payload.state;',
    '      var profile = payload.profile;',
    '      if(!profile || !isFinite(profile.dropChance)) return;',
    '      var rand = typeof payload.rand === "function" ? payload.rand : Math.random;',
    '      var rewardsHazards = payload.rewardsHazards || null;',
    '',
    '      if(rewardsHazards && typeof rewardsHazards.resolveDrop === "function"){',
    '        var resolved = rewardsHazards.resolveDrop({',
    '          state: state,',
    '          level: Number(state.level) || 1,',
    '          wave: Number(state.wave) || 0,',
    '          tick: Number(state.tick) || 0,',
    '          enemy: payload.enemy,',
    '          enemyThreat: Math.max(1, Math.floor(Number(payload.enemy.maxHp || payload.enemy.hp) || 1)),',
    '          profile: profile,',
    '          rand: rand',
    '        });',
    '        if(!resolved) return;',
    '        state.powerups.push({',
    '          x: payload.enemy.x + payload.enemy.w * 0.5 - pickupSize * 0.5,',
    '          y: payload.enemy.y + payload.enemy.h * 0.5 - pickupSize * 0.5,',
    '          w: pickupSize,',
    '          h: pickupSize,',
    '          dy: pickupBaseDy + rand() * pickupDyVariance,',
    '          type: resolved.pickupType || spreadPickupType,',
    '          sourceType: resolved.sourceType || "reward",',
    '          sourceId: resolved.sourceId || null,',
    '          pickupLabel: resolved.pickupLabel || null,',
    '          hazardEffect: resolved.hazardEffect || null,',
    '          phase: rand() * Math.PI * 2',
    '        });',
    '        return;',
    '      }',
    '',
    '      if(rand() > profile.dropChance) return;',
    '',
    '      var type = rand() < spreadDropChance ? spreadPickupType : lifePickupType;',
    '      state.powerups.push({',
    '        x: payload.enemy.x + payload.enemy.w * 0.5 - pickupSize * 0.5,',
    '        y: payload.enemy.y + payload.enemy.h * 0.5 - pickupSize * 0.5,',
    '        w: pickupSize,',
    '        h: pickupSize,',
    '        dy: pickupBaseDy + rand() * pickupDyVariance,',
    '        type: type,',
    '        phase: rand() * Math.PI * 2',
    '      });',
    '    }',
    '',
    '    function tickPowerTimer(payload){',
    '      if(!payload || !payload.state) return;',
    '      var state = payload.state;',
    '      if(!(state.powerTimer > 0)) return;',
    '      state.powerTimer -= 1;',
    '      if(state.powerTimer <= 0){',
    '        state.powerTimer = 0;',
    '        state.powerLevel = 1;',
    '      }',
    '    }',
    '',
    '    function queueNarrativeEvent(event){',
    '      if(!event || !event.key) return;',
    '      if(!Array.isArray(game.__astroNarrativeExternalQueue)){',
    '        game.__astroNarrativeExternalQueue = [];',
    '      }',
    '      game.__astroNarrativeExternalQueue.push(event);',
    '    }',
    '',
    '    function updatePowerups(payload){',
    '      if(!payload || !payload.state || !payload.player || typeof payload.rectsOverlap !== "function"){',
    '        return;',
    '      }',
    '',
    '      var state = payload.state;',
    '      var player = payload.player;',
    '      var tick = Number(payload.tick) || 0;',
    '      var maxLives = Math.max(1, Number(payload.maxLives) || 5);',
    '      var worldHeight = Number(payload.worldHeight) || 600;',
    '      var shared = payload.shared || null;',
    '      var rewardsHazards = payload.rewardsHazards || null;',
    '      var spawnEnemyShot = typeof payload.spawnEnemyShot === "function" ? payload.spawnEnemyShot : null;',
    '',
    '      for(var i = state.powerups.length - 1; i >= 0; i--){',
    '        var powerup = state.powerups[i];',
    '        powerup.y += powerup.dy;',
    '        powerup.x += Math.sin((tick + powerup.phase) / pickupDriftDivisor) * pickupDriftAmplitude;',
    '',
    '        if(payload.rectsOverlap(powerup, player)){',
    '          if(rewardsHazards && typeof rewardsHazards.applyPickup === "function"){',
    '            var applied = rewardsHazards.applyPickup({',
    '              state: state,',
    '              pickup: powerup,',
    '              player: player,',
    '              tick: tick,',
    '              spawnEnemyShot: spawnEnemyShot,',
    '              shared: shared,',
    '              maxLives: maxLives',
    '            });',
    '            if(applied && applied.consumed){',
    '              state.powerups.splice(i, 1);',
    '              continue;',
    '            }',
    '          }',
    '',
    '          if(powerup.type === lifePickupType){',
    '            state.lives = Math.min(maxLives, state.lives + 1);',
    '            if(shared && shared.beep) shared.beep(760, 0.12, "sine", 0.05);',
    '          } else if(powerup.type === thrusterPickupType){',
    '            var hadThrusters = !!state.verticalMobilityUnlocked;',
    '            state.verticalMobilityUnlocked = true;',
    '            state.mobilityUnlockIntro = Math.max(Number(state.mobilityUnlockIntro) || 0, thrusterIntroFrames);',
    '            if(!hadThrusters){',
    '              queueNarrativeEvent({',
    '                key: "ops-thrusters-online",',
    '                kind: "transmission",',
    '                speaker: "OPS",',
    '                title: "Systems Update",',
    '                text: "Vertical thrusters unlocked. Up/down maneuvering now available.",',
    '                durationMs: 3400',
    '              });',
    '            }',
    '            if(shared && shared.beep){',
    '              shared.beep(520, 0.05, "sine", 0.04);',
    '              shared.beep(720, 0.07, "triangle", 0.04);',
    '            }',
    '          } else if(powerup.type === multiplierPickupType){',
    '            var hadAutoFire = !!state.fireAutoUnlocked;',
    '            state.fireCadenceTier = clampFireCadenceTier((Number(state.fireCadenceTier) || 0) + 1);',
    '            state.fireAutoUnlocked = isAutoFireUnlocked(state.fireCadenceTier);',
    '            state.fireAutoUnlockTier = autoFireUnlockTier;',
    '            state.maxFireCadenceTier = maxFireCadenceTier;',
    '            if(state.fireAutoUnlocked){',
    '              state.fireUnlockIntro = Math.max(Number(state.fireUnlockIntro) || 0, fireUnlockIntroFrames);',
    '              if(!hadAutoFire){',
    '                queueNarrativeEvent({',
    '                  key: "ops-autofire-online",',
    '                  kind: "transmission",',
    '                  speaker: "OPS",',
    '                  title: "Systems Update",',
    '                  text: "Auto-fire is now online. Hold fire to sustain volleys.",',
    '                  durationMs: 3400',
    '                });',
    '              }',
    '            }',
    '            if(shared && shared.beep){',
    '              if(state.fireAutoUnlocked){',
    '                shared.beep(540, 0.05, "triangle", 0.04);',
    '                shared.beep(760, 0.07, "triangle", 0.04);',
    '              } else {',
    '                shared.beep(620, 0.05, "square", 0.03);',
    '              }',
    '            }',
    '          } else {',
    '            state.powerLevel = Math.min(maxPowerLevel, clampPowerLevel(state.powerLevel) + 1);',
    '            state.powerTimer = spreadPowerDurationFrames;',
    '            if(shared && shared.beep) shared.beep(660, 0.14, "sine", 0.05);',
    '          }',
    '          state.powerups.splice(i, 1);',
    '          continue;',
    '        }',
    '',
    '        if(powerup.y > worldHeight + pickupExpireOffsetY){',
    '          state.powerups.splice(i, 1);',
    '        }',
    '      }',
    '    }',
    '',
    '    return {',
    '      getInitialState: getInitialState,',
    '      getPlayerShotPattern: getPlayerShotPattern,',
    '      maybeDrop: maybeDrop,',
    '      tickPowerTimer: tickPowerTimer,',
    '      updatePowerups: updatePowerups',
    '    };',
    '  }',
    '',
    `  var runtimeConfig = ${runtimeJson};`,
    '  var runtimeHooks = game.__astroV2RuntimeHooks || {};',
    '  runtimeHooks.powerups = createPowerupsRuntime(runtimeConfig);',
    '  game.__astroV2RuntimeHooks = runtimeHooks;',
    '  if(typeof game.setV2RuntimeHooks === "function"){',
    '    game.setV2RuntimeHooks(runtimeHooks);',
    '  }',
    '',
    '  runtimePatch.runtime = runtimePatch.runtime || {};',
    '  runtimePatch.runtime.powerups = {',
    '    module: "powerups-runtime-hooks",',
    '    status: "active",',
    '    behaviorParity: "legacy-v1+fire-cadence" ',
    '  };',
    '})();'
  ].join('\n');
}

export const powerupsRuntimeModule = {
  id: 'powerups-runtime-hooks',
  priority: 35,
  description: 'Injects runtime powerup/upgrade behavior hooks with legacy-parity values.',
  apply(artifact){
    artifact.runtimePatch.runtime = artifact.runtimePatch.runtime || {};
    artifact.runtimePatch.runtime.powerupsConfig = cloneSerializable(powerupsRuntimeConfig);

    artifact.runtimeSnippets = artifact.runtimeSnippets || [];
    artifact.runtimeSnippets.push(buildRuntimeSnippet(powerupsRuntimeConfig));
    return artifact;
  }
};
