import { cloneSerializable } from '../framework/clone-serializable.mjs';

const waveProgressionRuntimeConfig = Object.freeze({
  maxCampaignLevelFallback: 120,
  defaultWidth: 480
});

function buildRuntimeSnippet(config){
  const runtimeJson = JSON.stringify(config, null, 2);
  return [
    '(function(){',
    '  function createWaveProgressionRuntime(config){',
    '    var maxCampaignLevelFallback = Math.max(1, Number(config.maxCampaignLevelFallback) || 120);',
    '    var defaultWidth = Math.max(200, Number(config.defaultWidth) || 480);',
    '',
    '    function getUnlockedTypes(level, enemyTypes){',
    '      var unlocked = [];',
    '      var key;',
    '      for(key in enemyTypes){',
    '        if(!enemyTypes.hasOwnProperty(key)) continue;',
    '        if(level >= Number(enemyTypes[key].unlock || 0)){',
    '          unlocked.push(key);',
    '        }',
    '      }',
    '      return unlocked;',
    '    }',
    '',
    '    function getSectorTheme(level, overflow, sectorThemes, maxCampaignLevel){',
    '      if(overflow > 0){',
    '        return {',
    '          id: "overdrive",',
    '          name: "Overdrive",',
    '          sectorNumber: Math.floor((maxCampaignLevel - 1) / 10) + 1 + overflow,',
    '          formations: ["swarm", "ring", "vee"],',
    '          enemyWeights: { dive: 1.35, sniper: 1.22, carrier: 1.26, tank: 1.1 },',
    '          speedMul: 1.12 + Math.min(0.42, overflow * 0.012),',
    '          fireMul: 1.13 + Math.min(0.45, overflow * 0.011),',
    '          hpMul: 1.06 + Math.min(0.28, overflow * 0.006),',
    '          dropBonus: -0.012,',
    '          forcedType: overflow % 3 === 0 ? "carrier" : "dive",',
    '          budgetBonus: 2 + Math.floor(overflow / 10)',
    '        };',
    '      }',
    '',
    '      var sectorNumber = Math.floor((level - 1) / 10) + 1;',
    '      var base = sectorThemes[(sectorNumber - 1) % sectorThemes.length];',
    '      return {',
    '        id: base.id,',
    '        name: base.name,',
    '        sectorNumber: sectorNumber,',
    '        formations: base.formations,',
    '        enemyWeights: base.enemyWeights,',
    '        speedMul: base.speedMul,',
    '        fireMul: base.fireMul,',
    '        hpMul: base.hpMul,',
    '        dropBonus: base.dropBonus,',
    '        forcedType: base.forcedType,',
    '        budgetBonus: base.budgetBonus',
    '      };',
    '    }',
    '',
    '    function pickFormation(level, sectorTheme, rand){',
    '      var options = ["line", "stagger", "columns"];',
    '      if(level >= 10) options.push("vee");',
    '      if(level >= 20) options.push("swarm");',
    '      if(level >= 35) options.push("ring");',
    '',
    '      if(',
    '        sectorTheme &&',
    '        Array.isArray(sectorTheme.formations) &&',
    '        sectorTheme.formations.length > 0 &&',
    '        rand() < 0.72',
    '      ){',
    '        return sectorTheme.formations[Math.floor(rand() * sectorTheme.formations.length)];',
    '      }',
    '',
    '      return options[Math.floor(rand() * options.length)];',
    '    }',
    '',
    '    function getLevelProfile(payload){',
    '      var level = Math.max(1, Math.floor(Number(payload.level) || 1));',
    '      var maxCampaignLevel = Math.max(1, Math.floor(Number(payload.maxCampaignLevel) || maxCampaignLevelFallback));',
    '      var enemyTypes = payload.enemyTypes || {};',
    '      var sectorThemes = Array.isArray(payload.sectorThemes) ? payload.sectorThemes : [];',
    '      var rand = typeof payload.rand === "function" ? payload.rand : Math.random;',
    '',
    '      var overflow = level > maxCampaignLevel ? (level - maxCampaignLevel) : 0;',
    '      var effectiveLevel = Math.min(maxCampaignLevel, level) + Math.floor(overflow * 0.65);',
    '      var sectorTheme = getSectorTheme(level, overflow, sectorThemes, maxCampaignLevel);',
    '      var budget = 8 + Math.floor(effectiveLevel * 1.4) + Math.floor(overflow * 0.25) + (sectorTheme.budgetBonus || 0);',
    '      var speedScale = (1 + Math.min(2.6, effectiveLevel * 0.018 + overflow * 0.012)) * (sectorTheme.speedMul || 1);',
    '      var fireScale = (1 + Math.min(2.9, effectiveLevel * 0.016 + overflow * 0.01)) * (sectorTheme.fireMul || 1);',
    '      var hpScale = (1 + Math.min(1.7, effectiveLevel * 0.009 + overflow * 0.007)) * (sectorTheme.hpMul || 1);',
    '      var dropChance = 0.13 - effectiveLevel * 0.0007 + (sectorTheme.dropBonus || 0);',
    '',
    '      return {',
    '        level: level,',
    '        effectiveLevel: effectiveLevel,',
    '        overflow: overflow,',
    '        budget: Math.min(52, budget),',
    '        speedScale: speedScale,',
    '        fireScale: fireScale,',
    '        hpScale: hpScale,',
    '        dropChance: Math.max(0.025, Math.min(0.22, dropChance)),',
    '        unlocked: getUnlockedTypes(level, enemyTypes),',
    '        formation: pickFormation(level, sectorTheme, rand),',
    '        sectorTheme: sectorTheme,',
    '        sectorName: sectorTheme.name,',
    '        sectorNumber: sectorTheme.sectorNumber',
    '      };',
    '    }',
    '',
    '    function pickEnemyType(payload){',
    '      var profile = payload.profile;',
    '      var budget = Math.max(0, Number(payload.budget) || 0);',
    '      var enemyTypes = payload.enemyTypes || {};',
    '      var rand = typeof payload.rand === "function" ? payload.rand : Math.random;',
    '      var choices = [];',
    '      var totalWeight = 0;',
    '      var sectorTheme = profile.sectorTheme || null;',
    '      var sectorWeights = sectorTheme && sectorTheme.enemyWeights ? sectorTheme.enemyWeights : null;',
    '      var i;',
    '',
    '      for(i = 0; i < profile.unlocked.length; i++){',
    '        var typeId = profile.unlocked[i];',
    '        var spec = enemyTypes[typeId];',
    '        if(!spec) continue;',
    '        if(Number(spec.cost || 0) > budget) continue;',
    '',
    '        var unlockDistance = Math.max(0, profile.level - Number(spec.unlock || 0));',
    '        var weight = Number(spec.baseWeight || 0) + unlockDistance * 0.08;',
    '        if(Number(spec.cost || 0) >= 4 && profile.level >= 20){',
    '          weight += (profile.level - 20) * 0.03;',
    '        }',
    '        if(Number(spec.cost || 0) >= 6 && profile.level < 40){',
    '          weight *= 0.55;',
    '        }',
    '',
    '        if(sectorWeights && sectorWeights[typeId]){',
    '          weight *= sectorWeights[typeId];',
    '        }',
    '',
    '        if(sectorTheme && sectorTheme.forcedType === typeId){',
    '          weight *= 1.08;',
    '        }',
    '',
    '        if(weight <= 0){',
    '          continue;',
    '        }',
    '',
    '        choices.push({ id: typeId, weight: weight });',
    '        totalWeight += weight;',
    '      }',
    '',
    '      if(!choices.length){',
    '        return null;',
    '      }',
    '',
    '      var roll = rand() * totalWeight;',
    '      var cursor = 0;',
    '      for(i = 0; i < choices.length; i++){',
    '        cursor += choices[i].weight;',
    '        if(roll <= cursor){',
    '          return choices[i].id;',
    '        }',
    '      }',
    '',
    '      return choices[choices.length - 1].id;',
    '    }',
    '',
    '    function buildFormationSlots(payload){',
    '      var count = Math.max(0, Math.floor(Number(payload.count) || 0));',
    '      var formation = payload.formation || "line";',
    '      var width = Math.max(200, Number(payload.width) || defaultWidth);',
    '      var rand = typeof payload.rand === "function" ? payload.rand : Math.random;',
    '      var slots = [];',
    '      var i;',
    '',
    '      function pushGrid(cols, xPadding, yStart, xStep, yStep, stagger){',
    '        for(i = 0; i < count; i++){',
    '          var row = Math.floor(i / cols);',
    '          var col = i % cols;',
    '          var x = xPadding + col * xStep;',
    '          if(stagger && (row % 2 === 1)){',
    '            x += xStep * 0.5;',
    '          }',
    '          var y = yStart - row * yStep;',
    '          slots.push({ x: x, y: y });',
    '        }',
    '      }',
    '',
    '      if(formation === "line"){',
    '        pushGrid(Math.min(11, count), 24, -24, 40, 44, false);',
    '        return slots;',
    '      }',
    '',
    '      if(formation === "stagger"){',
    '        pushGrid(Math.min(10, count), 26, -24, 42, 40, true);',
    '        return slots;',
    '      }',
    '',
    '      if(formation === "columns"){',
    '        pushGrid(Math.min(5, count), 44, -24, 84, 38, false);',
    '        return slots;',
    '      }',
    '',
    '      if(formation === "vee"){',
    '        for(i = 0; i < count; i++){',
    '          var layer = Math.floor(i / 2);',
    '          var side = i % 2 === 0 ? -1 : 1;',
    '          var lane = Math.ceil(i / 2);',
    '          var vx = width * 0.5 + side * lane * 22;',
    '          var vy = -24 - layer * 30;',
    '          slots.push({ x: vx, y: vy });',
    '        }',
    '        return slots;',
    '      }',
    '',
    '      if(formation === "ring"){',
    '        for(i = 0; i < count; i++){',
    '          var angle = (Math.PI * 2 * i) / Math.max(1, count);',
    '          var radius = 100 + Math.floor(i / 12) * 26;',
    '          slots.push({',
    '            x: width * 0.5 + Math.cos(angle) * radius,',
    '            y: -120 + Math.sin(angle) * radius * 0.55',
    '          });',
    '        }',
    '        return slots;',
    '      }',
    '',
    '      for(i = 0; i < count; i++){',
    '        slots.push({',
    '          x: 18 + rand() * (width - 36),',
    '          y: -30 - rand() * 220',
    '        });',
    '      }',
    '      return slots;',
    '    }',
    '',
    '    function makeEnemy(payload){',
    '      var typeId = payload.typeId || "scout";',
    '      var slot = payload.slot || { x: 24, y: -24 };',
    '      var profile = payload.profile;',
    '      var index = Math.max(0, Math.floor(Number(payload.index) || 0));',
    '      var enemyTypes = payload.enemyTypes || {};',
    '      var rand = typeof payload.rand === "function" ? payload.rand : Math.random;',
    '      var randInt = typeof payload.randInt === "function" ? payload.randInt : function(min, max){',
    '        return Math.floor(rand() * (max - min + 1)) + min;',
    '      };',
    '',
    '      var spec = enemyTypes[typeId] || enemyTypes.scout;',
    '      if(!spec){',
    '        return null;',
    '      }',
    '',
    '      var hpScaleBonus = Number(spec.cost || 0) >= 4 ? 0.22 : 0.08;',
    '      var hp = Math.max(1, Math.floor(Number(spec.baseHp || 1) + profile.hpScale * hpScaleBonus * Number(spec.baseHp || 1)));',
    '      var speed = Number(spec.baseSpeed || 1) * profile.speedScale;',
    '      var fireRate = Math.max(45, Math.floor(Number(spec.fireRate || 180) / profile.fireScale));',
    '      var baseScore = Math.floor(Number(spec.baseScore || 70) * (1 + profile.effectiveLevel * 0.026));',
    '',
    '      return {',
    '        type: typeId,',
    '        x: slot.x,',
    '        y: slot.y,',
    '        w: Number(spec.w || 22),',
    '        h: Number(spec.h || 22),',
    '        hp: hp,',
    '        maxHp: hp,',
    '        speed: speed,',
    '        scoreValue: baseScore,',
    '        motion: spec.motion || "sway",',
    '        fireMode: spec.fireMode || "single",',
    '        bulletSpeed: Number(spec.bulletSpeed || 3.2) + profile.effectiveLevel * 0.03,',
    '        fireRate: fireRate,',
    '        fireCooldown: randInt(Math.floor(fireRate * 0.35), fireRate + 25),',
    '        color: spec.color || "#ff5b6e",',
    '        dir: rand() < 0.5 ? -1 : 1,',
    '        phase: rand() * Math.PI * 2,',
    '        age: 0,',
    '        vx: 0,',
    '        vy: 0,',
    '        diveDelay: 65 + randInt(0, 100),',
    '        diving: false,',
    '        variant: index % 3',
    '      };',
    '    }',
    '',
    '    function buildWaveLabel(level, profile){',
    '      var sectorTitle = profile.sectorName || "Sector Drift";',
    '      var sectorNumber = profile.sectorNumber || (Math.floor((level - 1) / 10) + 1);',
    '      if(profile.overflow > 0){',
    '        return "Overdrive " + profile.overflow + " - " + sectorTitle;',
    '      }',
    '      if(level % 15 === 0){',
    '        return "Sector " + sectorNumber + " - Elite Surge";',
    '      }',
    '      if(level % 10 === 0){',
    '        return "Sector " + sectorNumber + " - " + sectorTitle + " Peak";',
    '      }',
    '      return "Sector " + sectorNumber + " - " + sectorTitle;',
    '    }',
    '',
    '    function buildWaveSpec(payload){',
    '      if(!payload || !payload.enemyTypes || !Array.isArray(payload.sectorThemes)){',
    '        return null;',
    '      }',
    '',
    '      var level = Math.max(1, Math.floor(Number(payload.level) || 1));',
    '      var width = Math.max(200, Number(payload.width) || defaultWidth);',
    '      var maxCampaignLevel = Math.max(1, Math.floor(Number(payload.maxCampaignLevel) || maxCampaignLevelFallback));',
    '      var enemyTypes = payload.enemyTypes;',
    '      var sectorThemes = payload.sectorThemes;',
    '      var rand = typeof payload.rand === "function" ? payload.rand : Math.random;',
    '      var randInt = typeof payload.randInt === "function" ? payload.randInt : function(min, max){',
    '        return Math.floor(rand() * (max - min + 1)) + min;',
    '      };',
    '',
    '      var profile = getLevelProfile({',
    '        level: level,',
    '        maxCampaignLevel: maxCampaignLevel,',
    '        enemyTypes: enemyTypes,',
    '        sectorThemes: sectorThemes,',
    '        rand: rand',
    '      });',
    '',
    '      var sectorTheme = profile.sectorTheme || null;',
    '      var picks = [];',
    '      var budget = profile.budget;',
    '      var maxCount = Math.min(34, 10 + Math.floor(level * 0.24));',
    '',
    '      if(',
    '        sectorTheme &&',
    '        sectorTheme.forcedType &&',
    '        enemyTypes[sectorTheme.forcedType] &&',
    '        budget >= Number(enemyTypes[sectorTheme.forcedType].cost || 0) &&',
    '        rand() < 0.72',
    '      ){',
    '        picks.push(sectorTheme.forcedType);',
    '        budget -= Number(enemyTypes[sectorTheme.forcedType].cost || 0);',
    '      }',
    '',
    '      if(level % 15 === 0 && enemyTypes.carrier && enemyTypes.tank && enemyTypes.sniper){',
    '        picks.push("carrier");',
    '        budget -= Number(enemyTypes.carrier.cost || 0);',
    '        if(budget < 0) budget = 0;',
    '        picks.push("tank");',
    '        picks.push("sniper");',
    '      }',
    '',
    '      while(budget > 0 && picks.length < maxCount){',
    '        var typeId = pickEnemyType({',
    '          profile: profile,',
    '          budget: budget,',
    '          enemyTypes: enemyTypes,',
    '          rand: rand',
    '        });',
    '        if(!typeId) break;',
    '        picks.push(typeId);',
    '        budget -= Number(enemyTypes[typeId].cost || 0);',
    '      }',
    '',
    '      if(picks.length === 0){',
    '        picks.push("scout");',
    '      }',
    '',
    '      if(level % 7 === 0 && picks.length < maxCount){',
    '        picks.push(level >= 18 ? "dive" : "zigzag");',
    '      }',
    '',
    '      if(level % 9 === 0 && level >= 12 && picks.length < maxCount){',
    '        picks.push("sniper");',
    '      }',
    '',
    '      if(',
    '        sectorTheme &&',
    '        sectorTheme.id === "sniper" &&',
    '        level % 2 === 0 &&',
    '        picks.length < maxCount &&',
    '        enemyTypes.sniper &&',
    '        budget >= Number(enemyTypes.sniper.cost || 0)',
    '      ){',
    '        picks.push("sniper");',
    '        budget -= Number(enemyTypes.sniper.cost || 0);',
    '      }',
    '',
    '      if(',
    '        sectorTheme &&',
    '        sectorTheme.id === "dive" &&',
    '        level % 3 === 0 &&',
    '        picks.length < maxCount &&',
    '        enemyTypes.dive &&',
    '        budget >= Number(enemyTypes.dive.cost || 0)',
    '      ){',
    '        picks.push("dive");',
    '        budget -= Number(enemyTypes.dive.cost || 0);',
    '      }',
    '',
    '      if(',
    '        sectorTheme &&',
    '        sectorTheme.id === "siege" &&',
    '        level % 5 === 0 &&',
    '        picks.length < maxCount &&',
    '        enemyTypes.tank &&',
    '        budget >= Number(enemyTypes.tank.cost || 0)',
    '      ){',
    '        picks.push("tank");',
    '        budget -= Number(enemyTypes.tank.cost || 0);',
    '      }',
    '',
    '      var slots = buildFormationSlots({',
    '        count: picks.length,',
    '        formation: profile.formation,',
    '        width: width,',
    '        rand: rand',
    '      });',
    '',
    '      var enemies = [];',
    '      var i;',
    '      for(i = 0; i < picks.length; i++){',
    '        var enemy = makeEnemy({',
    '          typeId: picks[i],',
    '          slot: slots[i],',
    '          profile: profile,',
    '          index: i,',
    '          enemyTypes: enemyTypes,',
    '          rand: rand,',
    '          randInt: randInt',
    '        });',
    '        if(enemy){',
    '          enemies.push(enemy);',
    '        }',
    '      }',
    '',
    '      return {',
    '        enemies: enemies,',
    '        profile: profile,',
    '        label: buildWaveLabel(level, profile)',
    '      };',
    '    }',
    '',
    '    return {',
    '      buildWaveSpec: buildWaveSpec,',
    '      getLevelProfile: getLevelProfile',
    '    };',
    '  }',
    '',
    `  var runtimeConfig = ${runtimeJson};`,
    '  var runtimeHooks = game.__astroV2RuntimeHooks || {};',
    '  runtimeHooks.waveProgression = createWaveProgressionRuntime(runtimeConfig);',
    '  game.__astroV2RuntimeHooks = runtimeHooks;',
    '  if(typeof game.setV2RuntimeHooks === "function"){',
    '    game.setV2RuntimeHooks(runtimeHooks);',
    '  }',
    '',
    '  runtimePatch.runtime = runtimePatch.runtime || {};',
    '  runtimePatch.runtime.waveProgression = {',
    '    module: "wave-progression-runtime-hooks",',
    '    status: "active",',
    '    behaviorParity: "legacy-v1-wave-system"',
    '  };',
    '})();'
  ].join('\n');
}

export const waveProgressionRuntimeModule = {
  id: 'wave-progression-runtime-hooks',
  priority: 33,
  description: 'Injects wave profile, formation, and enemy composition runtime hooks.',
  apply(artifact){
    artifact.runtimePatch.runtime = artifact.runtimePatch.runtime || {};
    artifact.runtimePatch.runtime.waveProgressionConfig = cloneSerializable(waveProgressionRuntimeConfig);

    artifact.runtimeSnippets = artifact.runtimeSnippets || [];
    artifact.runtimeSnippets.push(buildRuntimeSnippet(waveProgressionRuntimeConfig));
    return artifact;
  }
};
