#!/usr/bin/env node
/**
 * collection-run.mjs — mint "The Machinery", a pixel-art collection by Wizard-3.
 *
 * DRY RUN BY DEFAULT. With no flags it runs the whole loop against a fake
 * chain: no key is read, nothing is signed, nothing is sent, and no request
 * leaves this process. `--broadcast` is the only thing that spends.
 *
 * Eight 16x16 plates of the parts of the mint path, then a manifest minted with
 * all eight as on-chain dependencies. The Builder conceived it, the generator
 * draws it, and the Builder's wallet pays for it.
 *
 * See the plan and the sizes without touching anything at all:
 *   node scripts/wizard/collection-run.mjs --preview
 *
 * Rehearse the whole mint against a fake chain:
 *   node scripts/wizard/collection-run.mjs --all --dry
 *
 * Write the plates out to look at them:
 *   node scripts/wizard/collection-run.mjs --write /tmp/machinery
 *
 * What is confirmed, pending or missing, with every on-chain plate compared to
 * its generated bytes:
 *   node scripts/wizard/collection-run.mjs --status
 *
 * Really do it (real mainnet transactions, real STX, irreversible):
 *   node scripts/wizard/collection-run.mjs --all --broadcast
 *
 * Every rail inscribe.mjs applies to one mint applies to each mint here, plus
 * the run journal, the nonce asymmetry, the run-level spend cap and the kill
 * switch, all imported from run-thread-core.mjs rather than restated. The one
 * rail with no corpus equivalent is the member check: the manifest refuses to
 * name an id whose chunk u0 is not byte-identical to the plate it claims to be.
 *
 * There is no `--resolve` here, and that is not an omission. A corpus entry
 * quotes the block it was written at, so a lost transaction id can never
 * afterwards be matched by content hash and only a human can close it. A plate
 * names no block and no fee, so its hash never changes and `--status` can
 * settle the same question definitively at any point in the future.
 *
 * See scripts/wizard/README.md.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

import {
  DEFAULT_BALANCE_FLOOR_USTX,
  DEFAULT_HIRO_URL,
  DEFAULT_MAX_TX_FEE_USTX,
  DEFAULT_SPEND_CAP_USTX,
  WizardSafetyError,
  groupDigits,
  killSwitchEngaged,
  loadWizardEnv
} from './inscribe.mjs';
import { journalPorts, liveSubmit, makeFakeChain, fakeFetch, walletsFor } from './run-thread.mjs';
import {
  COLLECTION_CONCEPT,
  COLLECTION_ID,
  COLLECTION_LENGTH,
  PIECES,
  composeCollectionManifest,
  describeCollection,
  renderPiece
} from './collection-art.mjs';
import {
  COLLECTION_WIZARD,
  DEFAULT_CONFIRM_POLL_MS,
  DEFAULT_CONFIRM_TIMEOUT_MS,
  DEFAULT_MEMPOOL_POLL_MS,
  DEFAULT_MEMPOOL_WAIT_MS,
  DEFAULT_RUN_SPEND_CAP_USTX,
  collectionStatusReport,
  formatCollectionPlan,
  formatCollectionRunReport,
  formatCollectionStatusTable,
  runCollection
} from './collection-run-core.mjs';

/* ------------------------------------------------------------------ */
/* argv                                                                */
/* ------------------------------------------------------------------ */

const arg = (name, fallback = null) => {
  const index = process.argv.indexOf(`--${name}`);
  if (index === -1) return fallback;
  const value = process.argv[index + 1];
  return value && !value.startsWith('--') ? value : true;
};
const flag = (name) => arg(name) === true;
const text = (name, fallback = null) => (typeof arg(name) === 'string' ? arg(name) : fallback);
const csv = (value) =>
  value && typeof value === 'string' ? value.split(',').map((part) => part.trim()).filter(Boolean) : [];

const say = (line = '') => console.log(line);

/* ------------------------------------------------------------------ */
/* the fake chain, for --dry                                           */
/* ------------------------------------------------------------------ */

/**
 * The fake chain, the fake fetch and the wallet resolver are imported from
 * run-thread.mjs rather than re-implemented. They already answer every read
 * this runner makes — quote, pause, chunk, creator, hash lookup, tip, balance,
 * nonces, transaction — and a second fake would be a second thing to drift away
 * from the real encoders.
 *
 * The journal is held in memory and never written. A dry run invents its
 * inscription ids and its transaction ids, and a file full of invented txids
 * sitting next to the real one is an accident waiting to happen.
 */
function dryPorts({ chain, wallets, out = say }) {
  let journal = null;
  return {
    readJournal: () => journal,
    writeJournal: (path, value) => {
      journal = value;
    },
    fetchImpl: fakeFetch(chain),
    killSwitch: (env) => killSwitchEngaged(env),
    now: () => Date.UTC(2026, 6, 31, 12, 0, 0),
    sleep: async () => {},
    say: out,
    presentPlan: (plan, options) => out(formatCollectionPlan(plan, options)),
    // `out` rather than `say` throughout, so a caller that wants the real
    // fetch, submit and journal ports without the terminal can have them. The
    // ports a test cares about are the ones that could spend; the presenter is
    // not one of them and it prints a whole plan per mint.
    submit: async ({ plan, broadcast, wizardId, minerFeeUstx }) => {
      if (broadcast === true) {
        throw new WizardSafetyError('the dry submit port was asked to broadcast. It cannot, and it did not.');
      }
      const minted = chain.mint(plan.body, wallets[wizardId]?.address ?? null, minerFeeUstx);
      out(`    [dry] minted into the fake chain as #${minted.id}; nothing was signed and nothing was sent`);
      return { txid: minted.txid };
    }
  };
}

/* ------------------------------------------------------------------ */
/* cli                                                                 */
/* ------------------------------------------------------------------ */

function usage() {
  say('collection-run.mjs — mint "The Machinery", the Builder\'s pixel-art collection.');
  say('');
  say('  DRY RUN BY DEFAULT. --broadcast is the only flag that spends.');
  say('');
  say('  --preview                the concept, every plate and its byte size, and the manifest. Reads nothing.');
  say('  --write <dir>            write every plate to <dir> as an .svg. Reads nothing, sends nothing.');
  say('  --all                    every piece plus the manifest (the usual run)');
  say('  --piece <n>              just one piece');
  say('  --from <n> --to <n>      a range of pieces');
  say('  --ids <a,b,c>            inscription ids for pieces already minted, in piece order');
  say('  --dry                    the default: the whole loop against a fake chain');
  say('  --broadcast              real mainnet transactions, real STX, irreversible');
  say('  --status                 journal plus chain, as a table. Runs nothing.');
  say('  --no-manifest            stop after the last piece, do not close the collection');
  say('  --collection <id>        the collection id (default ' + COLLECTION_ID + ')');
  say('  --run-spend-cap-ustx <n> cap across the whole run (default ' + groupDigits(DEFAULT_RUN_SPEND_CAP_USTX) + ')');
  say('  --spend-cap-ustx <n>     cap for any one mint (default ' + groupDigits(DEFAULT_SPEND_CAP_USTX) + ')');
  say('  --balance-floor-ustx <n> never spend the wallet below this');
  say('  --max-tx-fee-ustx <n>    miner fee bid per transaction');
  say('  --confirm-timeout-minutes <n>  how long to wait for one transaction');
  say('  --poll-seconds <n>       gap between transaction lookups');
  say('  --mempool-wait-minutes <n>     how long to wait on a lost txid whose nonce is still pending');
  say('  --mempool-poll-seconds <n>     gap between those lookups');
  say('  --hiro <url>             Hiro endpoint');
  say('');
  say(`  pieces: ${PIECES.map((piece) => `${piece.index} ${piece.id}`).join(', ')}`);
  say('');
  say('  There is no --resolve. A plate names no block and no fee, so its bytes never change and --status');
  say('  settles a lost transaction id by content hash at any point in the future.');
  say('');
  say('  See scripts/wizard/README.md.');
}

/** The concept and the plates, with no chain and no journal involved at all. */
function preview({ collectionId }) {
  say('');
  say(COLLECTION_CONCEPT);
  say('');
  for (const line of describeCollection()) say(line);
  say('');
  say('=== PREVIEW: the manifest below lists SYNTHETIC ids. Nothing here is on chain. ===');
  say('');
  say(
    composeCollectionManifest({
      collectionId,
      members: PIECES.map((piece) => ({ index: piece.index, id: String(9000 + piece.index) }))
    })
  );
  say('=== PREVIEW END. No key was read, no transaction was built, nothing was sent. ===');
}

async function main() {
  if (flag('help')) {
    usage();
    return 0;
  }

  loadWizardEnv();
  const env = process.env;
  const hiroUrl = text('hiro', DEFAULT_HIRO_URL);
  const collectionId = text('collection', COLLECTION_ID);

  if (flag('preview')) {
    preview({ collectionId });
    return 0;
  }

  if (typeof arg('write') === 'string') {
    const dir = arg('write');
    mkdirSync(dir, { recursive: true });
    for (const piece of PIECES) {
      const file = join(dir, `${String(piece.index).padStart(2, '0')}-${piece.id}.svg`);
      writeFileSync(file, renderPiece(piece.index), 'utf8');
      say(`  wrote ${file}`);
    }
    say('');
    say('Nothing was signed and nothing was sent. These are the exact bytes a mint would carry.');
    return 0;
  }

  if (arg('status')) {
    const ids = csv(arg('ids'));
    const report = await collectionStatusReport({
      ports: { ...journalPorts(), fetchImpl: globalThis.fetch },
      options: {
        collectionId,
        hiroUrl,
        knownIds: Object.fromEntries(ids.map((id, index) => [String(index + 1), id]))
      }
    });
    say(formatCollectionStatusTable(report));
    return 0;
  }

  const broadcast = flag('broadcast');
  const piece = arg('piece') ? Number(arg('piece')) : null;
  const from = piece ?? Number(arg('from', 1));
  const to = piece ?? Number(arg('to', COLLECTION_LENGTH));
  const ids = csv(arg('ids'));

  const options = {
    collectionId,
    from,
    to,
    broadcast,
    manifest: !flag('no-manifest'),
    wizard: COLLECTION_WIZARD,
    hiroUrl,
    env,
    runSpendCapUstx: BigInt(arg('run-spend-cap-ustx', String(DEFAULT_RUN_SPEND_CAP_USTX))),
    spendCapUstx: BigInt(arg('spend-cap-ustx', String(DEFAULT_SPEND_CAP_USTX))),
    balanceFloorUstx: BigInt(arg('balance-floor-ustx', String(DEFAULT_BALANCE_FLOOR_USTX))),
    minerFeeUstx: BigInt(arg('max-tx-fee-ustx', String(DEFAULT_MAX_TX_FEE_USTX))),
    confirmTimeoutMs: arg('confirm-timeout-minutes')
      ? Number(arg('confirm-timeout-minutes')) * 60_000
      : DEFAULT_CONFIRM_TIMEOUT_MS,
    confirmPollMs: arg('poll-seconds') ? Number(arg('poll-seconds')) * 1_000 : DEFAULT_CONFIRM_POLL_MS,
    mempoolWaitMs: arg('mempool-wait-minutes')
      ? Number(arg('mempool-wait-minutes')) * 60_000
      : DEFAULT_MEMPOOL_WAIT_MS,
    mempoolPollMs: arg('mempool-poll-seconds')
      ? Number(arg('mempool-poll-seconds')) * 1_000
      : DEFAULT_MEMPOOL_POLL_MS
  };

  const wallets = walletsFor({ env, broadcast });
  options.wallets = wallets;
  let ports;

  if (broadcast) {
    options.knownIds = Object.fromEntries(ids.map((id, index) => [String(index + 1), id]));
    ports = {
      ...journalPorts(),
      fetchImpl: globalThis.fetch,
      killSwitch: (killEnv) => killSwitchEngaged(killEnv),
      now: () => Date.now(),
      sleep: (ms) => new Promise((resolve) => setTimeout(resolve, ms)),
      say,
      presentPlan: (plan, presentOptions) => say(formatCollectionPlan(plan, presentOptions)),
      submit: liveSubmit({ hiroUrl })
    };
    say('');
    say('=== BROADCAST. Every mint below is a real mainnet transaction and cannot be undone. ===');
  } else {
    // Pieces already minted have to exist for the manifest to list them, so a
    // dry run serves them from a fake chain. Real ids when --ids supplies them,
    // synthetic ones otherwise, said out loud either way.
    const chain = makeFakeChain({ tip: 8_700_000, feeUstx: 11_000n });
    const priorIds = Array.from(
      { length: Math.max(0, Math.min(from, COLLECTION_LENGTH) - 1) },
      (_, index) => ids[index] ?? String(9001 + index)
    );
    options.knownIds = Object.fromEntries(priorIds.map((id, index) => [String(index + 1), id]));
    for (const [index, id] of priorIds.entries()) {
      chain.add(id, renderPiece(index + 1), wallets[COLLECTION_WIZARD]?.address ?? null);
    }

    ports = dryPorts({ chain, wallets });
    say('');
    say('=== DRY RUN. A fake chain in this process. No key is read, nothing is signed, nothing is sent. ===');
    if (priorIds.length > 0) {
      const synthetic = priorIds.filter((id, index) => ids[index] === undefined);
      say(
        `    pieces 1..${from - 1} are served from locally generated plates at ${priorIds.map((id) => `#${id}`).join(', ')}` +
          (synthetic.length > 0
            ? `. ${synthetic.map((id) => `#${id}`).join(', ')} ${synthetic.length === 1 ? 'is' : 'are'} SYNTHETIC — ` +
              'pass --ids to rehearse against the real ones.'
            : '.')
      );
    }
    say('');
  }

  const result = await runCollection({ ports, options });
  say(formatCollectionRunReport(result));

  if (!result.ok) return 1;
  if (!broadcast) {
    say('');
    say('To do this for real, re-run with --broadcast and the real ids:');
    say(
      `  node scripts/wizard/collection-run.mjs --from ${from} --to ${to}` +
        `${ids.length ? ` --ids ${ids.join(',')}` : ''} --broadcast`
    );
  }
  return 0;
}

const isDirectRun = Boolean(process.argv[1]) && pathToFileURL(process.argv[1]).href === import.meta.url;
if (isDirectRun) {
  main()
    .then((code) => {
      process.exitCode = code ?? 0;
    })
    .catch((error) => {
      console.error(`\n${error?.name === 'WizardSafetyError' || error?.name === 'WizardComposeError' ? error.message : error}`);
      process.exitCode = 1;
    });
}

export { dryPorts, preview };
