#!/usr/bin/env node
/**
 * collection-run.mjs — mint and list a wizard's pixel-art collection.
 *
 * DRY RUN BY DEFAULT. With no flags it runs the whole loop against a fake
 * chain: no key is read, nothing is signed, nothing is sent, and no request
 * leaves this process. `--broadcast` is the only thing that spends.
 *
 * There are three collections, one per wizard, all drawing the same eight parts
 * of the mint path through that wizard's fixed concern:
 *
 *   c-machinery-001  The Machinery        Wizard-3, the Builder
 *   c-keeping-001    The Cost of Keeping  Wizard-1, the Archivist
 *   c-omission-001   What the Hash Omits  Wizard-2, the Skeptic
 *
 * `--collection <id>` picks one; the Builder's is the default, so every command
 * that worked when there was one collection still does the same thing. The
 * wizard is not a flag: a collection is minted and listed by the wizard that
 * conceived it, out of that wizard's wallet, or not at all.
 *
 * See the plan and the sizes without touching anything at all:
 *   node scripts/wizard/collection-run.mjs --preview
 *   node scripts/wizard/collection-run.mjs --collections
 *
 * Rehearse the whole mint against a fake chain:
 *   node scripts/wizard/collection-run.mjs --all --dry
 *   node scripts/wizard/collection-run.mjs --collection c-keeping-001 --all --dry
 *
 * Write the plates out to look at them:
 *   node scripts/wizard/collection-run.mjs --write /tmp/machinery
 *
 * What is confirmed, pending or missing, with every on-chain plate compared to
 * its generated bytes:
 *   node scripts/wizard/collection-run.mjs --status
 *
 * List what has been minted, at that wizard's own price:
 *   node scripts/wizard/collection-run.mjs --collection c-keeping-001 --list --dry
 *
 * Really do it (real mainnet transactions, real STX, irreversible):
 *   node scripts/wizard/collection-run.mjs --all --broadcast
 *
 * Every rail inscribe.mjs applies to one mint applies to each mint here, plus
 * the run journal, the nonce asymmetry, the run-level spend cap and the kill
 * switch, all imported from run-thread-core.mjs rather than restated. The one
 * rail with no corpus equivalent is the member check: the manifest refuses to
 * name an id whose chunk u0 is not byte-identical to the plate it claims to be.
 * The listing path imports market-run-core.mjs whole for the same reason.
 *
 * There is no `--resolve` here, and that is not an omission. A corpus entry
 * quotes the block it was written at, so a lost transaction id can never
 * afterwards be matched by content hash and only a human can close it. A plate
 * names no block and no fee, so its hash never changes and `--status` can
 * settle the same question definitively at any point in the future.
 *
 * See scripts/wizard/README.md.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

import {
  DEFAULT_BALANCE_FLOOR_USTX,
  DEFAULT_HIRO_URL,
  DEFAULT_MAX_TX_FEE_USTX,
  DEFAULT_SPEND_CAP_USTX,
  WizardSafetyError,
  groupDigits,
  killSwitchEngaged,
  loadWizardEnv
} from './inscribe.mjs';
import { journalPorts, liveSubmit, makeFakeChain, fakeFetch, walletsFor } from './run-thread.mjs';
import {
  dryPorts as marketDryPorts,
  journalPorts as marketJournalPorts,
  liveSubmit as marketLiveSubmit,
  makeFakeMarket
} from './market-run.mjs';
import { COLLECTION_IDS, DEFAULT_COLLECTION_ID, describeCollections, getCollection } from './collections.mjs';
import {
  DEFAULT_CONFIRM_POLL_MS,
  DEFAULT_CONFIRM_TIMEOUT_MS,
  DEFAULT_MEMPOOL_POLL_MS,
  DEFAULT_MEMPOOL_WAIT_MS,
  DEFAULT_RUN_SPEND_CAP_USTX,
  collectionStatusReport,
  formatCollectionPlan,
  formatCollectionRunReport,
  formatCollectionStatusTable,
  runCollection
} from './collection-run-core.mjs';
import {
  DEFAULT_LISTING_MARKET,
  DEFAULT_LISTING_RUN_SPEND_CAP_USTX,
  MANIFEST_KEY,
  MARKET_KEYS,
  MIN_FEE_BUDGET_USTX,
  collectionListingPlan,
  formatCollectionListingPlan,
  formatCollectionListingReport,
  idsFromMintJournal,
  listCollection
} from './collection-market.mjs';

/* ------------------------------------------------------------------ */
/* argv                                                                */
/* ------------------------------------------------------------------ */

const arg = (name, fallback = null) => {
  const index = process.argv.indexOf(`--${name}`);
  if (index === -1) return fallback;
  const value = process.argv[index + 1];
  return value && !value.startsWith('--') ? value : true;
};
const flag = (name) => arg(name) === true;
const text = (name, fallback = null) => (typeof arg(name) === 'string' ? arg(name) : fallback);
const csv = (value) =>
  value && typeof value === 'string' ? value.split(',').map((part) => part.trim()).filter(Boolean) : [];

const say = (line = '') => console.log(line);

/* ------------------------------------------------------------------ */
/* the fake chain, for --dry                                           */
/* ------------------------------------------------------------------ */

/**
 * The fake chain, the fake fetch and the wallet resolver are imported from
 * run-thread.mjs rather than re-implemented. They already answer every read
 * this runner makes — quote, pause, chunk, creator, hash lookup, tip, balance,
 * nonces, transaction — and a second fake would be a second thing to drift away
 * from the real encoders.
 *
 * The journal is held in memory and never written. A dry run invents its
 * inscription ids and its transaction ids, and a file full of invented txids
 * sitting next to the real one is an accident waiting to happen.
 */
function dryPorts({ chain, wallets, wizard = 'builder', out = say }) {
  let journal = null;
  return {
    readJournal: () => journal,
    writeJournal: (path, value) => {
      journal = value;
    },
    fetchImpl: fakeFetch(chain),
    killSwitch: (env) => killSwitchEngaged(env),
    now: () => Date.UTC(2026, 6, 31, 12, 0, 0),
    sleep: async () => {},
    say: out,
    presentPlan: (plan, options) => out(formatCollectionPlan(plan, options)),
    // `out` rather than `say` throughout, so a caller that wants the real
    // fetch, submit and journal ports without the terminal can have them. The
    // ports a test cares about are the ones that could spend; the presenter is
    // not one of them and it prints a whole plan per mint.
    submit: async ({ plan, broadcast, wizardId, minerFeeUstx }) => {
      if (broadcast === true) {
        throw new WizardSafetyError('the dry submit port was asked to broadcast. It cannot, and it did not.');
      }
      const minted = chain.mint(plan.body, wallets[wizardId ?? wizard]?.address ?? null, minerFeeUstx);
      out(`    [dry] minted into the fake chain as #${minted.id}; nothing was signed and nothing was sent`);
      return { txid: minted.txid };
    }
  };
}

/**
 * The fake market for `--list --dry`, imported whole from market-run.mjs.
 *
 * The tokens being listed have to exist and have to be owned by the seller, so
 * they are minted into the fake market first and the seller is funded. That is
 * setup for a rehearsal and not a claim about the real chain: `--list --dry`
 * proves the sweep's shape, its prices and its refusals, and proves nothing at
 * all about whether those inscriptions are really there.
 */
function listingDryPorts({ art, ids, wallets, minerFeeUstx, out = say }) {
  const chain = makeFakeMarket({ tip: 8_700_000, minerFeeUstx });
  const address = wallets[art.wizard]?.address ?? null;
  for (const id of Object.values(ids)) chain.mint(id, address);
  if (address) chain.fund(address, 50_000_000n);
  const ports = marketDryPorts({ chain, sponsor: null, minerFeeUstx });

  // One journal per run id, in memory, never written. The market runner's own
  // dry ports keep a single journal because a market run is one run; a listing
  // sweep is nine of them, each with its own id, and a shared slot makes run
  // two load run one's record and halt on the mismatch. Keyed by path, which is
  // exactly what a real journal is keyed by.
  const journals = new Map();
  return {
    chain,
    ports: {
      ...ports,
      readJournal: (path) => journals.get(path) ?? null,
      writeJournal: (path, value) => journals.set(path, value),
      say: out,
      presentPlan: () => {}
    }
  };
}

/* ------------------------------------------------------------------ */
/* cli                                                                 */
/* ------------------------------------------------------------------ */

function usage() {
  say('collection-run.mjs — mint and list the wizards\' pixel-art collections.');
  say('');
  say('  DRY RUN BY DEFAULT. --broadcast is the only flag that spends.');
  say('');
  say('  --collections            the three collections and who drew them. Reads nothing.');
  say('  --collection <id>        which one (default ' + DEFAULT_COLLECTION_ID + ')');
  say('  --preview                the concept, every plate and its byte size, and the manifest. Reads nothing.');
  say('  --write <dir>            write every plate to <dir> as an .svg. Reads nothing, sends nothing.');
  say('  --all                    every piece plus the manifest (the usual run)');
  say('  --piece <n>              just one piece');
  say('  --from <n> --to <n>      a range of pieces');
  say('  --ids <a,b,c>            inscription ids for pieces already minted, in piece order');
  say('  --dry                    the default: the whole loop against a fake chain');
  say('  --broadcast              real mainnet transactions, real STX, irreversible');
  say('  --status                 journal plus chain, as a table. Runs nothing.');
  say('  --no-manifest            stop after the last piece, do not close the collection');
  say('');
  say('  --list                   list what has been minted, at this wizard\'s own price');
  say('  --market <key>           which sponsored market to list on: ' + MARKET_KEYS.join(', ') + ` (default ${DEFAULT_LISTING_MARKET})`);
  say('  --manifest-id <id>       the manifest inscription id, for --list');
  say('  --only <a,b,manifest>    list only these members');
  say('  --fee-budget-ustx <n>    sponsorship deposit per listing, always STX (default ' + groupDigits(MIN_FEE_BUDGET_USTX) + ')');
  say('  --listing-cap-ustx <n>   cap across a whole listing sweep (default ' + groupDigits(DEFAULT_LISTING_RUN_SPEND_CAP_USTX) + ')');
  say('');
  say('  --run-spend-cap-ustx <n> cap across the whole mint run (default ' + groupDigits(DEFAULT_RUN_SPEND_CAP_USTX) + ')');
  say('  --spend-cap-ustx <n>     cap for any one mint (default ' + groupDigits(DEFAULT_SPEND_CAP_USTX) + ')');
  say('  --balance-floor-ustx <n> never spend the wallet below this');
  say('  --max-tx-fee-ustx <n>    miner fee bid per transaction');
  say('  --confirm-timeout-minutes <n>  how long to wait for one transaction');
  say('  --poll-seconds <n>       gap between transaction lookups');
  say('  --mempool-wait-minutes <n>     how long to wait on a lost txid whose nonce is still pending');
  say('  --mempool-poll-seconds <n>     gap between those lookups');
  say('  --hiro <url>             Hiro endpoint');
  say('');
  for (const line of describeCollections()) say(line);
  say('');
  say('  There is no --resolve. A plate names no block and no fee, so its bytes never change and --status');
  say('  settles a lost transaction id by content hash at any point in the future.');
  say('');
  say('  There is no --seller either. A collection is listed by the wizard that minted it.');
  say('');
  say('  See scripts/wizard/README.md.');
}

/** The concept and the plates, with no chain and no journal involved at all. */
function preview({ art, collectionId }) {
  say('');
  say(art.concept);
  say('');
  for (const line of art.describeLines()) say(line);
  say('');
  say(
    `asking ${groupDigits(art.price.pieceUstx)} microSTX a plate and ${groupDigits(art.price.manifestUstx)} for ` +
      `the list. ${art.pricing.reasoning}`
  );
  say('');
  say('=== PREVIEW: the manifest below lists SYNTHETIC ids. Nothing here is on chain. ===');
  say('');
  say(
    art.composeManifest({
      collectionId,
      members: art.pieces.map((piece) => ({ index: piece.index, id: String(9000 + piece.index) }))
    })
  );
  say('=== PREVIEW END. No key was read, no transaction was built, nothing was sent. ===');
}

/**
 * `--list`: which ids, from where.
 *
 * `--ids` and `--manifest-id` win, because an operator naming an id is making a
 * deliberate statement. Failing that the mint journal is read, which is the
 * only other place that knows what this collection actually minted.
 */
function listingIdsFor({ art, ids, manifestId, journal }) {
  const fromJournal = idsFromMintJournal(journal);
  const resolved = { ...fromJournal };
  for (const [index, id] of ids.entries()) resolved[String(index + 1)] = id;
  if (manifestId) resolved[MANIFEST_KEY] = manifestId;
  // Never list a key the collection does not have. A stray --ids entry past the
  // end would otherwise become a listing of somebody else's token at this
  // collection's price.
  const keys = new Set([...art.pieces.map((piece) => String(piece.index)), MANIFEST_KEY]);
  return Object.fromEntries(Object.entries(resolved).filter(([key]) => keys.has(key)));
}

async function main() {
  if (flag('help')) {
    usage();
    return 0;
  }
  if (flag('collections')) {
    say('');
    for (const line of describeCollections()) say(line);
    say('');
    say('Same eight subjects in all three: chunk, fold, seal, dependency edge, nonce, miner fee,');
    say('post-condition, escrow. Different readings, different pictures, different prices.');
    return 0;
  }

  loadWizardEnv();
  const env = process.env;
  const hiroUrl = text('hiro', DEFAULT_HIRO_URL);
  const collectionId = text('collection', DEFAULT_COLLECTION_ID);
  const art = getCollection(collectionId);
  const wizard = art.wizard;

  if (flag('preview')) {
    preview({ art, collectionId: art.id });
    return 0;
  }

  if (typeof arg('write') === 'string') {
    const dir = arg('write');
    mkdirSync(dir, { recursive: true });
    for (const piece of art.pieces) {
      const file = join(dir, `${String(piece.index).padStart(2, '0')}-${piece.id}.svg`);
      writeFileSync(file, art.renderPiece(piece.index), 'utf8');
      say(`  wrote ${file}`);
    }
    say('');
    say('Nothing was signed and nothing was sent. These are the exact bytes a mint would carry.');
    return 0;
  }

  const broadcast = flag('broadcast');
  const ids = csv(arg('ids'));

  if (arg('status')) {
    const report = await collectionStatusReport({
      ports: { ...journalPorts(), fetchImpl: globalThis.fetch },
      options: {
        collectionId: art.id,
        hiroUrl,
        knownIds: Object.fromEntries(ids.map((id, index) => [String(index + 1), id]))
      }
    });
    say(formatCollectionStatusTable(report));
    return 0;
  }

  const minerFeeUstx = BigInt(arg('max-tx-fee-ustx', String(DEFAULT_MAX_TX_FEE_USTX)));

  /* ---------------------------------------------------------------- */
  /* --list                                                            */
  /* ---------------------------------------------------------------- */

  if (flag('list')) {
    const wallets = walletsFor({ env, broadcast });
    const marketKey = text('market', DEFAULT_LISTING_MARKET);
    const journalIo = journalPorts();
    const mintJournalPath = join(
      new URL('.', import.meta.url).pathname,
      `.collection-${art.id}${broadcast ? '' : '.dry'}.json`
    );
    const listingIds = listingIdsFor({
      art,
      ids,
      manifestId: text('manifest-id', null),
      journal: broadcast ? journalIo.readJournal(mintJournalPath) : null
    });

    const plan = collectionListingPlan({
      collectionId: art.id,
      ids: listingIds,
      market: marketKey,
      feeBudgetUstx: BigInt(arg('fee-budget-ustx', String(MIN_FEE_BUDGET_USTX)))
    });
    say('');
    say(formatCollectionListingPlan(plan, { broadcast }));

    if (plan.listable.length === 0) {
      say('');
      say('Nothing to list. Mint the collection first, or pass --ids and --manifest-id.');
      return 1;
    }

    let ports;
    if (broadcast) {
      ports = {
        ...marketJournalPorts(),
        fetchImpl: globalThis.fetch,
        killSwitch: (killEnv) => killSwitchEngaged(killEnv),
        now: () => Date.now(),
        sleep: (ms) => new Promise((resolve) => setTimeout(resolve, ms)),
        say,
        presentPlan: () => {},
        submit: marketLiveSubmit({ hiroUrl }),
        sponsor: null
      };
      say('');
      say('=== BROADCAST. Every listing below is a real mainnet transaction and cannot be undone. ===');
    } else {
      // Dry: the ids being listed are served from a fake market that has been
      // told they exist. That is rehearsal scaffolding and it is said out loud
      // rather than left for someone to infer from a green table.
      ports = listingDryPorts({ art, ids: listingIds, wallets, minerFeeUstx }).ports;
      say('');
      say('=== DRY RUN. A fake market in this process. No key is read, nothing is signed, nothing is sent. ===');
      say('    the inscriptions below are minted into the fake market first, so the sweep has something to list.');
    }

    const result = await listCollection({
      ports,
      options: {
        collectionId: art.id,
        ids: listingIds,
        market: marketKey,
        broadcast,
        only: csv(arg('only')).length > 0 ? csv(arg('only')) : null,
        env,
        wallets,
        hiroUrl,
        feeBudgetUstx: BigInt(arg('fee-budget-ustx', String(MIN_FEE_BUDGET_USTX))),
        runSpendCapUstx: BigInt(arg('listing-cap-ustx', String(DEFAULT_LISTING_RUN_SPEND_CAP_USTX))),
        balanceFloorUstx: BigInt(arg('balance-floor-ustx', String(DEFAULT_BALANCE_FLOOR_USTX))),
        minerFeeUstx,
        confirmTimeoutMs: arg('confirm-timeout-minutes')
          ? Number(arg('confirm-timeout-minutes')) * 60_000
          : DEFAULT_CONFIRM_TIMEOUT_MS,
        confirmPollMs: arg('poll-seconds') ? Number(arg('poll-seconds')) * 1_000 : DEFAULT_CONFIRM_POLL_MS
      }
    });
    say(formatCollectionListingReport(result));
    return result.ok ? 0 : 1;
  }

  /* ---------------------------------------------------------------- */
  /* the mint                                                          */
  /* ---------------------------------------------------------------- */

  const piece = arg('piece') ? Number(arg('piece')) : null;
  const from = piece ?? Number(arg('from', 1));
  const to = piece ?? Number(arg('to', art.length));

  const options = {
    collectionId: art.id,
    from,
    to,
    broadcast,
    manifest: !flag('no-manifest'),
    hiroUrl,
    env,
    runSpendCapUstx: BigInt(arg('run-spend-cap-ustx', String(DEFAULT_RUN_SPEND_CAP_USTX))),
    spendCapUstx: BigInt(arg('spend-cap-ustx', String(DEFAULT_SPEND_CAP_USTX))),
    balanceFloorUstx: BigInt(arg('balance-floor-ustx', String(DEFAULT_BALANCE_FLOOR_USTX))),
    minerFeeUstx,
    confirmTimeoutMs: arg('confirm-timeout-minutes')
      ? Number(arg('confirm-timeout-minutes')) * 60_000
      : DEFAULT_CONFIRM_TIMEOUT_MS,
    confirmPollMs: arg('poll-seconds') ? Number(arg('poll-seconds')) * 1_000 : DEFAULT_CONFIRM_POLL_MS,
    mempoolWaitMs: arg('mempool-wait-minutes')
      ? Number(arg('mempool-wait-minutes')) * 60_000
      : DEFAULT_MEMPOOL_WAIT_MS,
    mempoolPollMs: arg('mempool-poll-seconds')
      ? Number(arg('mempool-poll-seconds')) * 1_000
      : DEFAULT_MEMPOOL_POLL_MS
  };

  const wallets = walletsFor({ env, broadcast });
  options.wallets = wallets;
  let ports;

  if (broadcast) {
    options.knownIds = Object.fromEntries(ids.map((id, index) => [String(index + 1), id]));
    ports = {
      ...journalPorts(),
      fetchImpl: globalThis.fetch,
      killSwitch: (killEnv) => killSwitchEngaged(killEnv),
      now: () => Date.now(),
      sleep: (ms) => new Promise((resolve) => setTimeout(resolve, ms)),
      say,
      presentPlan: (plan, presentOptions) => say(formatCollectionPlan(plan, presentOptions)),
      submit: liveSubmit({ hiroUrl })
    };
    say('');
    say(`=== BROADCAST. Every mint below is a real mainnet transaction and cannot be undone. (${art.title}) ===`);
  } else {
    // Pieces already minted have to exist for the manifest to list them, so a
    // dry run serves them from a fake chain. Real ids when --ids supplies them,
    // synthetic ones otherwise, said out loud either way.
    const chain = makeFakeChain({ tip: 8_700_000, feeUstx: 11_000n });
    const priorIds = Array.from(
      { length: Math.max(0, Math.min(from, art.length) - 1) },
      (_, index) => ids[index] ?? String(9001 + index)
    );
    options.knownIds = Object.fromEntries(priorIds.map((id, index) => [String(index + 1), id]));
    for (const [index, id] of priorIds.entries()) {
      chain.add(id, art.renderPiece(index + 1), wallets[wizard]?.address ?? null);
    }

    ports = dryPorts({ chain, wallets, wizard });
    say('');
    say(`=== DRY RUN (${art.title}). A fake chain in this process. No key is read, nothing is signed, nothing is sent. ===`);
    if (priorIds.length > 0) {
      const synthetic = priorIds.filter((id, index) => ids[index] === undefined);
      say(
        `    pieces 1..${from - 1} are served from locally generated plates at ${priorIds.map((id) => `#${id}`).join(', ')}` +
          (synthetic.length > 0
            ? `. ${synthetic.map((id) => `#${id}`).join(', ')} ${synthetic.length === 1 ? 'is' : 'are'} SYNTHETIC — ` +
              'pass --ids to rehearse against the real ones.'
            : '.')
      );
    }
    say('');
  }

  const result = await runCollection({ ports, options });
  say(formatCollectionRunReport(result));

  if (!result.ok) return 1;
  if (!broadcast) {
    say('');
    say('To do this for real, re-run with --broadcast and the real ids:');
    say(
      `  node scripts/wizard/collection-run.mjs --collection ${art.id} --from ${from} --to ${to}` +
        `${ids.length ? ` --ids ${ids.join(',')}` : ''} --broadcast`
    );
    say('');
    say(`Then list it: node scripts/wizard/collection-run.mjs --collection ${art.id} --list --broadcast`);
  }
  return 0;
}

const isDirectRun = Boolean(process.argv[1]) && pathToFileURL(process.argv[1]).href === import.meta.url;
if (isDirectRun) {
  main()
    .then((code) => {
      process.exitCode = code ?? 0;
    })
    .catch((error) => {
      console.error(`\n${error?.name === 'WizardSafetyError' || error?.name === 'WizardComposeError' ? error.message : error}`);
      process.exitCode = 1;
    });
}

export { COLLECTION_IDS, dryPorts, listingDryPorts, listingIdsFor, preview };
