import {afterEach,expect,it,vi} from 'vitest';
import {JSDOM} from 'jsdom';
import {ChessApp} from '../../packages/ui/app.js';
import {mountShell,resetForTests} from '../../packages/ui/boot.js';
import {MockChain} from '../../packages/chain/mock.js';
import {normaliseRules,DEFAULT_RULES} from '../../packages/protocol/rules.js';
import {rulesHash} from '../../packages/protocol/canonical.js';
import {PeerApp} from '../../packages/peer/ui.js';
const A='SP3JNSEXAZP4BDSHV0DN3M8R3P0MY0EEBQQZX743X',B='SP1CVH5EWQPTH2J7CWZ7JBHEJPDHA0G4C4QKXFF6W';
const windows:JSDOM[]=[];
afterEach(()=>{vi.restoreAllMocks();for(const dom of windows.splice(0))dom.window.close();});
function setup(chain=new MockChain()){resetForTests();const dom=new JSDOM('<!doctype html><html><body></body></html>',{url:'https://example.test'});windows.push(dom);Object.assign(globalThis,{document:dom.window.document,localStorage:dom.window.localStorage});mountShell(dom.window.document);const app=new ChessApp({chain,document:dom.window.document,build:{network:'devnet',contract:chain.contractId}});return{app,inner:app as any,chain,doc:dom.window.document};}
async function games(count:number,ranked=false,cooldown=0){const chain=new MockChain({balances:{[A]:100000000000n,[B]:100000000000n}}),rules=normaliseRules({...DEFAULT_RULES,white:A,black:B,ranked,cooldown});for(let i=0;i<count;i++){chain.as(A);await chain.openGame(rulesHash(rules),ranked);if(ranked)for(const [n,mv]of ['f2f3','e7e5','g2g4','d8h4'].entries()){chain.as(n%2?B:A);await chain.submit(i+1,mv);}}return{chain,rules};}
it('exposes initial leaderboard failure retry, shares overlapping walks and clears recovered error',async()=>{const {chain}=await games(1,true),{app,inner,doc}=setup(chain);let resolve!:()=>void;const gate=new Promise<void>(r=>resolve=r);const prepare=vi.spyOn(inner,'ensureManifestPairings').mockImplementation(async()=>gate);const count=vi.spyOn(chain,'getRankedCount').mockRejectedValueOnce(Object.assign(Error('offline'),{code:'CHAIN_UNAVAILABLE'}));await new Promise(r=>setTimeout(r,0));const first=app.loadLeaderboard();await app.loadLeaderboard();expect(prepare).toHaveBeenCalledTimes(1);expect(doc.getElementById('leaderboard-note')!.textContent).toContain('Preparing');resolve();await first;const retry=doc.getElementById('leaderboard-verify') as HTMLButtonElement;expect(retry.classList.contains('hide')).toBe(false);expect(retry.disabled).toBe(false);expect(retry.textContent).toBe('Retry verification');count.mockRestore();await app.loadLeaderboard();expect(doc.getElementById('chain-notice')!.textContent).toContain('recovered');expect(doc.getElementById('leaderboard-note')!.textContent).toContain('1 verified ranked game');});
it('recovers named rules and recomputes replay and seat authorization without refresh',async()=>{const{chain,rules}=await games(1,false,17),{app,inner,doc}=setup(chain);vi.spyOn(inner,'adoptWithManifests').mockResolvedValue(undefined);await app.load(1);expect(inner.rulesConfirmed).toBe(false);vi.restoreAllMocks();inner.ensureManifestPairings=async()=>{inner.candidatesFor=()=>[rules];};await inner.adoptWithManifests();expect(inner.state.rules.white).toBe(A);expect(inner.state.rules.black).toBe(B);expect(inner.state.rules.cooldown).toBe(17);expect(doc.getElementById('players')!.textContent).not.toContain('anyone');expect(inner.replayCache.size).toBe(0);});
it('keeps page and cursor on failed pagination, blocks double clicks, and retries the same range',async()=>{const{chain}=await games(60),{inner,doc}=setup(chain);await inner.loadExplore();const before=doc.getElementById('explore-rows')!.textContent;let reject!:(e:Error)=>void;const gate=new Promise<never>((_,r)=>reject=r);const original=chain.getGame.bind(chain);const read=vi.spyOn(chain,'getGame').mockImplementation(id=>id===35?gate:original(id));const page=inner.pageExplore(-1);await Promise.resolve();expect((doc.getElementById('explore-older') as HTMLButtonElement).disabled).toBe(true);await inner.pageExplore(-1);reject(Object.assign(Error('offline'),{code:'CHAIN_UNAVAILABLE'}));await page;expect(inner.exploreTop).toBe(null);expect(doc.getElementById('explore-rows')!.textContent).toBe(before);expect(doc.getElementById('explore-found')!.textContent).toContain('previous page is unchanged');read.mockRestore();await inner.pageExplore(-1);expect(inner.exploreTop).toBe(35);expect(doc.getElementById('explore-count')!.textContent).toContain('11–35');await inner.reloadExplore();expect(inner.exploreTop).toBe(null);});
it('retains completed ranking replays after interruption but rechecks fresh rows',async()=>{const{chain}=await games(6,true),{app}=setup(chain);const entries=vi.spyOn(chain,'getAllEntries'),rows=vi.spyOn(chain,'getGame'),original=chain.getRankedGame.bind(chain);const ranked=vi.spyOn(chain,'getRankedGame').mockImplementation(async index=>{if(index===4){await new Promise(r=>setTimeout(r,40));throw Error('interrupted');}return original(index);});await app.loadLeaderboard();const done=entries.mock.calls.filter(c=>c[0]===1).length;expect(done).toBe(1);ranked.mockRestore();await app.loadLeaderboard();expect(entries.mock.calls.filter(c=>c[0]===1).length).toBe(1);expect(rows.mock.calls.filter(c=>c[0]===1).length).toBe(2);});
it('awaits the same in-flight manifest read for all consumers',async()=>{const{inner}=setup();let release!:()=>void;const gate=new Promise<void>(r=>release=r);inner.readManifestPairings=vi.fn(()=>gate);let finished=0;const a=inner.ensureManifestPairings().then(()=>finished++),b=inner.ensureManifestPairings().then(()=>finished++);await Promise.resolve();expect(finished).toBe(0);expect(inner.readManifestPairings).toHaveBeenCalledTimes(1);release();await Promise.all([a,b]);expect(finished).toBe(2);});
it('refreshes completed tournament freshness and persisted picker state on every scored draw',()=>{const{inner,doc}=setup();inner.tournament={ok:true,scored:true,tournamentId:2993,tournament:{name:'Test',games:[],entrants:[]},rounds:[{number:1,games:[{id:1,white:'A',black:'B',result:'0-1',moves:4,verdict:'verified'}]}],table:[],lineage:[],provenance:null,says:'',problems:[]};inner.tournamentReadAt=Date.now();inner.drawTournament();expect(doc.getElementById('tournament-fresh')!.textContent).toContain('Every game has finished');expect(inner.tournamentState(2993)).toBe('finished');inner.tournament.scored=false;inner.drawTournament();expect(doc.getElementById('tournament-fresh')!.textContent).toBe('');});
it('provides mainnet registry without carrying the default into testnet and explains both play modes',()=>{const{doc,inner}=setup();const peer=new PeerApp(doc);const registry=doc.querySelector('[data-p=registry]') as HTMLInputElement,network=doc.querySelector('[data-p=network]') as HTMLSelectElement;expect(registry.value).toBe('SPARQA0T0GWJZADHRMGNVTJ51D014V8P7XPDSTNH.xchess-peer-v1');network.value='testnet';network.dispatchEvent(new doc.defaultView!.Event('change'));expect(registry.value).toBe('');network.value='mainnet';network.dispatchEvent(new doc.defaultView!.Event('change'));expect(registry.value).toContain('SPAR');inner.drawHelp();expect(doc.getElementById('help-body')!.textContent).toContain('off-chain moves');expect(doc.getElementById('help-body')!.textContent).toContain('legacy play');peer.destroy();});
it('invalidates a retained ranking replay when the fresh chain row changes',async()=>{const{chain}=await games(1,true),{app}=setup(chain);const entries=vi.spyOn(chain,'getAllEntries');await app.loadLeaderboard();chain.as(A);await chain.submit(1,'a2a3');await app.loadLeaderboard();expect(entries).toHaveBeenCalledTimes(2);});
it('does not publish a partial leaderboard when a ranked row or its history is missing',async()=>{const{chain}=await games(1,true),{app,inner,doc}=setup(chain);await app.loadLeaderboard();const before=doc.getElementById('leaderboard-rows')!.textContent;inner.rankedReplays.clear();const entries=vi.spyOn(chain,'getAllEntries').mockResolvedValue([]);await app.loadLeaderboard();expect(doc.getElementById('leaderboard-note')!.textContent).toContain('Verification stopped');expect(doc.getElementById('leaderboard-rows')!.textContent).toBe(before);entries.mockRestore();vi.spyOn(chain,'getGame').mockResolvedValue(null);await app.loadLeaderboard();expect(doc.getElementById('leaderboard-note')!.textContent).toContain('Verification stopped');expect(doc.getElementById('leaderboard-rows')!.textContent).toBe(before);});
it('ignores delayed manifest recovery after a different game starts loading',async()=>{const{chain}=await games(1,false,17),{app,inner}=setup(chain);vi.spyOn(inner,'adoptWithManifests').mockResolvedValue(undefined);await app.load(1);vi.restoreAllMocks();let release!:()=>void;inner.ensureManifestPairings=()=>new Promise<void>(r=>release=r);const adopt=vi.spyOn(inner,'adoptRules'),pending=inner.adoptWithManifests();inner.loadRevision++;release();await pending;expect(adopt).not.toHaveBeenCalled();});
