#!/usr/bin/env node
/**
 * build.mjs — derive the two secondary forms of the library from the one source.
 *
 *   piece-sets.iife.js   a classic script that sets window.ChessPieceSets, so
 *                        index.html opens by double-click. An ES module cannot:
 *                        `import` over file:// is blocked by CORS, and a
 *                        preview you have to start a server for is a preview
 *                        nobody looks at.
 *
 *   svg/<set>/<colour>-<piece>.svg
 *                        120 flat files with the theme inlined, for anything
 *                        that wants a URL rather than a module: <img>, CSS
 *                        background, a design tool, an asset pipeline.
 *
 * Both are GENERATED. Edit piece-sets.js and re-run; never edit the output.
 *
 *   node build.mjs
 */

import { readFile, writeFile, mkdir, rm } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));

const lib = await import('./piece-sets.js');
const { SET_IDS, PIECE_KEYS, pieceStandalone } = lib;

/* ---- the classic-script build ---- */

const src = await readFile(join(here, 'piece-sets.js'), 'utf8');

// The default export is the last thing in the file and is the one construct
// with no IIFE equivalent, so it goes and everything after it with it.
const body = src
  .replace(/\nexport default [\s\S]*$/, '\n')
  .replace(/^export (const|function) /gm, '$1 ');

const iife =
  '/* GENERATED by build.mjs from piece-sets.js — do not edit. */\n' +
  ';(function (root) {\n' +
  body +
  '\nroot.ChessPieceSets = { SETS: SETS, SET_IDS: SET_IDS, PIECE_KEYS: PIECE_KEYS,' +
  ' PIECE_NAMES: PIECE_NAMES, KEY_BY_TYPE: KEY_BY_TYPE, pieceSVG: pieceSVG, pieceUse: pieceUse,' +
  ' pieceMarkup: pieceMarkup, spriteDefs: spriteDefs, pieceStandalone: pieceStandalone, setAttrs: setAttrs, symbolId: symbolId, THEMES: THEMES };\n' +
  '})(typeof globalThis !== "undefined" ? globalThis : this);\n';

await writeFile(join(here, 'piece-sets.iife.js'), iife);

// Fail loudly rather than shipping a build that silently lost an export.
const probe = { window: {} };
new Function('globalThis', iife.replace(/^;\(function/, '(function'))(probe.window);
for (const name of ['SETS', 'pieceSVG', 'spriteDefs', 'pieceStandalone']) {
  if (!probe.window.ChessPieceSets?.[name]) throw new Error(`iife build lost export: ${name}`);
}

/* ---- the flat files ---- */

const svgDir = join(here, 'svg');
await rm(svgDir, { recursive: true, force: true });

let count = 0;
for (const setId of SET_IDS) {
  await mkdir(join(svgDir, setId), { recursive: true });
  for (const color of ['white', 'black']) {
    for (const key of PIECE_KEYS) {
      await writeFile(join(svgDir, setId, `${color}-${key}.svg`), pieceStandalone(setId, key, color));
      count++;
    }
  }
}

console.log(`piece-sets.iife.js  (${(iife.length / 1024).toFixed(1)} kB)`);
console.log(`svg/                (${count} files across ${SET_IDS.length} sets)`);
