import { canonicalJson, sha256Hex } from './canonical';
import {
  LEADERBOARD_TEMPLATE,
  type LeaderboardConfiguration,
  type StudioArtifact,
  type StudioProject,
  type XtrataAssetRef
} from './model';

const ascii = (value: string, max: number, field: string) => {
  const trimmed = value.trim();
  if (!trimmed || trimmed.length > max || !/^[\x20-\x7e]+$/.test(trimmed)) {
    throw new Error(`${field} must contain 1-${max} printable ASCII characters.`);
  }
  return trimmed.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
};

const uint = (value: string, field: string) => {
  if (!/^(0|[1-9]\d*)$/.test(value)) {
    throw new Error(`${field} must be a non-negative integer.`);
  }
  return BigInt(value);
};

export const validateLeaderboardConfiguration = (
  configuration: LeaderboardConfiguration,
  asset: XtrataAssetRef
) => {
  ascii(configuration.projectName, 64, 'Project name');
  ascii(configuration.gameId, 32, 'Game id');
  const min = uint(configuration.minScore, 'Minimum score');
  const max = uint(configuration.maxScore, 'Maximum score');
  if (min >= max) throw new Error('Maximum score must be greater than minimum score.');
  if (!/^[0-9a-f]{64}$/.test(asset.contentHash)) {
    throw new Error('The asset reference must contain a 32-byte lowercase hex hash.');
  }
  if (!/^S[PTMN][A-Z0-9]{20,}\.[a-zA-Z][a-zA-Z0-9-_]{0,127}$/.test(asset.coreContractId)) {
    throw new Error('The asset reference has an invalid core contract principal.');
  }
  if (!/^S[PTMN][A-Z0-9]{20,}$/.test(configuration.administrator)) {
    throw new Error('Administrator must be a valid standard principal.');
  }
  if (!Number.isInteger(configuration.topN) || configuration.topN < 3 || configuration.topN > 10) {
    throw new Error('Top N must be between 3 and 10.');
  }
};

export const generateLeaderboardSource = (
  asset: XtrataAssetRef,
  configuration: LeaderboardConfiguration
) => {
  validateLeaderboardConfiguration(configuration, asset);
  const higher = configuration.direction === 'higher';
  const best = configuration.recordMode === 'personal-best';
  const publicSubmission = configuration.submissionPolicy === 'public';
  return `;; Generated by Xtrata Contract Studio
;; Template: ${LEADERBOARD_TEMPLATE.id}/${LEADERBOARD_TEMPLATE.version}
;; Project: ${ascii(configuration.projectName, 64, 'Project name')}
;; Immutable asset: ${asset.coreContractId}#${asset.tokenId}
;; This source is deterministic. Xtrata stores the game; this contract stores scores.

(define-constant ERR-NOT-AUTHORIZED (err u100))
(define-constant ERR-ASSET-NOT-VERIFIED (err u101))
(define-constant ERR-INVALID-ASSET (err u102))
(define-constant ERR-INVALID-SCORE (err u103))
(define-constant ERR-INVALID-ALIAS (err u104))
(define-constant ERR-DUPLICATE (err u105))
(define-constant ERR-NOT-BETTER (err u106))
(define-constant ERR-NOT-QUALIFIED (err u107))
(define-constant ERR-INVALID-RANK (err u108))
(define-constant ERR-PERMANENT-SEASON (err u109))

(define-constant ADMINISTRATOR '${configuration.administrator})
(define-constant XTRATA-CORE '${asset.coreContractId})
(define-constant XTRATA-TOKEN-ID u${asset.tokenId})
(define-constant XTRATA-CONTENT-HASH 0x${asset.contentHash})
(define-constant GAME-ID "${ascii(configuration.gameId, 32, 'Game id')}")
(define-constant MIN-SCORE u${configuration.minScore})
(define-constant MAX-SCORE u${configuration.maxScore})
(define-constant TOP-N u${configuration.topN})

(define-data-var asset-verified bool false)
(define-data-var verified-at uint u0)
(define-data-var current-season uint u1)

(define-map PlayerScores
  { season: uint, player: principal }
  { score: uint, alias: (string-ascii 12), updated-at: uint }
)
(define-map Board
  { season: uint, rank: uint }
  { player: principal, score: uint, alias: (string-ascii 12), updated-at: uint }
)

(define-private (better? (new uint) (old uint))
  ${higher ? '(> new old)' : '(< new old)'})

(define-private (valid-rank? (rank uint))
  (and (>= rank u1) (<= rank TOP-N)))

(define-private (copy-slot (season uint) (from uint) (to uint))
  (match (map-get? Board { season: season, rank: from })
    entry (map-set Board { season: season, rank: to } entry)
    (map-delete Board { season: season, rank: to })))

(define-private (player-at? (season uint) (rank uint) (player principal))
  (match (map-get? Board { season: season, rank: rank })
    entry (is-eq (get player entry) player)
    false))

(define-private (find-player-rank (season uint) (player principal))
  (if (player-at? season u1 player) u1
  (if (player-at? season u2 player) u2
  (if (player-at? season u3 player) u3
  (if (player-at? season u4 player) u4
  (if (player-at? season u5 player) u5
  (if (player-at? season u6 player) u6
  (if (player-at? season u7 player) u7
  (if (player-at? season u8 player) u8
  (if (player-at? season u9 player) u9
  (if (player-at? season u10 player) u10 u0)))))))))))

(define-private (remove-rank (season uint) (rank uint))
  (begin
    (if (<= rank u1) (copy-slot season u2 u1) true)
    (if (<= rank u2) (copy-slot season u3 u2) true)
    (if (<= rank u3) (copy-slot season u4 u3) true)
    (if (<= rank u4) (copy-slot season u5 u4) true)
    (if (<= rank u5) (copy-slot season u6 u5) true)
    (if (<= rank u6) (copy-slot season u7 u6) true)
    (if (<= rank u7) (copy-slot season u8 u7) true)
    (if (<= rank u8) (copy-slot season u9 u8) true)
    (if (<= rank u9) (copy-slot season u10 u9) true)
    (map-delete Board { season: season, rank: u10 })
    true))

(define-private (qualifies? (season uint) (score uint) (rank uint))
  (match (map-get? Board { season: season, rank: rank })
    entry (better? score (get score entry))
    true))

(define-private (find-rank (season uint) (score uint))
  (if (and (<= u1 TOP-N) (qualifies? season score u1)) u1
  (if (and (<= u2 TOP-N) (qualifies? season score u2)) u2
  (if (and (<= u3 TOP-N) (qualifies? season score u3)) u3
  (if (and (<= u4 TOP-N) (qualifies? season score u4)) u4
  (if (and (<= u5 TOP-N) (qualifies? season score u5)) u5
  (if (and (<= u6 TOP-N) (qualifies? season score u6)) u6
  (if (and (<= u7 TOP-N) (qualifies? season score u7)) u7
  (if (and (<= u8 TOP-N) (qualifies? season score u8)) u8
  (if (and (<= u9 TOP-N) (qualifies? season score u9)) u9
  (if (and (<= u10 TOP-N) (qualifies? season score u10)) u10 u0)))))))))))

(define-private (shift-down (season uint) (rank uint))
  (begin
    (if (<= rank u9) (copy-slot season u9 u10) true)
    (if (<= rank u8) (copy-slot season u8 u9) true)
    (if (<= rank u7) (copy-slot season u7 u8) true)
    (if (<= rank u6) (copy-slot season u6 u7) true)
    (if (<= rank u5) (copy-slot season u5 u6) true)
    (if (<= rank u4) (copy-slot season u4 u5) true)
    (if (<= rank u3) (copy-slot season u3 u4) true)
    (if (<= rank u2) (copy-slot season u2 u3) true)
    (if (<= rank u1) (copy-slot season u1 u2) true)
    true))

(define-public (verify-asset)
  (begin
    (let ((meta (unwrap! (contract-call? '${asset.coreContractId} get-inscription-meta XTRATA-TOKEN-ID) ERR-INVALID-ASSET)))
      (asserts! (and (get sealed meta) (is-eq (get final-hash meta) XTRATA-CONTENT-HASH)) ERR-INVALID-ASSET)
      (var-set asset-verified true)
      (var-set verified-at stacks-block-height)
      (print { event: "asset-verified", core: XTRATA-CORE, token-id: XTRATA-TOKEN-ID, content-hash: XTRATA-CONTENT-HASH })
      (ok true))))

(define-public (submit-score (score uint) (alias (string-ascii 12)))
  (begin
    (asserts! (var-get asset-verified) ERR-ASSET-NOT-VERIFIED)
    ${publicSubmission ? 'true' : '(asserts! (is-eq tx-sender ADMINISTRATOR) ERR-NOT-AUTHORIZED)'}
    (asserts! (and (>= score MIN-SCORE) (<= score MAX-SCORE)) ERR-INVALID-SCORE)
    (asserts! (and (>= (len alias) u3) (<= (len alias) u12)) ERR-INVALID-ALIAS)
    (let ((season (var-get current-season))
          (old (map-get? PlayerScores { season: (var-get current-season), player: tx-sender })))
      ${configuration.rejectIdentical ? '(asserts! (not (is-eq old (some { score: score, alias: alias, updated-at: stacks-block-height }))) ERR-DUPLICATE)' : 'true'}
      ${configuration.rejectIdentical ? '(match old entry (asserts! (not (is-eq (get score entry) score)) ERR-DUPLICATE) true)' : 'true'}
      ${best ? '(match old entry (asserts! (better? score (get score entry)) ERR-NOT-BETTER) true)' : 'true'}
      (let ((old-rank (find-player-rank season tx-sender)))
        (if (> old-rank u0) (remove-rank season old-rank) true))
      (let ((rank (find-rank season score)))
        (asserts! (> rank u0) ERR-NOT-QUALIFIED)
        (shift-down season rank)
        (map-set PlayerScores { season: season, player: tx-sender }
          { score: score, alias: alias, updated-at: stacks-block-height })
        (map-set Board { season: season, rank: rank }
          { player: tx-sender, score: score, alias: alias, updated-at: stacks-block-height })
        (print { event: "score-submitted", game-id: GAME-ID, season: season, player: tx-sender, score: score, alias: alias, rank: rank })
        (ok rank)))))

(define-public (start-next-season)
  (begin
    ${configuration.seasons ? '(asserts! (is-eq tx-sender ADMINISTRATOR) ERR-NOT-AUTHORIZED)' : '(asserts! false ERR-PERMANENT-SEASON)'}
    (let ((next (+ (var-get current-season) u1)))
      (var-set current-season next)
      (print { event: "season-started", season: next })
      (ok next))))

(define-read-only (get-asset-reference)
  { core: XTRATA-CORE, token-id: XTRATA-TOKEN-ID, content-hash: XTRATA-CONTENT-HASH,
    verified: (var-get asset-verified), verified-at: (var-get verified-at) })
(define-read-only (get-current-season) (var-get current-season))
(define-read-only (get-player-score (season uint) (player principal))
  (map-get? PlayerScores { season: season, player: player }))
(define-read-only (get-leaderboard-entry (season uint) (rank uint))
  (if (valid-rank? rank) (ok (map-get? Board { season: season, rank: rank })) ERR-INVALID-RANK))
(define-read-only (get-configuration)
  { game-id: GAME-ID, administrator: ADMINISTRATOR, min-score: MIN-SCORE,
    max-score: MAX-SCORE, top-n: TOP-N, higher-is-better: ${higher ? 'true' : 'false'},
    personal-best: ${best ? 'true' : 'false'}, public-submission: ${publicSubmission ? 'true' : 'false'},
    seasons: ${configuration.seasons ? 'true' : 'false'} })
`;
};

const buildClarinetToml = (asset: XtrataAssetRef) => `[project]
name = "xtrata-contract-studio-export"
description = "Generated by Xtrata Contract Studio"
authors = []
telemetry = false
cache_dir = "./.cache"
requirements = []

[contracts.xtrata-studio-leaderboard]
path = "contracts/xtrata-studio-leaderboard.clar"
clarity_version = 3
epoch = "latest"

[repl.analysis]
passes = ["check_checker"]

[repl.remote_data]
enabled = true
api_url = "${asset.network === 'mainnet' ? 'https://api.hiro.so' : 'https://api.testnet.hiro.so'}"
`;

const buildGeneratedTest = (configuration: LeaderboardConfiguration) => `import { Cl } from '@stacks/transactions';
import { describe, expect, it } from 'vitest';

const accounts = simnet.getAccounts();
const deployer = accounts.get('deployer')!;
const wallet1 = accounts.get('wallet_1')!;
const wallet2 = accounts.get('wallet_2')!;
const contract = \`\${deployer}.xtrata-studio-leaderboard\`;

describe('generated Xtrata leaderboard', () => {
  it('rejects scores until the pinned asset has been verified', () => {
    expect(simnet.callPublicFn(contract, 'submit-score',
      [Cl.uint(100), Cl.stringAscii('ACE')], wallet1).result).toBeErr(Cl.uint(101));
  });
  it('verifies the pinned remote asset and covers score failure paths', () => {
    expect(simnet.callPublicFn(contract, 'verify-asset', [], wallet1).result).toBeOk(Cl.bool(true));
    expect(simnet.callPublicFn(contract, 'submit-score',
      [Cl.uint(${configuration.minScore}), Cl.stringAscii('ACE')], wallet1).result).toBeOk(Cl.uint(1));
    expect(simnet.callPublicFn(contract, 'submit-score',
      [Cl.uint(${configuration.minScore}), Cl.stringAscii('ACE')], wallet1).result).toBeErr(Cl.uint(105));
    expect(simnet.callPublicFn(contract, 'submit-score',
      [Cl.uint(${BigInt(configuration.maxScore) + 1n}), Cl.stringAscii('MAX')], wallet2).result).toBeErr(Cl.uint(103));
  });
  it('tests reset permission', () => {
    expect(simnet.callPublicFn(contract, 'start-next-season', [], wallet1).result).toBeErr(Cl.uint(${configuration.seasons ? '100' : '109'}));
    ${configuration.seasons ? `expect(simnet.callPublicFn(contract, 'start-next-season', [], deployer).result).toBeOk(Cl.uint(2));` : ''}
  });
});
`;

const packageJson = `{
  "name": "xtrata-contract-studio-export",
  "private": true,
  "type": "module",
  "scripts": { "check": "clarinet check", "test": "vitest run" },
  "devDependencies": {
    "@stacks/clarinet-sdk": "^3.9.0",
    "@stacks/transactions": "^7.2.0",
    "vitest": "^4.0.7",
    "vitest-environment-clarinet": "^3.0.2"
  }
}
`;

const vitestConfig = `import { defineConfig } from 'vitest/config';
import { getClarinetVitestsArgv, vitestSetupFilePath } from '@stacks/clarinet-sdk/vitest';
export default defineConfig({
  test: {
    include: ['tests/**/*.test.ts'],
    environment: 'clarinet',
    pool: 'forks',
    isolate: false,
    maxWorkers: 1,
    setupFiles: [vitestSetupFilePath],
    environmentOptions: { clarinet: { ...getClarinetVitestsArgv() } }
  }
});
`;

export const generateLeaderboardProject = async (
  asset: XtrataAssetRef,
  configuration: LeaderboardConfiguration
): Promise<StudioProject> => {
  const source = generateLeaderboardSource(asset, configuration);
  const configurationHash = await sha256Hex(canonicalJson(configuration));
  const sourceHash = await sha256Hex(source);
  const manifest = {
    manifestVersion: '1',
    projectName: configuration.projectName,
    network: asset.network,
    xtrataAssets: [asset],
    template: LEADERBOARD_TEMPLATE,
    modules: ['xtrata-asset-ref/1', 'leaderboard-core/1', 'submission-policy/1', 'season-reset/1', 'events/1'],
    configuration,
    roles: { deployer: '', administrator: configuration.administrator, treasury: '' },
    upgradeModel: 'immutable',
    generatedArtifacts: { contractSourceHash: sourceHash, configurationHash },
    deployment: { contractPrincipal: '', transactionId: '', blockHeight: null },
    customised: false
  };
  const artifacts: StudioArtifact[] = [
    { path: 'Clarinet.toml', content: buildClarinetToml(asset) },
    { path: 'package.json', content: packageJson },
    { path: 'vitest.config.ts', content: vitestConfig },
    { path: 'contracts/xtrata-studio-leaderboard.clar', content: source },
    {
      path: 'tests/xtrata-studio-leaderboard.test.ts',
      content: buildGeneratedTest(configuration)
    },
    { path: 'xtrata-project.json', content: canonicalJson(manifest) },
    {
      path: 'README.md',
      content: `# ${configuration.projectName}\n\nGenerated from ${LEADERBOARD_TEMPLATE.id}/${LEADERBOARD_TEMPLATE.version}.\n\nRun \`npm install\` and \`npm test\` after adding the pinned Xtrata core or faithful mock to the Clarinet project. Deploy with a matching-network wallet only.\n`
    },
    {
      path: 'SECURITY.md',
      content: `# Security report\n\nRisk: Tier 1 (no asset transfers).\n\nPinned dependency: ${asset.coreContractId}#${asset.tokenId} / ${asset.contentHash}.\n\nPrivileged role: ${configuration.administrator} may ${configuration.seasons ? 'start seasons' : 'not reset the permanent season'}${configuration.submissionPolicy === 'administrator' ? ' and submit scores' : ''}.\n\nTrust assumptions: public scores are wallet-authenticated, not proof that a game result was honestly earned. The template is tested, not audited.\n`
    },
    {
      path: 'src/client.ts',
      content: `import { PostConditionMode, stringAsciiCV, uintCV } from '@stacks/transactions';
export const buildSubmitScore = (score: bigint, alias: string) => ({
  functionName: 'submit-score',
  functionArgs: [uintCV(score), stringAsciiCV(alias)],
  postConditionMode: PostConditionMode.Deny,
  postConditions: []
});
export const READ_ONLY_FUNCTIONS = ['get-asset-reference', 'get-current-season', 'get-player-score', 'get-leaderboard-entry', 'get-configuration'] as const;
`
    },
    {
      path: 'contract-interface.json',
      content: canonicalJson({
        public: [
          { name: 'verify-asset', args: [] },
          { name: 'submit-score', args: ['uint', 'string-ascii 12'] },
          { name: 'start-next-season', args: [] }
        ],
        readOnly: [
          'get-asset-reference',
          'get-current-season',
          'get-player-score',
          'get-leaderboard-entry',
          'get-configuration'
        ]
      })
    }
  ];
  return { source, sourceHash, configurationHash, manifest, artifacts };
};
