import {Cl,cvToJSON,deserializeCV,serializeCV,makeUnsignedContractCall,makeUnsignedSTXTokenTransfer,PostConditionMode,AnchorMode,makeStandardSTXPostCondition,FungibleConditionCode,validateStacksAddress,deserializeTransaction,addressToString,addressFromVersionHash,AddressVersion} from '@stacks/transactions';
import {StacksMainnet} from '@stacks/network';
import {RADIO_PLAYS_SHA256,inspectRadioPlaysConfig,RADIO_PLAYS_CORES} from '../lib/deploy/radio-plays';
import {CONTRACT,type Entry} from './model';
const [deployer,name]=CONTRACT.split('.');
export const hex=(v:Uint8Array)=>Array.from(v,b=>b.toString(16).padStart(2,'0')).join('');
export function bytes(v:string){if(!/^(?:[a-f0-9]{2})+$/i.test(v))throw Error('Invalid encoded data.');return Uint8Array.from(v.match(/../g)!,b=>parseInt(b,16));}
export async function hash(v:string){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v))));}
export async function api(path:string,init:RequestInit={}){const r=await fetch('/hiro/mainnet'+path,{...init,cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error(`Blockchain service HTTP ${r.status}; no automatic retry payment was made.`);return r.json();}
export async function read(fn:string,args:any[]=[]){const r=await api(`/v2/contracts/call-read/${deployer}/${name}/${fn}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sender:deployer,arguments:args.map(a=>'0x'+hex(serializeCV(a)))})});if(!r.okay||!r.result)throw Error('Contract read unavailable.');return cvToJSON(deserializeCV(r.result));}
export async function verify(){const s=await api(`/v2/contracts/source/${deployer}/${name}?proof=0`);if(typeof s.source!=='string'||await hash(s.source)!==RADIO_PLAYS_SHA256)throw Error('Deployed source does not match the tested helper.');if(inspectRadioPlaysConfig(await read('get-config')).length)throw Error('Paid-play contract configuration mismatch.');}
export function addressOK(address:string){return address.startsWith('SP')&&validateStacksAddress(address)&&!address.includes('.');}
export async function account(address:string){if(!addressOK(address))throw Error('Invalid mainnet wallet address.');const a=await api(`/v2/accounts/${address}?proof=0`);if(!/^0x[0-9a-f]+$/i.test(a.balance)||!Number.isSafeInteger(a.nonce)||a.nonce<0)throw Error('Malformed account data.');const n=await api(`/extended/v1/address/${address}/nonces`);if(!Number.isSafeInteger(n.possible_next_nonce)||n.possible_next_nonce!==a.nonce||(n.detected_missing_nonces?.length)||(n.last_mempool_tx_nonce!==null&&n.last_mempool_tx_nonce!==undefined&&n.last_mempool_tx_nonce>=a.nonce))throw Error('This wallet has an unresolved transaction or nonce gap. Reconcile first.');return {balance:BigInt(a.balance),nonce:BigInt(a.nonce)};}
export async function balance(address:string){const a=await api(`/v2/accounts/${address}?proof=0`);return BigInt(a.balance);}
export async function owner(core:number,id:number){const d=await read('get-owner',[Cl.uint(core),Cl.uint(id)]);const address=d?.success===true?d.value?.value?.value:null;if(typeof address!=='string'||!addressOK(address))throw Error('Master missing or held by an unsupported escrow contract.');return address;}
export function playOptions(address:string,publicKey:string,core:number,id:number,receipt:string,fee:bigint,nonce:bigint){if(![1,2,3].includes(core)||!Number.isSafeInteger(id)||id<0||!/^[0-9a-f]{32}$/.test(receipt))throw Error('Invalid play request.');return {contractAddress:deployer,contractName:name,functionName:'play',functionArgs:[Cl.uint(core),Cl.uint(id),Cl.buffer(bytes(receipt))],publicKey,fee,nonce,network:new StacksMainnet(),anchorMode:AnchorMode.Any,postConditionMode:PostConditionMode.Deny,postConditions:[makeStandardSTXPostCondition(address,FungibleConditionCode.Equal,50n)]};}
export async function preview(address:string,publicKey:string,core:number,id:number,receipt:string,fee:bigint){await verify();const a=await account(address),recipient=await owner(core,id);if(recipient===address)throw Error('Your test wallet holds this master; self-payment is not supported.');const tx=await makeUnsignedContractCall(playOptions(address,publicKey,core,id,receipt,fee,a.nonce));return {recipient,nonce:a.nonce.toString(),balance:a.balance.toString(),bytes:tx.serialize().length};}
export async function withdrawalPreview(address:string,publicKey:string,recipient:string,amount:bigint,fee:bigint){if(fee<1n||fee>10000n)throw Error('Withdrawal fee outside test limits.');if(!addressOK(recipient)||recipient===address||amount<=0n)throw Error('Choose a different standard mainnet recipient and positive amount.');const a=await account(address);if(amount+fee>a.balance)throw Error('Insufficient balance for amount plus fee.');const tx=await makeUnsignedSTXTokenTransfer({recipient,amount,fee,nonce:a.nonce,publicKey,network:new StacksMainnet(),memo:'Radio test withdrawal',anchorMode:AnchorMode.Any});return {nonce:a.nonce.toString(),bytes:tx.serialize().length};}
export async function broadcast(raw:string,expected:string){let response:Response;try{response=await fetch('/hiro/mainnet/v2/transactions',{method:'POST',headers:{'content-type':'application/octet-stream'},body:bytes(raw),signal:AbortSignal.timeout(15000)});}catch{throw Error('Submission outcome unknown. Reconcile the saved transaction before doing anything else.');}const body=await response.json();if(response.status===400&&body?.reason==='FeeTooLow'){const e=new Error('Node rejected the fee as too low. No automatic increase. Preview a new test with another fee.');Object.assign(e,{feeRejected:true});throw e;}if(!response.ok||typeof body!=='string'||body.replace(/^0x/,'')!==expected.replace(/^0x/,''))throw Error(`Submission unconfirmed (${response.status}). Reconcile or resend the same saved transaction; do not create a replacement.`);return body;}
export async function transaction(txid:string){if(!/^(0x)?[0-9a-f]{64}$/i.test(txid))throw Error('Invalid transaction ID.');const r=await fetch(`/hiro/mainnet/extended/v1/tx/${txid}?unanchored=false`,{cache:'no-store',signal:AbortSignal.timeout(15000)});if(r.status===404)return null;if(!r.ok)throw Error('Transaction lookup unavailable.');return r.json();}
export const coreContract=(core:number)=>deployer+'.'+RADIO_PLAYS_CORES[core-1];

/** Verify a persisted executable envelope before first broadcast or identical resend. */
export function validateSaved(e:Entry){
 if(!e.raw||e.raw.length>16384||!e.txid)throw Error('Missing or oversized signed transaction.');
 const tx=deserializeTransaction(bytes(e.raw)),auth=tx.auth as any,p=tx.payload as any,condition=auth.spendingCondition;
 if(tx.version!==0||tx.chainId!==1||auth.authType!==4||condition.hashMode!==0||addressToString(addressFromVersionHash(AddressVersion.MainnetSingleSig,condition.signer))!==e.address||condition.fee!==BigInt(e.fee)||condition.nonce!==BigInt(e.nonce)||tx.txid()!==e.txid.replace(/^0x/,''))throw Error('Saved transaction does not match its approved terms.');
 tx.verifyOrigin();
 if(e.kind==='play'){
  const pc=tx.postConditions.values[0] as any;
  if(p.payloadType!==2||addressToString(p.contractAddress)+'.'+p.contractName.content!==CONTRACT||p.functionName.content!=='play'||p.functionArgs.length!==3||hex(serializeCV(p.functionArgs[0]))!==hex(serializeCV(Cl.uint(e.core)))||hex(serializeCV(p.functionArgs[1]))!==hex(serializeCV(Cl.uint(e.song)))||hex(serializeCV(p.functionArgs[2]))!==hex(serializeCV(Cl.buffer(bytes(e.id))))||e.amount!=='50'||tx.postConditionMode!==PostConditionMode.Deny||tx.postConditions.values.length!==1||pc.conditionType!==0||pc.amount!==50n||pc.conditionCode!==FungibleConditionCode.Equal||pc.principal.prefix!==2||addressToString(pc.principal.address)!==e.address)throw Error('Saved play protection or master does not match.');
 }else if(p.payloadType!==0||cvToJSON(p.recipient).value!==e.recipient||p.amount!==BigInt(e.amount))throw Error('Saved withdrawal does not match.');
}
