import {generateMnemonic,mnemonicToSeedSync,validateMnemonic} from '@scure/bip39';
import {wordlist} from '@scure/bip39/wordlists/english.js';
import {HDKey} from '@scure/bip32';
import {getAddressFromPrivateKey,TransactionVersion} from '@stacks/transactions';
import {hex,bytes,addressOK} from './chain';
export type Vault={version:1;network:'mainnet';address:string;publicKey:string;salt:string;iv:string;iterations:600000;ciphertext:string};
const enc=new TextEncoder();
export function derive(mnemonic:string){if(!validateMnemonic(mnemonic,wordlist))throw Error('Invalid recovery seed.');const node=HDKey.fromMasterSeed(mnemonicToSeedSync(mnemonic)).derive("m/44'/5757'/0'/0/0");if(!node.privateKey)throw Error('Key derivation failed.');const privateKey=hex(node.privateKey)+'01';return {privateKey,address:getAddressFromPrivateKey(privateKey,TransactionVersion.Mainnet),publicKey:hex(node.publicKey!)};}
async function key(password:string,salt:Uint8Array,usage:KeyUsage[]){if(password.length<12||password.length>1024)throw Error('Use a password of at least 12 characters.');const material=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt:new Uint8Array(salt).buffer,iterations:600000},material,{name:'AES-GCM',length:256},false,usage);}
function aad(v:Pick<Vault,'address'|'publicKey'>){return enc.encode('xtrata-radio-test-wallet:1:mainnet:'+v.address+':'+v.publicKey);}
export function parseVault(value:unknown):Vault{const v=value as Vault;if(!v||v.version!==1||v.network!=='mainnet'||v.iterations!==600000||!addressOK(v.address)||!/^(02|03)[0-9a-f]{64}$/.test(v.publicKey)||!/^[0-9a-f]{32}$/.test(v.salt)||!/^[0-9a-f]{24}$/.test(v.iv)||typeof v.ciphertext!=='string'||v.ciphertext.length>4096||!/^(?:[0-9a-f]{2})+$/.test(v.ciphertext))throw Error('Not a supported encrypted listening-wallet backup.');return v;}
export async function createVault(password:string){const mnemonic=generateMnemonic(wordlist,128);const identity=derive(mnemonic),salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12));const v:Vault={version:1,network:'mainnet',address:identity.address,publicKey:identity.publicKey,salt:hex(salt),iv:hex(iv),iterations:600000,ciphertext:''};v.ciphertext=hex(new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:aad(v)},await key(password,salt,['encrypt']),enc.encode(mnemonic))));return v;}
export async function unlockVault(value:unknown,password:string){const v=parseVault(value);try{const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(v.iv),additionalData:aad(v)},await key(password,bytes(v.salt),['decrypt']),bytes(v.ciphertext));const identity=derive(new TextDecoder().decode(plain));new Uint8Array(plain).fill(0);if(identity.address!==v.address||identity.publicKey!==v.publicKey)throw Error();return identity;}catch{throw Error('Incorrect password or damaged backup. No wallet was changed.');}}
