[project]
name = 'ab3'
description = 'Astro Blaster 3 leaderboard'
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []

[contracts.xtrata-arcade-scores-v2]
path = 'contracts/xtrata-arcade-scores-v2.clar'
clarity_version = 4
epoch = 'latest'
