#!/usr/bin/env node
/**
 * Xtrata Agent One — Opus/WebM audio optimiser (the "opus tool" logic, server-side).
 * ---------------------------------------------------------------------------------
 * Mirrors the Xtrata site's opus-file-generator "Music (High Quality)" profile, byte
 * for byte, so an audio asset is transcoded to the same Opus-in-WebM (.weba) format
 * the browser tool produces — only here it runs automatically, server-side, the
 * instant a job is funded (see core.runJob), BEFORE inscription, so a smaller asset
 * goes on-chain and the deposit's surplus is refunded as change.
 *
 * The exact preset is the tool's `audioProfiles.music_high_quality` (config-state.js):
 *     bitrate 96k · vbr on (1) · compression_level 7 · application audio
 * muxed into a WebM container (getAudioOutputConfig('weba') -> ffmpegFormat 'webm',
 * mime 'audio/webm; codecs=opus'), with the tool's audio-only stream mapping and the
 * same Audional/Xtrata identification metadata tags (ffmpeg-handler.js). Sample rate
 * and channel count are passed through from the source exactly as the tool does
 * (it never forces -ar/-ac), and libopus' default 20 ms frames are used.
 *
 * Design: self-contained, no network, and FAIL-SAFE. Any problem (no ffmpeg, decode
 * error, larger output) returns { ok:false, reason } — it never throws — so the
 * inscription flow simply keeps the original file. This is a pure capability module;
 * the deterministic state machine in core.mjs decides whether to adopt the result.
 *
 * CLI:
 *   node opus-convert.mjs <in> [out.weba]   # one-off convert, prints a JSON result
 *   node opus-convert.mjs --selftest        # offline: synth tone -> encode -> verify
 *
 * Env:
 *   FFMPEG_PATH   explicit ffmpeg binary (checked first)
 *   OPUS_BITRATE  override the preset bitrate in kbps (default 96 — the tool's value)
 */
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { spawn, spawnSync } from 'node:child_process';
import { pathToFileURL } from 'node:url';

/**
 * The hardcoded preset — single source of truth. These values are copied from the
 * opus-file-generator's `audioProfiles.music_high_quality` + `AUDIO_OUTPUT_CONFIG.weba`.
 * Change `bitrate` here (or via OPUS_BITRATE) to retune; everything else matches the tool.
 */
export const OPUS_MUSIC_HQ = Object.freeze({
  name: 'Music (High Quality)',
  profileId: 'music_high_quality',
  codec: 'libopus',
  bitrate: Number(process.env.OPUS_BITRATE || 96), // kbps (VBR target)
  vbr: 1,                 // tool: 'on' -> ffmpeg libopus -vbr 1
  compressionLevel: 7,    // tool: lower compression for better quality preservation
  application: 'audio',   // tool: best for music / general content
  container: 'webm',      // getAudioOutputConfig('weba').ffmpegFormat
  mime: 'audio/webm; codecs=opus',
  ext: 'weba',
});

// The tool's identification/watermark tags (ffmpeg-handler.js). The xtrata_* and
// stream tags are what make the output "Xtrata formatted" web audio downstream.
const GENERATOR_ID = 'AudionalOpusEncoder_v1.0';
function metadataArgs(preset) {
  return [
    '-metadata', `AOE-Generator=${GENERATOR_ID}`,
    '-metadata', `X-AudionalTool-Origin=${GENERATOR_ID}`,
    '-metadata', `comment=Generated by ${GENERATOR_ID}`,
    '-metadata', `xtrata_mime=${preset.mime}`,
    '-metadata', 'xtrata_media_kind=audio',
    '-metadata:s:a:0', 'handler_name=Audio',
    '-metadata:s:a:0', 'media_type=audio',
  ];
}

const AUDIO_MIME_RE = /^audio\//i;
const log = (o) => { try { console.log(JSON.stringify({ mod: 'opus-convert', ...o })); } catch {} };
const binOk = (bin) => { try { return spawnSync(bin, ['-version'], { stdio: 'ignore' }).status === 0; } catch { return false; } };

/** Resolve an ffmpeg binary: FFMPEG_PATH -> system PATH -> bundled ffmpeg-static -> null. */
export async function resolveFfmpeg() {
  const fromEnv = process.env.FFMPEG_PATH;
  if (fromEnv && binOk(fromEnv)) return fromEnv;
  if (binOk('ffmpeg')) return 'ffmpeg';
  try { const m = await import('ffmpeg-static'); const p = m.default || m; if (p && binOk(p)) return p; } catch { /* not installed */ }
  return null;
}

/**
 * Is this an audio asset worth optimising? True for any audio/* that isn't already
 * Opus-in-WebM (re-encoding the target format would only lose quality / add nothing).
 */
export function isConvertibleAudio(mime, filePath = '') {
  if (!mime || !AUDIO_MIME_RE.test(mime)) return false;
  if (/audio\/webm/i.test(mime) && /opus/i.test(mime)) return false;       // already the target
  const ext = (String(filePath).match(/\.([a-z0-9]+)$/i) || [])[1];
  if (ext && ext.toLowerCase() === 'weba') return false;
  return true;
}

/**
 * Transcode any audio file to Opus-in-WebM using the Music (High Quality) preset —
 * the exact ffmpeg command the opus-file-generator runs for .weba output.
 * Returns { ok, path, bytes, mime, codec, container, bitrate, preset, ffmpeg, ms }
 * or { ok:false, reason }. NEVER throws.
 */
export async function convertToOpusWebm(srcPath, opts = {}) {
  const preset = opts.preset || OPUS_MUSIC_HQ;
  try {
    if (!srcPath || !fs.existsSync(srcPath)) return { ok: false, reason: 'source not found' };
    const ff = opts.ffmpeg || await resolveFfmpeg();
    if (!ff) return { ok: false, reason: 'no ffmpeg (set FFMPEG_PATH, install ffmpeg, or `npm i ffmpeg-static`)' };

    const outDir = opts.outDir || path.dirname(srcPath);
    const stem = (path.basename(srcPath).replace(/\.[^.]+$/, '') || 'audio');
    const outPath = opts.outPath || path.join(outDir, `${stem}.opus-hq.${preset.ext}`);

    const args = [
      '-y', '-hide_banner', '-loglevel', 'error',
      '-i', srcPath,
      // audio-only: drop embedded cover art / video / subs / data / chapters
      '-map', '0:a:0', '-map_chapters', '-1', '-vn', '-sn', '-dn',
      ...metadataArgs(preset),
      '-c:a', preset.codec,
      '-b:a', `${preset.bitrate}k`,
      '-vbr', String(preset.vbr),
      '-compression_level', String(preset.compressionLevel),
      '-application', preset.application,
      '-f', preset.container,
      outPath,
    ];

    const t0 = Date.now();
    const code = await new Promise((resolve) => {
      let err = '';
      const c = spawn(ff, args, { stdio: ['ignore', 'ignore', 'pipe'] });
      c.stderr.on('data', (d) => { err = (err + d.toString()).slice(-600); });
      c.on('error', () => resolve(-1));
      c.on('close', (x) => { if (x !== 0) log({ event: 'ffmpeg-error', code: x, err: err.trim() }); resolve(x); });
    });
    if (code !== 0 || !fs.existsSync(outPath)) return { ok: false, reason: `ffmpeg failed (exit ${code})`, ffmpeg: ff };

    const bytes = fs.statSync(outPath).size;
    if (!bytes) { try { fs.unlinkSync(outPath); } catch {} return { ok: false, reason: 'empty output' }; }
    const out = { ok: true, path: outPath, bytes, mime: preset.mime, codec: 'opus', container: 'webm',
      bitrate: `${preset.bitrate}k`, preset: preset.name, ffmpeg: ff, ms: Date.now() - t0 };
    log({ event: 'converted', src: path.basename(srcPath), out: path.basename(outPath), bytes, ms: out.ms });
    return out;
  } catch (e) { return { ok: false, reason: String((e && e.message) || e) }; }
}

// --------------------------- self-test (offline) ---------------------------
async function selftest() {
  const ff = await resolveFfmpeg();
  if (!ff) { console.error('selftest: no ffmpeg available'); process.exit(2); }
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'opus-st-'));
  const wav = path.join(tmp, 'tone.wav');
  // 6 s of 48k stereo PCM — a chunky source that must shrink after Opus encode
  spawnSync(ff, ['-y', '-hide_banner', '-loglevel', 'error', '-f', 'lavfi',
    '-i', 'sine=frequency=440:sample_rate=48000:duration=6', '-ac', '2', wav], { stdio: 'ignore' });
  const inBytes = fs.statSync(wav).size;
  const r = await convertToOpusWebm(wav, { outDir: tmp });
  const pass = !!(r.ok && r.bytes < inBytes && r.mime === 'audio/webm; codecs=opus');
  console.log(JSON.stringify({ selftest: pass ? 'PASS' : 'FAIL', inBytes, outBytes: r.bytes,
    ratio: r.ok ? +(r.bytes / inBytes).toFixed(3) : null, ...r }, null, 2));
  try { fs.rmSync(tmp, { recursive: true, force: true }); } catch {}
  process.exit(pass ? 0 : 1);
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) {
  if (process.argv.includes('--selftest')) selftest();
  else if (process.argv[2]) {
    const src = process.argv[2], out = process.argv[3];
    convertToOpusWebm(src, out ? { outPath: out } : {}).then((r) => { console.log(JSON.stringify(r, null, 2)); process.exit(r.ok ? 0 : 1); });
  } else {
    console.log('usage: node opus-convert.mjs <in> [out.weba]   |   node opus-convert.mjs --selftest');
  }
}
