// suno-build.js — IN-BROWSER Suno→player builder (no backend, no server ffmpeg).
// Mirrors the opus-file-generator: ffmpeg.wasm transcodes the MP3 to Opus/WebM
// (Music HQ: libopus 96k VBR, compression 7, application audio + the Audional/Xtrata
// identification tags), extracts title/artist/album/lyrics + cover art, base64s both,
// and builds the self-contained player via window.buildXtrataAudioPlayerHtml
// (HTML_Template.js). Returns a player File so the wizard can quote on its EXACT size.
//
// Requires (loaded before this): @ffmpeg/ffmpeg@0.11 (global FFmpeg) + HTML_Template.js.
(function () {
  const FF = window.FFmpeg;
  let _ff = null, _loading = null;
  async function ff(onStatus) {
    if (_ff) return _ff;
    if (_loading) return _loading;
    _loading = (async () => {
      if (!FF || !FF.createFFmpeg) throw new Error('ffmpeg.wasm not loaded');
      onStatus && onStatus('Loading the audio engine…');
      const f = FF.createFFmpeg({ log: false, corePath: 'https://cdn.jsdelivr.net/npm/@ffmpeg/core@0.11.0/dist/ffmpeg-core.js' });
      await f.load();
      _ff = f; return f;
    })();
    return _loading;
  }

  const fetchFile = (FF && FF.fetchFile) ? FF.fetchFile : async (file) => new Uint8Array(await file.arrayBuffer());
  const slug = (s) => String(s || '').toLowerCase().replace(/\.[^.]+$/, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 48) || 'track';
  function b64(u8) { let s = ''; const CH = 0x8000; for (let i = 0; i < u8.length; i += CH) s += String.fromCharCode.apply(null, u8.subarray(i, i + CH)); return btoa(s); }

  // ffmetadata parser (handles \-escapes + multi-line continuation, e.g. lyrics)
  const ffUnescape = (s) => String(s).replace(/\\(.)/g, (_m, c) => c);
  function parseFfmeta(text) {
    const out = {}; const lines = String(text).split('\n'); let i = 0;
    const endsEscaped = (s) => { let n = 0; for (let j = s.length - 1; j >= 0 && s[j] === '\\'; j--) n++; return n % 2 === 1; };
    while (i < lines.length) {
      let line = lines[i++];
      if (!line || line[0] === ';' || line[0] === '#') continue;
      while (endsEscaped(line) && i < lines.length) line = line.slice(0, -1) + '\n' + lines[i++];
      let eq = -1;
      for (let j = 0; j < line.length; j++) if (line[j] === '=') { let n = 0, k = j - 1; while (k >= 0 && line[k] === '\\') { n++; k--; } if (n % 2 === 0) { eq = j; break; } }
      if (eq <= 0) continue;
      const key = line.slice(0, eq).trim().toLowerCase();
      if (!(key in out)) out[key] = ffUnescape(line.slice(eq + 1));
    }
    return out;
  }

  // The opus tool's Music (High Quality) → .weba command (+ Audional/Xtrata tags).
  const OPUS_ARGS = (inName) => [
    '-i', inName, '-map', '0:a:0', '-map_chapters', '-1', '-vn', '-sn', '-dn',
    '-metadata', 'AOE-Generator=AudionalOpusEncoder_v1.0',
    '-metadata', 'X-AudionalTool-Origin=AudionalOpusEncoder_v1.0',
    '-metadata', 'comment=Generated by AudionalOpusEncoder_v1.0',
    '-metadata', 'xtrata_mime=audio/webm; codecs=opus',
    '-metadata', 'xtrata_media_kind=audio',
    '-metadata:s:a:0', 'handler_name=Audio', '-metadata:s:a:0', 'media_type=audio',
    '-c:a', 'libopus', '-b:a', '96k', '-vbr', '1', '-compression_level', '7', '-application', 'audio',
    '-f', 'webm', 'out.weba',
  ];

  // Build a self-contained player File from an audio File. onStatus(msg) for UI.
  async function build(file, onStatus) {
    if (!window.buildXtrataAudioPlayerHtml) throw new Error('player template not loaded (HTML_Template.js)');
    const f = await ff(onStatus);
    const inName = 'in-' + Date.now() + '.' + ((file.name.match(/\.([a-z0-9]+)$/i) || [])[1] || 'mp3');
    f.FS('writeFile', inName, await fetchFile(file));
    const cleanup = (n) => { try { f.FS('unlink', n); } catch (_e) {} };
    try {
      onStatus && onStatus('Optimising to Opus (Music HQ)…');
      await f.run(...OPUS_ARGS(inName));
      const weba = f.FS('readFile', 'out.weba');

      onStatus && onStatus('Reading title, artist & lyrics…');
      let meta = {};
      try { await f.run('-i', inName, '-f', 'ffmetadata', 'meta.txt'); meta = parseFfmeta(new TextDecoder().decode(f.FS('readFile', 'meta.txt'))); } catch (_e) {}

      onStatus && onStatus('Extracting cover art…');
      let coverB64 = null, coverMime = null;
      try { await f.run('-i', inName, '-an', '-map', '0:v:0', '-frames:v', '1', '-c:v', 'mjpeg', 'cover.jpg'); const cb = f.FS('readFile', 'cover.jpg'); if (cb && cb.length) { coverB64 = b64(cb); coverMime = 'image/jpeg'; } } catch (_e) {}

      const title = (meta.title || '').trim() || (file.name || 'Untitled').replace(/\.[^.]+$/, '');
      const artist = (meta.artist || '').trim();
      const album = (meta.album || '').trim();
      const lyricsKey = Object.keys(meta).find((k) => /^lyrics/.test(k) || k === 'unsyncedlyrics');
      const lyrics = (meta['lyrics-eng'] || meta['lyrics'] || (lyricsKey ? meta[lyricsKey] : '') || '').trim();
      const comment = (meta.comment || '').trim();
      const isSuno = /made with suno/i.test(comment + ' ' + title + ' ' + artist) || /\bsuno\b/i.test(comment);

      onStatus && onStatus('Building the player…');
      const html = window.buildXtrataAudioPlayerHtml({
        mode: 'embedded', audioMimeType: 'audio/webm; codecs=opus', audioBase64: b64(weba),
        imageMimeType: coverMime || undefined, imageBase64: coverB64 || undefined, artFit: 'cover',
        metadata: { assetType: 'song', title, artist, album, lyrics },
      });
      const playerFile = new File([html], slug(file.name) + '.player.html', { type: 'text/html' });
      return { playerFile, title, artist, album, hasCover: !!coverB64, hasLyrics: !!lyrics, isSuno, opusBytes: weba.length, playerBytes: playerFile.size, sourceBytes: file.size };
    } finally {
      ['out.weba', 'meta.txt', 'cover.jpg', inName].forEach(cleanup);
    }
  }

  window.XtrataSuno = { build };
})();
