;; Generated by Xtrata Contract Studio
;; Template: xtrata-leaderboard/1.0.0
;; Project: Xtrata Game Leaderboard
;; Immutable asset: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.mock-xtrata-studio-core#42
;; This source is deterministic. Xtrata stores the game; this contract stores scores.

(define-constant ERR-NOT-AUTHORIZED (err u100))
(define-constant ERR-ASSET-NOT-VERIFIED (err u101))
(define-constant ERR-INVALID-ASSET (err u102))
(define-constant ERR-INVALID-SCORE (err u103))
(define-constant ERR-INVALID-ALIAS (err u104))
(define-constant ERR-DUPLICATE (err u105))
(define-constant ERR-NOT-BETTER (err u106))
(define-constant ERR-NOT-QUALIFIED (err u107))
(define-constant ERR-INVALID-RANK (err u108))
(define-constant ERR-PERMANENT-SEASON (err u109))

(define-constant ADMINISTRATOR 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM)
(define-constant XTRATA-CORE 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.mock-xtrata-studio-core)
(define-constant XTRATA-TOKEN-ID u42)
(define-constant XTRATA-CONTENT-HASH 0xabababababababababababababababababababababababababababababababab)
(define-constant GAME-ID "xtrata-game")
(define-constant MIN-SCORE u10)
(define-constant MAX-SCORE u1000)
(define-constant TOP-N u5)

(define-data-var asset-verified bool false)
(define-data-var verified-at uint u0)
(define-data-var current-season uint u1)

(define-map PlayerScores
  { season: uint, player: principal }
  { score: uint, alias: (string-ascii 12), updated-at: uint }
)
(define-map Board
  { season: uint, rank: uint }
  { player: principal, score: uint, alias: (string-ascii 12), updated-at: uint }
)

(define-private (better? (new uint) (old uint))
  (> new old))

(define-private (valid-rank? (rank uint))
  (and (>= rank u1) (<= rank TOP-N)))

(define-private (copy-slot (season uint) (from uint) (to uint))
  (match (map-get? Board { season: season, rank: from })
    entry (map-set Board { season: season, rank: to } entry)
    (map-delete Board { season: season, rank: to })))

(define-private (player-at? (season uint) (rank uint) (player principal))
  (match (map-get? Board { season: season, rank: rank })
    entry (is-eq (get player entry) player)
    false))

(define-private (find-player-rank (season uint) (player principal))
  (if (player-at? season u1 player) u1
  (if (player-at? season u2 player) u2
  (if (player-at? season u3 player) u3
  (if (player-at? season u4 player) u4
  (if (player-at? season u5 player) u5
  (if (player-at? season u6 player) u6
  (if (player-at? season u7 player) u7
  (if (player-at? season u8 player) u8
  (if (player-at? season u9 player) u9
  (if (player-at? season u10 player) u10 u0)))))))))))

(define-private (remove-rank (season uint) (rank uint))
  (begin
    (if (<= rank u1) (copy-slot season u2 u1) true)
    (if (<= rank u2) (copy-slot season u3 u2) true)
    (if (<= rank u3) (copy-slot season u4 u3) true)
    (if (<= rank u4) (copy-slot season u5 u4) true)
    (if (<= rank u5) (copy-slot season u6 u5) true)
    (if (<= rank u6) (copy-slot season u7 u6) true)
    (if (<= rank u7) (copy-slot season u8 u7) true)
    (if (<= rank u8) (copy-slot season u9 u8) true)
    (if (<= rank u9) (copy-slot season u10 u9) true)
    (map-delete Board { season: season, rank: u10 })
    true))

(define-private (qualifies? (season uint) (score uint) (rank uint))
  (match (map-get? Board { season: season, rank: rank })
    entry (better? score (get score entry))
    true))

(define-private (find-rank (season uint) (score uint))
  (if (and (<= u1 TOP-N) (qualifies? season score u1)) u1
  (if (and (<= u2 TOP-N) (qualifies? season score u2)) u2
  (if (and (<= u3 TOP-N) (qualifies? season score u3)) u3
  (if (and (<= u4 TOP-N) (qualifies? season score u4)) u4
  (if (and (<= u5 TOP-N) (qualifies? season score u5)) u5
  (if (and (<= u6 TOP-N) (qualifies? season score u6)) u6
  (if (and (<= u7 TOP-N) (qualifies? season score u7)) u7
  (if (and (<= u8 TOP-N) (qualifies? season score u8)) u8
  (if (and (<= u9 TOP-N) (qualifies? season score u9)) u9
  (if (and (<= u10 TOP-N) (qualifies? season score u10)) u10 u0)))))))))))

(define-private (shift-down (season uint) (rank uint))
  (begin
    (if (<= rank u9) (copy-slot season u9 u10) true)
    (if (<= rank u8) (copy-slot season u8 u9) true)
    (if (<= rank u7) (copy-slot season u7 u8) true)
    (if (<= rank u6) (copy-slot season u6 u7) true)
    (if (<= rank u5) (copy-slot season u5 u6) true)
    (if (<= rank u4) (copy-slot season u4 u5) true)
    (if (<= rank u3) (copy-slot season u3 u4) true)
    (if (<= rank u2) (copy-slot season u2 u3) true)
    (if (<= rank u1) (copy-slot season u1 u2) true)
    true))

(define-public (verify-asset)
  (begin
    (let ((meta (unwrap! (contract-call? 'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.mock-xtrata-studio-core get-inscription-meta XTRATA-TOKEN-ID) ERR-INVALID-ASSET)))
      (asserts! (and (get sealed meta) (is-eq (get final-hash meta) XTRATA-CONTENT-HASH)) ERR-INVALID-ASSET)
      (var-set asset-verified true)
      (var-set verified-at stacks-block-height)
      (print { event: "asset-verified", core: XTRATA-CORE, token-id: XTRATA-TOKEN-ID, content-hash: XTRATA-CONTENT-HASH })
      (ok true))))

(define-public (submit-score (score uint) (alias (string-ascii 12)))
  (begin
    (asserts! (var-get asset-verified) ERR-ASSET-NOT-VERIFIED)
    true
    (asserts! (and (>= score MIN-SCORE) (<= score MAX-SCORE)) ERR-INVALID-SCORE)
    (asserts! (and (>= (len alias) u3) (<= (len alias) u12)) ERR-INVALID-ALIAS)
    (let ((season (var-get current-season))
          (old (map-get? PlayerScores { season: (var-get current-season), player: tx-sender })))
      (asserts! (not (is-eq old (some { score: score, alias: alias, updated-at: stacks-block-height }))) ERR-DUPLICATE)
      (match old entry (asserts! (not (is-eq (get score entry) score)) ERR-DUPLICATE) true)
      (match old entry (asserts! (better? score (get score entry)) ERR-NOT-BETTER) true)
      (let ((old-rank (find-player-rank season tx-sender)))
        (if (> old-rank u0) (remove-rank season old-rank) true))
      (let ((rank (find-rank season score)))
        (asserts! (> rank u0) ERR-NOT-QUALIFIED)
        (shift-down season rank)
        (map-set PlayerScores { season: season, player: tx-sender }
          { score: score, alias: alias, updated-at: stacks-block-height })
        (map-set Board { season: season, rank: rank }
          { player: tx-sender, score: score, alias: alias, updated-at: stacks-block-height })
        (print { event: "score-submitted", game-id: GAME-ID, season: season, player: tx-sender, score: score, alias: alias, rank: rank })
        (ok rank)))))

(define-public (start-next-season)
  (begin
    (asserts! (is-eq tx-sender ADMINISTRATOR) ERR-NOT-AUTHORIZED)
    (let ((next (+ (var-get current-season) u1)))
      (var-set current-season next)
      (print { event: "season-started", season: next })
      (ok next))))

(define-read-only (get-asset-reference)
  { core: XTRATA-CORE, token-id: XTRATA-TOKEN-ID, content-hash: XTRATA-CONTENT-HASH,
    verified: (var-get asset-verified), verified-at: (var-get verified-at) })
(define-read-only (get-current-season) (var-get current-season))
(define-read-only (get-player-score (season uint) (player principal))
  (map-get? PlayerScores { season: season, player: player }))
(define-read-only (get-leaderboard-entry (season uint) (rank uint))
  (if (valid-rank? rank) (ok (map-get? Board { season: season, rank: rank })) ERR-INVALID-RANK))
(define-read-only (get-configuration)
  { game-id: GAME-ID, administrator: ADMINISTRATOR, min-score: MIN-SCORE,
    max-score: MAX-SCORE, top-n: TOP-N, higher-is-better: true,
    personal-best: true, public-submission: true,
    seasons: true })
