[project]
name = "probe"
requirements = []
[contracts.mock-pepe]
path = "contracts/mock-pepe.clar"
clarity_version = 4
epoch = "latest"
[contracts.probe]
path = "contracts/probe.clar"
clarity_version = 4
epoch = "latest"
