import {Store} from '../src/peer/storage';import {Peer} from '../src/peer/transport';
import {hash,sign,actionFor,FORMAT,RULES,canonical,completed,parseArchive,insist,type Archive} from '../src/peer/protocol';
const results:{name:string;passed:boolean;error?:string}[]=[];
const check=(v:unknown,m='Assertion failed')=>{if(!v)throw Error(m);};
const wait=async(fn:()=>boolean,timeout=12000)=>{const start=Date.now();while(!fn()){if(Date.now()-start>timeout)throw Error('Timed out');await new Promise(r=>setTimeout(r,50));}};
const test=async(name:string,fn:()=>Promise<void>|void)=>{try{await fn();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:(e as Error).message});}document.getElementById('results')!.textContent=JSON.stringify(results,null,2);};
async function main(){
 const accounts=await(await fetch('/accounts')).json(),store=new Store();let k:any;
 await test('IndexedDB retains a non-exportable signing key across Store instances',async()=>{k=await store.key();const secret=await new Store().get('keys',k.public);check(secret&&secret.extractable===false);});
 await test('Web Locks serialize competing browser writers',async()=>{const order:number[]=[];await Promise.all([store.lock('test',async()=>{order.push(1);await new Promise(r=>setTimeout(r,40));order.push(2);}),store.lock('test',async()=>{order.push(3);})]);check(order.join()==='1,2,3');});
 let left:Peer|undefined,right:Peer|undefined;
 await test('real WebRTC offer/answer connects without STUN or signaling service locally',async()=>{let a=false,b=false;left=new Peer([],()=>{},()=>{},()=>{a=true;});right=new Peer([],()=>{},()=>{},()=>{b=true;});const offer=await left.offer(),answer=await right.answer(offer!);await left.finish(answer!);await wait(()=>a&&b);check(left.channel?.ordered===true);});
 left?.close();right?.close();
 await test('real WebRTC transports a chunked record larger than a single message',async()=>{let got='',a=false,b=false;left=new Peer([],()=>{},()=>{},()=>{a=true;});right=new Peer([],text=>{got=text;},()=>{},()=>{b=true;});await left.finish((await right.answer((await left.offer())!))!);await wait(()=>a&&b);const text='0123456789'.repeat(30000);await left.send(text);await wait(()=>got.length===text.length);check(got===text);});
 left?.close();right?.close();
 const frames:HTMLIFrameElement[]=[];
 for(let i=0;i<2;i++){const f=document.createElement('iframe');f.src='/ui?side='+i;f.style.cssText='width:48%;height:850px';document.getElementById('frames')!.append(f);frames.push(f);await wait(()=>!!f.contentDocument?.getElementById('registry') && !!(f.contentWindow as any).XChessWallet);}
 const d=(i:number)=>frames[i].contentDocument!,v=(i:number,id:string)=>(d(i).getElementById(id) as HTMLInputElement),click=(i:number,id:string)=>v(i,id).click();
 const status=(i:number)=>v(i,'status').textContent??'';
 const ready=async(i:number,pattern:RegExp)=>wait(()=>pattern.test(status(i)));
 for(let i=0;i<2;i++){v(i,'api').value=location.origin+'/api';v(i,'confirmations').value='0';click(i,'wallet');await ready(i,/Wallet connected/);}
  await test('peer UI starts with 64 squares and a dark a1',()=>{check(d(0).querySelectorAll('[data-square]').length===64);check(d(0).querySelector('[data-square="a1"]')?.classList.contains('dark'));});
 await test('peer board has one tab stop and keyboard navigation',()=>{const cells=d(0).querySelectorAll<HTMLButtonElement>('[data-square]');check([...cells].filter(b=>b.tabIndex===0).length===1);cells[0].focus();cells[0].dispatchEvent(new (frames[0].contentWindow as any).KeyboardEvent('keydown',{key:'End',bubbles:true}));check((d(0).activeElement as HTMLElement).dataset.square==='h8');});
 await test('UI creates and joins a game through real Clarity calls in simnet',async()=>{v(0,'opponent').value=accounts[1];click(0,'create');await ready(0,/Submitted create-game/);v(1,'game').value='1';click(1,'join');await ready(1,/Submitted join-game/);for(let i=0;i<2;i++){v(i,'game').value='1';click(i,'load');await ready(i,/Game loaded/);}});
 await test('UI copies manual invitation/answer and establishes a peer connection',async()=>{click(0,'invite');await ready(0,/Connection message ready/);v(1,'signal-in').value=v(0,'signal-out').value;click(1,'answer');await ready(1,/Connection message ready/);v(0,'signal-in').value=v(1,'signal-out').value;click(0,'finish');await wait(()=>[0,1].every(i=>/connected/i.test(v(i,'connection').textContent??'')&&!/disconnected/i.test(v(i,'connection').textContent??'')));});
 async function move(i:number,from:string,to:string){(d(i).querySelector(`[data-square="${from}"]`) as HTMLButtonElement).click();await new Promise(r=>setTimeout(r,60));(d(i).querySelector(`[data-square="${to}"]`) as HTMLButtonElement).click();}
 await test('automatically signed moves reach the other browser and update its board',async()=>{await move(0,'f2','f3');await wait(()=>/1 signed actions/.test(v(1,'position').textContent??''));await move(1,'e7','e5');await wait(()=>/2 signed actions/.test(v(0,'position').textContent??''));await move(0,'g2','g4');await wait(()=>/3 signed actions/.test(v(1,'position').textContent??''));});
 await test('winner prepares checkmate after loser disconnects without final signature',async()=>{click(0,'disconnect');await new Promise(r=>setTimeout(r,150));await move(1,'d8','h4');await wait(()=>/checkmate/.test(v(1,'position').textContent??''));click(1,'complete');await ready(1,/Completed record verified/);check(!(v(1,'publication') as any).hidden);const blobs=(frames[1].contentWindow as any).testDownloads;const text=await blobs.at(-1).text();const a=parseArchive(text);check((await completed(a,a.opening)).outcome?.result==='0-1');});
 await test('winner registers inscription reference through simnet without loser approval',async()=>{v(1,'inscription').value='123';click(1,'record');await ready(1,/Submitted record-archive/);});
 await test('signed-file fallback imports completed history into the disconnected peer',async()=>{const text=await (frames[1].contentWindow as any).testDownloads.at(-1).text();const w=frames[0].contentWindow as any;const dt=new w.DataTransfer();dt.items.add(new w.File([text],'record.json',{type:'application/json'}));(v(0,'import') as HTMLInputElement).files=dt.files;v(0,'import').dispatchEvent(new w.Event('change'));await ready(0,/Completed game verified/);check(/checkmate/.test(v(0,'position').textContent??''));});
 await test('reload recovers the registered key and complete history from durable storage',async()=>{frames[1].src='/ui?side=1&reload=1';await wait(()=>!!frames[1].contentDocument?.getElementById('registry') && v(1,'api').value==='http://localhost:3999');v(1,'api').value=location.origin+'/api';v(1,'confirmations').value='0';click(1,'wallet');await ready(1,/Wallet connected/);v(1,'game').value='1';click(1,'load');await ready(1,/Game loaded/);check(/checkmate/.test(v(1,'position').textContent??''));});
 await test('shipped single-file loader opens the new peer view',async()=>{const f=document.createElement('iframe');f.src='/artifact?xchess-view=peer';document.body.append(f);await wait(()=>f.contentDocument?.querySelector('h1')?.textContent==='Peer play');check((f.contentWindow as any).__XCHESS_V3_MODE__==='peer');check(f.contentDocument!.querySelectorAll('[data-square]').length===64);f.remove();});
 await fetch('/report',{method:'POST',body:JSON.stringify({results,passed:results.filter(r=>r.passed).length,failed:results.filter(r=>!r.passed).length,limitations:'Real WebRTC tested locally; simnet and simulated wallets; no remote NAT traversal or public chain broadcast.'},null,2)});
}
main().catch(async e=>{document.getElementById('results')!.textContent+='\nFATAL '+e.message;await fetch('/report',{method:'POST',body:JSON.stringify({results,fatal:e.message})});});
