import assert from 'node:assert/strict';
import {build} from '../../X-Chess_2.0/node_modules/esbuild/lib/main.js';
import {writeFileSync} from 'node:fs';
const bundle=await build({entryPoints:[new URL('../src/peer/protocol.ts',import.meta.url).pathname],bundle:true,write:false,format:'esm',platform:'node'});
const p=await import('data:text/javascript;base64,'+Buffer.from(bundle.outputFiles[0].text).toString('base64'));
const white=await p.generateKey(),black=await p.generateKey(),outsider=await p.generateKey();
const o={protocol:p.FORMAT,rules:p.RULES,network:'devnet',registry:'STC5KHM41H6WHAST7MWWDD807YSPRQKJ68T330BQ.xchess-peer-v1',game:1,white:'STC5KHM41H6WHAST7MWWDD807YSPRQKJ68T330BQ',black:'ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM',whiteKey:white.public,blackKey:black.public,baseMs:180000,incrementMs:2000,joinedHeight:2};
const empty=()=>({format:p.FORMAT,opening:o,events:[]});
const add=async(a,kind,move='')=>{const action=await p.actionFor(a,o,kind,move);return {...a,events:[...a.events,await p.sign(action,action.side==='white'?white:black)]};};
const copy=v=>structuredClone(v),results=[];
const test=async(name,fn)=>{try{await fn();results.push({name,passed:true});console.log('PASS',name);}catch(e){results.push({name,passed:false,error:e.message});console.log('FAIL',name,e.message.slice(0,150));}};
let mate=empty();for(const move of ['f2f3','e7e5','g2g4','d8h4'])mate=await add(mate,'move',move);
await test('winner publishes checkmate without a loser final acknowledgement',async()=>{const s=await p.completed(mate,o);assert.equal(s.outcome.result,'0-1');assert.equal(s.outcome.termination,'checkmate');assert.equal(mate.events.length,4);assert.equal(mate.events[3].action.side,'black');});
await test('every unfinished prefix refuses completed publication',async()=>{for(let n=0;n<4;n++)await assert.rejects(p.completed({...mate,events:mate.events.slice(0,n)},o),/Unfinished/);});
await test('move tampering fails signature verification',async()=>{const a=copy(mate);a.events[0].action.move='f2f4';await assert.rejects(p.replay(a,o),/signature/);});
await test('forged key cannot sign a player move',async()=>{const a=copy(mate);a.events[0]=await p.sign(a.events[0].action,outsider);await assert.rejects(p.replay(a,o),/signature/);});
await test('validly signed illegal move rejected',async()=>{const a=copy(mate);a.events=[await p.sign({...a.events[0].action,move:'e2e5'},white)];await assert.rejects(p.replay(a,o),/Illegal/);});
await test('validly signed false board rejected',async()=>{const a=copy(mate);a.events=[await p.sign({...a.events[0].action,fen:'fake'},white)];await assert.rejects(p.replay(a,o),/board/);});
await test('other game, network, rules, registry and player keys cannot substitute',async()=>{for(const patch of [{game:2},{network:'testnet'},{rules:'other'},{registry:o.registry+'x'},{whiteKey:outsider.public}])await assert.rejects(p.replay(mate,{...o,...patch}));});
await test('upload cannot redefine its own on-chain opening',async()=>{const a=copy(mate);a.opening.whiteKey=outsider.public;await assert.rejects(p.replay(a,o),/opening/);});
await test('reordered and missing moves rejected',async()=>{const a=copy(mate);[a.events[0],a.events[1]]=[a.events[1],a.events[0]];await assert.rejects(p.replay(a,o));await assert.rejects(p.replay({...mate,events:mate.events.slice(1)},o));});
await test('events after a terminal position rejected',async()=>{await assert.rejects(p.replay({...mate,events:[...mate.events,mate.events[0]]},o),/ended/);});
await test('signed resignation is sufficient',async()=>{const s=await p.completed(await add(empty(),'resign'),o);assert.equal(s.outcome.termination,'resignation');assert.equal(s.outcome.result,'0-1');});
await test('draw requires an opponent offer and acceptance',async()=>{let a=await add(empty(),'offer-draw');a=await add(a,'move','e2e4');a=await add(a,'accept-draw');assert.equal((await p.completed(a,o)).outcome.termination,'agreement');await assert.rejects(p.replay(await add(empty(),'accept-draw'),o),/offer/);});
await test('draw offer expires when recipient replies with a move',async()=>{let a=await add(empty(),'offer-draw');a=await add(a,'move','e2e4');a=await add(a,'move','e7e5');assert.equal((await p.replay(a,o)).offer,null);});
await test('automatic repetition draw preserves full position history',async()=>{let a=empty();for(const m of ['g1f3','g8f6','f3g1','f6g8','g1f3','g8f6','f3g1','f6g8'])a=await add(a,'move',m);assert.equal((await p.completed(a,o)).outcome.termination,'repetition');});
await test('clock-expiry and disconnect claims cannot invent results',async()=>{for(const kind of ['timeout','disconnect']){const a=copy(mate);a.events=[await p.sign({...a.events[0].action,kind,move:''},white)];await assert.rejects(p.replay(a,o),/action/);}});
await test('unknown timestamp fields rejected',async()=>{const a=copy(mate);a.events[0].action.timestamp=0;await assert.rejects(p.replay(a,o),/fields/);});
await test('duplicate and stale prefix imports do not roll back history',async()=>{assert.equal((await p.merge(mate,mate,o)).events.length,4);assert.equal((await p.merge(mate,empty(),o)).events.length,4);});
await test('conflicting valid signed branches are not silently selected',async()=>{const a=await add(empty(),'move','e2e4'),b=await add(empty(),'move','d2d4');await assert.rejects(p.merge(a,b,o),/Conflicting/);});
await test('signature randomness does not change the history root',async()=>{const a=copy(mate);a.events[0]=await p.sign(a.events[0].action,white);assert.equal((await p.replay(a,o)).root,(await p.replay(mate,o)).root);});
await test('transpositions have the same board but different history hashes',async()=>{let a=empty(),b=empty();for(const m of ['g1f3','g8f6','b1c3','b8c6'])a=await add(a,'move',m);for(const m of ['b1c3','b8c6','g1f3','g8f6'])b=await add(b,'move',m);const sa=await p.replay(a,o),sb=await p.replay(b,o);assert.equal(sa.position.fen(),sb.position.fen());assert.notEqual(sa.root,sb.root);});
await test('oversized and malformed archives rejected',async()=>{assert.throws(()=>p.parseArchive(' '.repeat(p.MAX_BYTES+1)));await assert.rejects(p.replay({...empty(),events:Array(2049).fill(mate.events[0])},o),/large/);await assert.rejects(p.replay({...empty(),result:'1-0'},o),/fields/);});
writeFileSync(new URL('../peer-results.json',import.meta.url),JSON.stringify(results,null,2)+'\n');if(results.some(r=>!r.passed))process.exitCode=1;
