// Control events: the submissions that are not moves.
//
// The contract sees a string of four or five characters and forms no opinion
// about it. That is the whole filter. So a resignation is not a new contract
// function, a new argument, or a flag — it is a string that happens not to be a
// move, and replay is where it acquires meaning.
//
// This is what keeps the contract ignorant while the game stays complete. Adding
// `resign` as a contract function would mean the contract knew that games can be
// resigned, which is a chess opinion, and the first one is the expensive one.
//
// The exact strings are FROZEN. They are in games already, or they will be, and
// a reader in ten years has only the published spec. See EVENTS-V1.md.

export const EVENT_STRINGS = {
  /** The sender resigns. The other side wins. */
  RESIGN: 'resgn',
  /** The sender offers a draw. */
  DRAW_OFFER: 'draw?',
  /** The sender accepts the offer standing against them. */
  DRAW_ACCEPT: 'draw!'
} as const;

export type EventKind = 'resign' | 'draw-offer' | 'draw-accept';

const BY_STRING: Record<string, EventKind> = {
  [EVENT_STRINGS.RESIGN]: 'resign',
  [EVENT_STRINGS.DRAW_OFFER]: 'draw-offer',
  [EVENT_STRINGS.DRAW_ACCEPT]: 'draw-accept'
};

/** Every reserved string, for the tests that prove none of them is a move. */
export const ALL_EVENT_STRINGS: readonly string[] = Object.values(EVENT_STRINGS);

/**
 * Is this submission a control event, and which one?
 *
 * Case sensitive, and deliberately so. UCI parsing is lenient about case because
 * people type moves into wallets by hand; a control string is generated by the
 * board, never typed, and one exact spelling means there is nothing to argue
 * about. `RESGN` is not a resignation, it is a malformed submission.
 */
export function parseEvent(mv: unknown): EventKind | null {
  if (typeof mv !== 'string') return null;
  return BY_STRING[mv] ?? null;
}

/**
 * Which side is this sender, for the purpose of a control event?
 *
 * Only a bound side can resign or agree a draw. On an open board where anyone
 * may play either colour there is nobody who owns the game, so there is nobody
 * who can end it — which is the honest answer, not a gap.
 *
 * White is checked first. If one principal somehow holds both sides the result
 * is White, deterministically. `readyToOpen` refuses that for ranked games, and
 * for an unranked one a self-game resigning as White is a coherent, if odd,
 * thing to have recorded.
 */
export function sideOf(rules: { white: string; black: string }, sender: string | null): 'white' | 'black' | null {
  const from = String(sender ?? '').toUpperCase();
  if (!from) return null;
  if (rules.white === from) return 'white';
  if (rules.black === from) return 'black';
  return null;
}
