import {afterEach,describe,it,expect,vi} from 'vitest';
import {MusicWebBridge} from '../music-web-bridge.mjs';
import {validate} from '../../../extensions/music-support/validate.js';
const origin='chrome-extension://'+'a'.repeat(32), id='b'.repeat(32);
let bridge:any;
afterEach(()=>{bridge?.close();vi.useRealTimers();});
function fixture(){
 const w={running:false,optional:vi.fn(async()=>null),setup:vi.fn(async()=>({address:'test'})),status:vi.fn(async()=>({address:'test',balanceMicroSTX:'1000000',entries:[],secret:'never'}))};
 const l={active:null as any,snapshot:vi.fn(),disable:vi.fn(()=>{l.active=null;}),enable:vi.fn(async()=>{l.active={token:'approval',fee:300};return l.active;}),start:vi.fn(async()=>({outcome:'requested'}))};
 const media={audio:vi.fn(async()=>{})};bridge=new MusicWebBridge(w,l,media);return {w,l,media};
}
async function pair(){const p=await bridge.call(origin,{method:'pair'});await bridge.approve(p.id);return (await bridge.call(origin,{method:'poll',id:p.id})).token;}
async function support(token:string){const p=await bridge.call(origin,{method:'support',token,fee:300});await bridge.approve(p.id);}
describe('website support permissions',()=>{
 it('requires local pairing, supports a new wallet, exposes no secrets',async()=>{const {w}=fixture();await expect(bridge.call('https://xtrata.xyz',{method:'pair'})).rejects.toThrow();await expect(bridge.call(origin,{method:'setup',token:id})).rejects.toThrow();const token=await pair();expect(await bridge.call(origin,{method:'status',token})).toMatchObject({address:null,enabled:false});expect(w.setup).not.toHaveBeenCalled();await bridge.call(origin,{method:'setup',token});w.optional.mockResolvedValue({address:'test'} as any);expect(await bridge.call(origin,{method:'status',token})).not.toHaveProperty('secret');await expect(bridge.call(origin,{method:'return',token})).rejects.toThrow();});
 it('requires separate spending approval and deduplicates starts without a duration',async()=>{const {l}=fixture();const token=await pair();const start={method:'start',token,id,song:315};await expect(bridge.call(origin,start)).rejects.toThrow();await support(token);expect(l.start).not.toHaveBeenCalled();await bridge.call(origin,start);await bridge.call(origin,start);expect(l.start).toHaveBeenCalledTimes(1);expect(l.start).toHaveBeenCalledWith(expect.objectContaining({song:315}));expect(l.start.mock.calls[0][0]).not.toHaveProperty('duration');});
 it('allows legacy short or unknown-duration starts and ignores the duration field',async()=>{const {l,media}=fixture();const token=await pair();await support(token);for(const [startId,duration] of [['c'.repeat(32),59],['d'.repeat(32),Number.NaN]])await bridge.call(origin,{method:'start',token,id:startId,song:315,duration});expect(media.audio).toHaveBeenCalledTimes(2);expect(l.start).toHaveBeenCalledTimes(2);for(const [input] of l.start.mock.calls)expect(input).not.toHaveProperty('duration');});
 it('never charges a busy start later',async()=>{const {w,l}=fixture();const token=await pair();await support(token);w.running=true;await bridge.call(origin,{method:'start',token,id,song:315,duration:61});w.running=false;await bridge.call(origin,{method:'start',token,id,song:315,duration:61});expect(l.start).not.toHaveBeenCalled();});
 it('stop during validation prevents a payment',async()=>{const {media,l}=fixture();const token=await pair();await support(token);let release:any;media.audio.mockImplementation(()=>new Promise(r=>release=r));const start=bridge.call(origin,{method:'start',token,id,song:315,duration:61});await bridge.call(origin,{method:'stop',token});release();await expect(start).rejects.toThrow('stopped');expect(l.start).not.toHaveBeenCalled();});
 it('stopping cancels an unapproved spending request',async()=>{fixture();const token=await pair();const p=await bridge.call(origin,{method:'support',token,fee:300});await bridge.call(origin,{method:'stop',token});await expect(bridge.approve(p.id)).rejects.toThrow('expired');});
 it('stop while approval is being checked revokes the eventual grant',async()=>{const {l}=fixture();const token=await pair();let release:any;l.enable.mockImplementation(()=>new Promise(r=>release=()=>{l.active={token:'late',fee:300};r(l.active);}));const p=await bridge.call(origin,{method:'support',token,fee:300});const approving=bridge.approve(p.id);await bridge.call(origin,{method:'stop',token});release();await expect(approving).rejects.toThrow();expect(l.active).toBe(null);});
 it('expires disconnected sessions and does not stop another owner',async()=>{vi.useFakeTimers();const {l}=fixture();const token=await pair();await support(token);vi.advanceTimersByTime(125000);expect(l.disable).toHaveBeenCalledTimes(1);await expect(bridge.call(origin,{method:'status',token})).rejects.toThrow();});
 it('repeated approval is idempotent and tokens are origin-bound',async()=>{fixture();const p=await bridge.call(origin,{method:'pair'});await bridge.approve(p.id);await bridge.approve(p.id);expect(bridge.connections.size).toBe(1);const token=(await bridge.call(origin,{method:'poll',id:p.id})).token;await expect(bridge.call(origin.replaceAll('a','b'),{method:'status',token})).rejects.toThrow();});
 it('restricts extension messages to the main website lounge top frame',()=>{const sender={id:'extension',frameId:0,documentId:'doc',tab:{id:1},origin:'https://xtrata.xyz',url:'https://xtrata.xyz/radio/browser-lounge'};expect(validate({id,method:'status'},sender,'extension')).toBeTruthy();for(const bad of [{frameId:1},{origin:'https://evil.test'},{url:'https://xtrata.xyz/radio'},{id:'other'}])expect(()=>validate({id,method:'status'},{...sender,...bad},'extension')).toThrow();expect(validate({id,method:'start',song:315,startId:id},sender,'extension')).toBeTruthy();expect(validate({id,method:'start',song:315,startId:id,duration:59},sender,'extension')).toBeTruthy();});
});
