// Canonical local Chromium renderer. No network media, wallets or publication.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || "playwright");
const fs = require("fs"),
  path = require("path");
const dir = path.resolve(__dirname, "..");
(async () => {
  const browser = await chromium.launch({
    ...(process.env.CHROMIUM_EXECUTABLE
      ? { executablePath: process.env.CHROMIUM_EXECUTABLE }
      : {}),
    headless: true,
  });
  try {
    const page = await browser.newPage();
    await page.goto(
      process.env.AUDIONAUT_URL ||
        "http://127.0.0.1:8768/audional-sequencer-l1xl2-v1/index.html",
    );
    const sounds = await page.evaluate(
      async () => (await import("./js/onboard-catalog.js")).ONBOARD_SOUNDS,
    );
    const manifest = {
      version: "2.0.0",
      canonicalEnvironment: await browser.version(),
      generatedAt: new Date().toISOString(),
      sampleRate: 44100,
      encoding: "PCM16 WAV",
      patches: sounds.length,
      assets: {},
      families: {},
      deployment: { status: "local", references: [] },
    };
    for (const family of [...new Set(sounds.map((s) => s.family))]) {
      const pack = {
        format: "audionaut-onboard-family/2",
        version: "2.0.0",
        family,
        entries: {},
      };
      for (const sound of sounds.filter((s) => s.family === family))
        for (const root of sound.roots.length ? sound.roots : [null])
          for (const velocity of sound.velocities) {
            const rendered = await page.evaluate(
              async ({ sound, root, velocity }) => {
                const { renderOnboard } = await import(
                  "./js/onboard-render.js"
                );
                const r = await renderOnboard(sound, root, velocity);
                let text = "";
                const b = new Uint8Array(r.bytes);
                for (let i = 0; i < b.length; i += 32768)
                  text += String.fromCharCode(...b.subarray(i, i + 32768));
                // Float32 working render remains local, outside publication packs.
                const channels = Array.from(
                  { length: r.audioBuffer.numberOfChannels },
                  (_, c) => r.audioBuffer.getChannelData(c),
                );
                let working = "";
                for (const a of channels) {
                  const bytes = new Uint8Array(a.buffer);
                  for (let i = 0; i < bytes.length; i += 32768)
                    working += String.fromCharCode(
                      ...bytes.subarray(i, i + 32768),
                    );
                }
                return {
                  metadata: r.metadata,
                  audioData: btoa(text),
                  working: btoa(working),
                  byteLength: b.length,
                };
              },
              { sound, root, velocity },
            );
            const id = rendered.metadata.assetId;
            pack.entries[id] = {
              filename: sound.label + ".wav",
              metadata: rendered.metadata,
              audioData: rendered.audioData,
            };
            manifest.assets[id] = {
              ...rendered.metadata,
              byteLength: rendered.byteLength,
              pack: `media/onboard-v2/${family}.json`,
            };
            const workingDir = path.join(dir, "media/onboard-v2/working");
            fs.mkdirSync(workingDir, { recursive: true });
            fs.writeFileSync(
              path.join(workingDir, id.replace(/[^\w.-]/g, "_") + ".f32"),
              Buffer.from(rendered.working, "base64"),
            );
          }
      const serialized = JSON.stringify(pack);
      fs.writeFileSync(
        path.join(dir, `media/onboard-v2/${family}.json`),
        serialized,
      );
      manifest.families[family] = {
        patches: sounds.filter((s) => s.family === family).length,
        assets: Object.keys(pack.entries).length,
        packBytes: Buffer.byteLength(serialized),
      };
      console.log(family, manifest.families[family]);
    }
    manifest.totalPackBytes = Object.values(manifest.families).reduce(
      (n, f) => n + f.packBytes,
      0,
    );
    manifest.totalAudioBytes = Object.values(manifest.assets).reduce(
      (n, a) => n + a.byteLength,
      0,
    );
    fs.writeFileSync(
      path.join(dir, "media/onboard-v2/manifest.json"),
      JSON.stringify(manifest, null, 2),
    );
    fs.writeFileSync(
      path.join(dir, "js/onboard-manifest.js"),
      "// Canonical approved-byte metadata; generated by scripts/build-onboard.cjs.\nexport const ONBOARD_MANIFEST = " +
        JSON.stringify(manifest) +
        ";\n",
    );
    console.log(
      "Complete",
      manifest.patches,
      Object.keys(manifest.assets).length,
      manifest.totalPackBytes,
    );
  } finally {
    await browser.close();
  }
})().catch((e) => {
  console.error(e);
  process.exit(1);
});
