import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {gzipSync} from 'node:zlib';
import {build,transform} from '../X-Chess_2.0/node_modules/esbuild/lib/main.js';
import {fileURLToPath} from 'node:url';
const root=new URL('./',import.meta.url), read=p=>readFileSync(new URL(p,root),'utf8');
mkdirSync(new URL('dist/',root),{recursive:true});
const bridge=await build({entryPoints:[fileURLToPath(new URL('src/v2-wallet.ts',root))],bundle:true,write:false,minify:true,format:'iife',target:'es2022'});
const app=await transform(read('src/imported-app.js'),{minify:true,target:'es2022',legalComments:'inline'});
const script='globalThis.__XCHESS_V3_CONFIG__='+read('local-config.json')+';\n'+bridge.outputFiles[0].text+'\n'+app.code;
const v3=read('src/shell.html').replace('<!-- APP_SCRIPT -->',()=>'<script>'+script.replaceAll('</script','<\\/script')+'</script>');
const peerBuild=await build({entryPoints:[fileURLToPath(new URL('src/peer/ui.ts',root))],bundle:true,write:false,minify:true,format:'iife',target:'es2022'});
const peer=read('src/peer/page.html').replace('<!-- PEER_SCRIPT -->',()=>'<script>'+(bridge.outputFiles[0].text+'\n'+peerBuild.outputFiles[0].text).replaceAll('</script','<\\/script')+'</script>');
const v2=read('../X-Chess_2.0/releases/2.2.0/xchess.html');
const sha=s=>createHash('sha256').update(s).digest('hex');
if(sha(v2)!=='23774fd3f961b0d801d84555100b0b7e5facc3a43c4ed8e79b0b779c92ad88b6')throw Error('V2 baseline changed; review and retest before repinning');
const packs={v2:gzipSync(v2,{level:9,mtime:0}).toString('base64'),v3:gzipSync(v3,{level:9,mtime:0}).toString('base64'),peer:gzipSync(peer,{level:9,mtime:0}).toString('base64')};
const loader=read('src/loader.js').replace('/* PACKS */{}',JSON.stringify(packs));
const compact=(await transform(loader,{minify:true,target:'es2022'})).code;
const html='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>X-Chess 3.0</title></head><body><p id="xchess-loading" role="status">Opening X-Chess…</p><script>'+compact.replaceAll('</script','<\\/script')+'</script></body></html>';
const bytes=Buffer.byteLength(html),chunks=Math.ceil(bytes/16384);
if(chunks>32)throw Error('Artifact exceeds 32 chunks');
let rolling=Buffer.alloc(32);const buf=Buffer.from(html);for(let i=0;i<buf.length;i+=16384)rolling=createHash('sha256').update(Buffer.concat([rolling,buf.subarray(i,i+16384)])).digest();
writeFileSync(new URL('dist/xchess.html',root),html);
writeFileSync(new URL('dist/v3-expanded.html',root),v3);
writeFileSync(new URL('dist/peer.html',root),peer);
writeFileSync(new URL('dist/peer-manifest.json',root),JSON.stringify({protocol:'xchess-peer-v1',deployment:'local only',peerHtmlSha256:sha(peer),contractSha256:sha(read('contracts/xchess-peer-v1.clar')),rules:'standard-v2-engine-snapshot-1',engineSourceSha256:Object.fromEntries(['board','engine','fen','moves','uci'].map(n=>[n,sha(read('src/peer/chess/'+n+'.ts'))]))},null,2)+'\n');
writeFileSync(new URL('dist/manifest.json',root),JSON.stringify({version:'3.0.0-local',htmlSha256:sha(html),bytes,chunks,rollingHash:rolling.toString('hex'),v2Sha256:sha(v2),v3ExpandedSha256:sha(v3),contract:'xchess-core-v3',deployment:'local only',contractSha256:sha(read('contracts/xchess-core-v3.clar')),sourceSha256:Object.fromEntries(['src/imported-app.js','src/shell.html','src/v2-wallet.ts','src/loader.js','local-config.json','build.mjs'].map(p=>[p,sha(read(p))])),compression:'gzip; browser DecompressionStream'},null,2)+'\n');
console.log(`${bytes} bytes / ${chunks} chunks; SHA-256 ${sha(html)}`);
