import * as wallet from '../upstream/src/index';
import {makeUnsignedContractCall,Cl,privateKeyToPublic,deserializeTransaction} from '@stacks/transactions';
import {signReviewed,TESTNET_CONTRACT} from '../adapter';
import vectors from '../upstream/test/vectors/derivation.vectors.json';
import signing from '../upstream/test/vectors/signing.vectors.json';
const $=(id:string)=>document.getElementById(id) as HTMLInputElement;
const bytes=(s:string)=>Uint8Array.from(s.match(/../g)!.map(x=>parseInt(x,16)));
const hex=(b:Uint8Array)=>Array.from(b,x=>x.toString(16).padStart(2,'0')).join('');
const report:any={schema:'xtrata-deorganized-canary/1',library:'0.4.0',origin:location.origin,checks:[],ceremonies:[],broadcasts:0};
let credentialId:Uint8Array|undefined,address='',publicKey='',busy=false;
const notice=(text:string,error=false)=>{$('message').textContent=text;$('message').className=error?'error':'';};
const row=(name:string,pass:boolean,detail='')=>{const li=document.createElement('li');li.textContent=(pass?'PASS — ':'FAIL — ')+name+(detail?' · '+detail:'');li.className=pass?'':'fail';$('checks').append(li);report.checks.push({name,pass,detail});};
async function run(fn:()=>Promise<void>){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e:any){const code=e.code||e.reason||e.name||'Error';report.ceremonies.push({at:new Date().toISOString(),outcome:'not-proven',code});notice(`Test not completed (${code}). Cancellation, provider state or device policy can cause this; it is not proof that the browser lacks PRF support. A credential may have been created even if verification failed.`,true);}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);($('sign') as any).disabled=!address;}}
function account(prf:Uint8Array){const {root}=wallet.prfBytesToRoot(prf);try{const node=root.derive("m/44'/5757'/0'/0/0");const p=privateKeyToPublic(hex(node.privateKey!)+'01');return {address:wallet.deriveStacksAccount(root,'testnet').address,publicKey:typeof p==='string'?p:hex(p)};}finally{root.wipePrivateData();}}
async function ceremony(){return wallet.evaluatePrf({challenge:crypto.getRandomValues(new Uint8Array(32)),rpId:location.hostname,allowCredentialIds:credentialId?[credentialId]:undefined,timeoutMs:90000});}
function compare(next:{address:string;publicKey:string}){const expected=$('expected').value.trim()||address;if(expected&&expected!==next.address)throw Object.assign(Error(),{code:'ADDRESS_MISMATCH'});address=next.address;publicKey=next.publicKey;$('address').textContent=address;report.address=address;report.continuity=expected?'matched':'baseline-established';}
$('offline').onclick=()=>run(async()=>{$('checks').replaceChildren();report.checks=[];for(const v of vectors.vectors){const prf=bytes(v.prfBytesHex);try{const got=wallet.deriveAddresses(prf,{salt:v.salt}).stacks.address;row(v.name,got===v.stacks.address);}finally{prf.fill(0);}}
 for(const v of signing.vectors){const prf=bytes(v.signerPrfBytesHex);try{const result=wallet.signStacksTransaction(prf,deserializeTransaction(v.unsignedHex),{...v.options,salt:v.salt});const expected:any=v.expected;const okay=!expected.error&&result.kind===expected.kind&&hex(result.transaction)===expected.signedHex&&(result.kind==='origin-signed'?!('txid'in result):result.txid===expected.txid);row('Signing class '+v.class,okay);}catch(e:any){row('Signing class '+v.class,e.name===(v.expected as any).error);}finally{prf.fill(0);}}
 notice('Software checks finished. These results do not prove a real device ceremony or cross-device recovery.');});
$('create').onclick=()=>run(async()=>{if(!window.isSecureContext)throw Object.assign(Error(),{code:'SECURE_ORIGIN_REQUIRED'});notice('Create a disposable test passkey. Do not select a funded wallet.');const c=await wallet.createPasskey({rpName:'Xtrata compatibility TEST — do not fund',rpId:location.hostname,userId:crypto.getRandomValues(new Uint8Array(32)),userName:'compatibility-test-'+Date.now(),challenge:crypto.getRandomValues(new Uint8Array(32)),timeoutMs:90000});credentialId=new Uint8Array(c.rawId);const prf=await ceremony();try{address='';compare(account(prf));report.ceremonies.push({at:new Date().toISOString(),step:'create-and-get',outcome:'pass',backupEligible:true});notice('Test credential created and a dedicated PRF sign-in succeeded. Save the public address to compare on another device.');}finally{prf.fill(0);}});
$('signin').onclick=()=>run(async()=>{notice('Select only the disposable compatibility-test credential.');const prf=await ceremony();try{compare(account(prf));report.ceremonies.push({at:new Date().toISOString(),step:'sign-in',outcome:'pass',continuity:report.continuity,backupEligibility:'not-checked-on-get-by-library'});notice('Sign-in succeeded. '+(report.continuity==='matched'?'The expected address matched.':'Baseline recorded; repeat sign-in or compare on another device.'));}finally{prf.fill(0);}});
$('sign').onclick=()=>run(async()=>{const [contractAddress,contractName]=TESTNET_CONTRACT.split('.');const tx=await makeUnsignedContractCall({contractAddress,contractName,functionName:'set-parent-delegate',functionArgs:[Cl.principal(address),Cl.bool(false)],publicKey,network:'testnet',fee:0n,nonce:0n,postConditionMode:'deny',postConditions:[]});notice('Re-authorize the test credential to verify an offline signature. Nothing will be broadcast.');const prf=await ceremony();try{compare(account(prf));const raw=tx.serialize();const signed=signReviewed(prf,raw,{contractId:TESTNET_CONTRACT,functionNames:['set-parent-delegate'],maxMinerFee:0n,expectedUnsignedHex:raw});deserializeTransaction(signed.transactionHex).verifyOrigin();report.ceremonies.push({at:new Date().toISOString(),step:'offline-signature',outcome:'pass',network:'testnet'});notice('Offline signature verified against the Testnet transaction. Signed bytes were discarded; nothing was broadcast.');}finally{prf.fill(0);}});
$('export').onclick=()=>{const out={...report,exportedAt:new Date().toISOString(),device:$('device').value,provider:$('provider').value,sdp:$('sdp').value,notes:$('notes').value,userAgent:navigator.userAgent,secureContext:window.isSecureContext};const url=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='passkey-canary-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
