// optimize-audio.js — automatic "best quality, smallest size" for the wizard.
//
// When an audio file lands in the wizard dropzone it is transcoded in-browser to
// Opus-in-WebM (.weba, Music High Quality: libopus 96k VBR, compression 7) with
// the Audional/Xtrata identification tags — the exact preset the SUNO page and
// the server-side optimiser use (see AUDIO_OPTIMIZATION.md). The quote is then
// taken on the SMALLER file, so byte-driven mining fees drop with it.
//
// IMPORTANT: this file deliberately uses the SINGLE-THREADED ffmpeg core
// (@ffmpeg/core-st). The multithreaded core needs SharedArrayBuffer, which
// requires COOP/COEP isolation headers — and those break the wallet popup flow.
// /wizard therefore ships WITHOUT isolation headers (only /wizard/suno has
// them), trading encode speed for an intact wallet. Fail-safe: any load or
// transcode problem simply returns the original file untouched.
(function () {
  'use strict';

  const FFMPEG_JS = 'https://cdn.jsdelivr.net/npm/@ffmpeg/ffmpeg@0.11.6/dist/ffmpeg.min.js';
  const CORE_ST = 'https://cdn.jsdelivr.net/npm/@ffmpeg/core-st@0.11.1/dist/ffmpeg-core.js';
  const TIMEOUT_MS = 240000; // hard stop for the transcode — never hold the railroad hostage
  const ENGINE_TIMEOUT_MS = 30000; // hard stop for loading ffmpeg.wasm itself (CDN hiccups)
  const MIN_BYTES = 64 * 1024; // below this the saving isn't worth the wait
  const KEEP_RATIO = 0.95; // must save at least 5% or the original is kept

  // Containers that are already Opus (or likely efficient enough to leave alone).
  const ALREADY_OPTIMAL = /\.(weba|opus|webm)$/i;
  // Formats worth converting. Video is out of scope (still passes through untouched).
  const CONVERTIBLE = /\.(mp3|wav|aif|aiff|flac|m4a|aac|ogg|oga)$/i;

  // Same command the SUNO builder and the server-side optimiser use (Music HQ).
  const OPUS_ARGS = (inName) => [
    '-i', inName, '-map', '0:a:0', '-map_chapters', '-1', '-vn', '-sn', '-dn',
    '-metadata', 'AOE-Generator=AudionalOpusEncoder_v1.0',
    '-metadata', 'X-AudionalTool-Origin=AudionalOpusEncoder_v1.0',
    '-metadata', 'comment=Generated by AudionalOpusEncoder_v1.0',
    '-metadata', 'xtrata_mime=audio/webm; codecs=opus',
    '-metadata', 'xtrata_media_kind=audio',
    '-metadata:s:a:0', 'handler_name=Audio', '-metadata:s:a:0', 'media_type=audio',
    '-c:a', 'libopus', '-b:a', '96k', '-vbr', '1', '-compression_level', '7', '-application', 'audio',
    '-f', 'webm', 'out.weba',
  ];

  let _script = null;
  function loadScript() {
    if (window.FFmpeg) return Promise.resolve();
    if (_script) return _script;
    _script = new Promise((resolve, reject) => {
      const s = document.createElement('script');
      s.src = FFMPEG_JS;
      s.onload = () => resolve();
      s.onerror = () => reject(new Error('could not load ffmpeg.wasm'));
      document.head.appendChild(s);
    });
    return _script;
  }

  // The single-threaded core (mainName:'main' + core-st) is SINGLE-USE: after one run()
  // the wasm runtime exits and the instance is dead. So each optimise() gets a FRESH
  // instance that is discarded afterwards — reusing one across a batch makes every file
  // after the first throw "ffmpeg.wasm can only run one command at a time" (which showed
  // up as every second batch song failing). loadScript stays a one-time global; only the
  // core instance is per-file.
  async function createEngine(onStatus) {
    await loadScript();
    const FF = window.FFmpeg;
    if (!FF || !FF.createFFmpeg) throw new Error('ffmpeg.wasm unavailable');
    onStatus && onStatus('Loading the audio engine…');
    const f = FF.createFFmpeg({ log: false, mainName: 'main', corePath: CORE_ST });
    await f.load();
    return f;
  }

  const fetchFile = async (file) => new Uint8Array(await file.arrayBuffer());
  const baseName = (name) => String(name || 'audio').replace(/\.[^.]+$/, '');

  function isCandidate(name, size) {
    if (!CONVERTIBLE.test(String(name || ''))) return false;
    if (ALREADY_OPTIMAL.test(String(name || ''))) return false;
    return (size || 0) >= MIN_BYTES;
  }

  // optimize(file, onStatus, opts) → always resolves:
  //   { file, originalBytes, optimizedBytes }            — converted, smaller
  //   { file, originalBytes, skipped: <reason> }         — original untouched
  // opts.signal (optional AbortSignal-like {aborted}) is checked between steps;
  // when set the original is returned ('skipped-by-user').
  async function optimize(file, onStatus, opts) {
    const originalBytes = file.size;
    const aborted = () => !!(opts && opts.signal && opts.signal.aborted);
    if (ALREADY_OPTIMAL.test(file.name)) return { file, originalBytes, skipped: 'already-opus' };
    if (!CONVERTIBLE.test(file.name)) return { file, originalBytes, skipped: 'not-audio' };
    if (originalBytes < MIN_BYTES) return { file, originalBytes, skipped: 'too-small' };

    let f;
    try {
      // The engine load itself is raced against a timeout: a stalled CDN fetch
      // must degrade to "inscribe the original", never to a perpetual spinner.
      f = await Promise.race([
        createEngine(onStatus),
        new Promise((_r, reject) =>
          setTimeout(() => reject(new Error('audio engine load timed out')), ENGINE_TIMEOUT_MS)),
      ]);
    } catch (e) {
      return { file, originalBytes, skipped: 'engine-unavailable' };
    }
    if (aborted()) return { file, originalBytes, skipped: 'skipped-by-user' };

    const inName = 'in-' + Date.now() + '.' + ((file.name.match(/\.([a-z0-9]+)$/i) || [])[1] || 'mp3');
    try {
      onStatus && onStatus('Optimising to Opus (Music HQ) — single-threaded, may take a minute…');
      f.FS('writeFile', inName, await fetchFile(file));
      if (aborted()) return { file, originalBytes, skipped: 'skipped-by-user' };
      const run = f.run(...OPUS_ARGS(inName));
      const timeout = new Promise((_r, reject) =>
        setTimeout(() => reject(new Error('optimisation timed out')), TIMEOUT_MS));
      await Promise.race([run, timeout]);
      const out = f.FS('readFile', 'out.weba');
      if (aborted()) return { file, originalBytes, skipped: 'skipped-by-user' };
      if (!out || !out.length || out.length >= originalBytes * KEEP_RATIO) {
        return { file, originalBytes, skipped: 'already-efficient' };
      }
      const optimized = new File([out], baseName(file.name) + '.weba', {
        type: 'audio/webm; codecs=opus',
        lastModified: Date.now(),
      });
      return { file: optimized, originalBytes, optimizedBytes: optimized.size };
    } catch (e) {
      return { file, originalBytes, skipped: 'failed' };
    } finally {
      // Single-use core: discard the whole instance (also frees its in-memory FS), so the
      // next file in the batch always starts from a clean, live engine.
      try { f.exit(); } catch (_e) { /* noop */ }
    }
  }

  window.XtrataAudioOptimizer = { optimize, isCandidate };
})();
