[project]
name = 'xtrata'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.sip009-nft-trait]
path = "contracts/sip009-nft-trait.clar"
clarity_version = 2
epoch = 2.5

[contracts.sip010-ft-trait]
path = "contracts/sip010-ft-trait.clar"
clarity_version = 2
epoch = 2.5

[contracts.mock-usdcx]
path = 'contracts/mock-usdcx.clar'
clarity_version = 3
epoch = 'latest'

[contracts.mock-sbtc]
path = 'contracts/mock-sbtc.clar'
clarity_version = 3
epoch = 'latest'

[contracts.mock-ipfs-collection]
path = 'contracts/mock-ipfs-collection.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-v1-1-0]
path = 'contracts/xtrata-v1.1.0.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-v1-1-1]
path = 'contracts/xtrata-v1.1.1.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-v2-1-0]
path = 'contracts/xtrata-v2.1.0.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-v2-1-1]
path = 'contracts/xtrata-v2.1.1.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-v3-2-2]
path = 'contracts/xtrata-v3.2.2.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-v3-2-3]
path = 'contracts/xtrata-v3.2.3.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-small-mint-v1-0]
path = 'contracts/xtrata-small-mint-v1.0.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-small-mint-v1-1]
path = 'contracts/xtrata-small-mint-v1.1.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-backup-registry-v1-0]
path = 'contracts/xtrata-backup-registry-v1.0.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-migrated-ipfs-collection-v1-0]
path = 'contracts/xtrata-migrated-ipfs-collection-v1.0.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-collection-mint-v1-0]
path = 'contracts/xtrata-collection-mint-v1.0.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-collection-mint-v1-1]
path = 'contracts/xtrata-collection-mint-v1.1.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-collection-mint-v1-2]
path = 'contracts/xtrata-collection-mint-v1.2.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-collection-mint-v1-3]
path = 'contracts/xtrata-collection-mint-v1.3.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-collection-mint-v1-4]
path = 'contracts/xtrata-collection-mint-v1.4.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-preinscribed-collection-sale-v1-0]
path = 'contracts/xtrata-preinscribed-collection-sale-v1.0.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-market-v1-0]
path = 'contracts/xtrata-market-v1.0.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-market-v1-1]
path = 'contracts/xtrata-market-v1.1.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-market-stx-v1-0]
path = 'contracts/xtrata-market-stx-v1.0.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-market-usdc-v1-0]
path = 'contracts/xtrata-market-usdc-v1.0.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-market-sbtc-v1-0]
path = 'contracts/xtrata-market-sbtc-v1.0.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-commerce]
path = 'contracts/xtrata-commerce.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-vault]
path = 'contracts/xtrata-vault.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-arcade-scores-v1-0]
path = 'contracts/xtrata-arcade-scores-v1.0.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-arcade-scores-v1-1]
path = 'contracts/xtrata-arcade-scores-v1.1.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-arcade-scores-v1-2]
path = 'contracts/xtrata-arcade-scores-v1.2.clar'
clarity_version = 3
epoch = 'latest'

[contracts.xtrata-arcade-scores-v1-3]
path = 'contracts/xtrata-arcade-scores-v1.3.clar'
clarity_version = 3
epoch = 'latest'


[repl.analysis]
passes = [
  'check_checker',
]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
