# Generates index.html from the data below.
# Edit CAMPAIGNS, re-run: python3 build-page.py
#
# Same shape as shots/build-page.py, which produced the X Chess launch board.
# Kept deliberately: that page is the proven format and the voice corpus both.
# What is new here is `shot` pointing at shots/three/, which is generated by
# harness/shots.mjs against the real inscription rather than posed by hand.
import json, html, pathlib

TOURNAMENT = 3016
BOARD = 3014
SHOTS_ABS = "/Users/melophonic/Documents/GitHub/xtrata/X-Chess/shots/three"

CAMPAIGNS = [
 {"id":"thread","title":"The invitation","blurb":"Post this first, as one thread. It answers the sceptic inside itself.","groups":[
   {"kind":"thread","label":"Thread: exhibition three is live","posts":[
     {"text":"Ten AI players. Ninety games. Every move a transaction on Stacks.\n\nExhibition Three is live, on a board that is itself an inscription.\n\nhttps://xtrata.xyz/i/3014",
      "shot":"01-standings.png","note":"The hero. Shows the table, the ladder and the verified marks in one frame."},
     {"text":"Each player is an inscription.\n\nIts instructions were written, budgeted to 1200 characters, and sealed on chain before it played a move.\n\nNobody can edit a character mid tournament. Not me either.",
      "shot":"07-sheet-fathom.png","note":"Fathom's sheet, read straight off chain."},
     {"text":"The honest part. The model choosing the moves runs off chain. I cannot inscribe weights and will not pretend otherwise.\n\nWhat is on chain is everything that decides a game. The engine, the characters, the pairings, the rules each game committed to, and every move.",
      "note":"THE POST THAT BUYS THE REST. Do not soften it and do not drop it."},
     {"text":"So you do not have to trust the table.\n\nFetch the manifest. Fetch the characters it names. Replay the moves. Check each game against the rules hash it committed to.\n\nIf your replay disagrees with my standings, mine is wrong.",
      "shot":"02-rounds.png","note":"Every game carries its own verified mark. That is the whole argument."},
     {"text":"Something I did not design for. A game commits its two players and nothing that says which tournament it is.\n\nSo one pair gets one ranked game, ever. Two exhibitions used all thirty of theirs. The third needed a new rule just to be possible.",
      "note":"The developer post. Most likely of the set to travel."},
     {"text":"Three of the ten search deeper than the rest.\n\nIt is declared in the manifest and the board marks it declared, because nothing on chain can prove it.\n\nEvery other number on that table was recomputed. That one is my word, labelled as my word.",
      "shot":"01-standings.png","note":"Crop to the table so the dotted +1 and +2 are legible."},
     {"text":"Board, engine, characters and manifest are all inscriptions you can open and read.\n\nhttps://xtrata.xyz/i/3014",
      "shot":"06-mobile-standings.png","note":"Close on the phone shot. Same board, no app."}]}]},

 {"id":"result","title":"The result worth citing","blurb":"Post after the thread has been up an hour or so.","groups":[
   {"kind":"single","posts":[
     {"text":"Plumb won the first exhibition and plays on the house engine.\n\nOblique finished joint last and was given the deepest search on purpose, so that a ladder decided by depth would show up as a table turning upside down.\n\nIt did not turn.",
      "shot":"03-game48-plumb-oblique.png","note":"Say it as one game. It is one game."},
     {"text":"Round one. Five games, five checkmates, no draws.\n\nThirty two to sixty eight signed transactions a game, and 0.035 STX for the round.",
      "shot":"02-rounds.png"},
     {"text":"Every result on that board was derived by replaying the chain, not read from a database.\n\nThere is no database.",
      "shot":"04-game47-checkmate.png"}]}]},

 {"id":"standalone","title":"Standalone posts","blurb":"Pick one. Do not post all of them.","groups":[
   {"kind":"single","posts":[
     {"text":"An application that is an inscription, running a tournament whose result you can recompute from chain without asking me for anything.\n\nTen AI players, ninety games, every move a transaction on Stacks.\n\nhttps://xtrata.xyz/i/3014",
      "shot":"01-standings.png","note":"For developers."},
     {"text":"No server. No account. No referee. No company.\n\nTen AI personalities playing ninety games of chess, and a board that is an inscription rather than a website.\n\nIt still works.\n\nhttps://xtrata.xyz/i/3014",
      "shot":"05-play.png","note":"Subtraction. The pattern that works best in this corpus."},
     {"text":"The chess board is not hosted. It is inscribed.\n\nThe players are not accounts. They are inscriptions.\n\nNinety games are running now.\n\nhttps://xtrata.xyz/i/3014",
      "note":"Pin this one."},
     {"text":"Ten AI players with their own wallets, signing their own moves, playing for a table nobody can edit.\n\nNinety games on Stacks. Watch it settle in real time.\n\nhttps://xtrata.xyz/i/3014",
      "shot":"06-mobile-standings.png"}]}]},

 {"id":"replies","title":"Replies","blurb":"Answers to what will actually be asked. Keep each shorter than the post it answers.","groups":[
   {"kind":"single","label":"Under any post","posts":[
     {"text":"No, and I would not claim it. The model runs off chain because weights cannot be inscribed.\n\nIts instructions are on chain, the engine it uses is on chain, and every move it makes is on chain. That is the part you can check.",
      "note":"To: is the AI on chain?"},
     {"text":"Stacks. Anchored to Bitcoin and mined by Bitcoin through Proof of Transfer.\n\nThe bytes live on Stacks. Bitcoin is the settlement layer underneath.",
      "note":"To: what chain? Never say on Bitcoin."},
     {"text":"Yes. Open the board and open a game. There is no signup because there is nothing to sign up to.\n\nYou need a Stacks wallet with a little STX, because a move is a transaction.\n\nhttps://xtrata.xyz/i/3014",
      "shot":"05-play.png","note":"To: can I play?"},
     {"text":"Better than open source for this purpose. The running application IS the source, inscribed at 3014. What you audit is what executes.",
      "note":"To: is it open source?"},
     {"text":"Read the manifest, which names every player, pairing and round. Replay each game's moves through the rules it committed to. Compare to the standings.\n\nNothing in that loop asks me for anything.",
      "shot":"02-rounds.png","note":"To: how do I verify a result?"},
     {"text":"No. The engine ranks every legal move and the character chooses among them by style.\n\nThat is why the same engine gave one player six points and another two in the first exhibition.",
      "note":"To: are they not just playing the engine's top move?"},
     {"text":"About a hundredth of a STX to open, and four hundred microstacks a move.\n\nA ninety game tournament is a few STX in total.",
      "note":"To: what does it cost?"},
     {"text":"Because the result does not depend on me being honest.\n\nTake the inscriptions, replay the games, get the same table. That is a different kind of claim from a leaderboard on a website.",
      "note":"To: why does this matter?"},
     {"text":"The manifest stays on chain and so does every game. The standings are derivable forever by anybody who wants to check them.\n\nNothing expires because nothing is hosted.",
      "note":"To: what happens when it finishes?"},
     {"text":"Both are mine and only 3016 is the tournament. 3015 is the same bytes inscribed with a dependency on the previous manifest, which the board reads as a revision rather than a sequence, so it answers to the older one's id.\n\nI left it there rather than pretend it did not happen.",
      "note":"To: why are there two Exhibition Threes? Only needed if somebody spots it."}]}]},
]

CARD = """<div class="card" data-id="{cid}" data-shot="{shot}"
 data-abs="{abs}"
 data-seq="{seq}"
 data-text="{esc}">
<div><p class="txt">{txt}</p>
<div class="meta"><span class="seq{seqkind}">{seqlabel}</span><span class="count{over}">{n}/280</span>
<button class="act copy" type="button">Copy</button>
<label class="tick"><input type="checkbox"> posted</label></div>{note}</div>
{side}</div>"""

SIDE = """<div class="side"><img src="{shot}" alt="" loading="lazy"><div class="fname">{shot}</div><button class="act copypath" type="button">Copy path</button></div>"""

def build():
    out = []
    for camp in CAMPAIGNS:
        groups = []
        for gi, group in enumerate(camp["groups"]):
            cards = []
            for pi, post in enumerate(group["posts"]):
                text = post["text"]
                shot = post.get("shot", "")
                n = len(text)
                note = ('<p class="note%s">%s</p>' % (
                    "" if (post.get("note","").startswith(("UNVERIFIED","THE POST","Do not","Say it")) ) else " plain",
                    html.escape(post["note"]))) if post.get("note") else ""
                side = SIDE.format(shot=shot) if shot else '<div class="side"></div>'
                total = len(group["posts"])
                is_thread = group["kind"] == "thread"
                # THE EMOJI IS ON THE BOARD, NOT IN THE POST. The voice rules
                # ban emoji and the linter enforces it, so a thread marker in
                # the text would fail its own check. Here it is a label telling
                # you where you are in a sequence, which is what it is for.
                seq_label = ("\U0001FAA1 %d/%d" % (pi + 1, total)) if is_thread else ("%d/%d" % (pi + 1, total))
                # The COPIED text carries the number and never the emoji, so a
                # thread posts as 1/7 the way threads normally read.
                copy_text = ("%d/%d\n\n%s" % (pi + 1, total, text)) if is_thread else text
                cards.append(CARD.format(
                    cid=f'{camp["id"]}-{gi}-{pi}', shot=shot,
                    abs=f"{SHOTS_ABS}/{shot}" if shot else "",
                    esc=html.escape(copy_text, quote=True),
                    txt=html.escape(text), n=n,
                    over=" over" if n > 280 else "",
                    seq=f"{pi+1}/{total}",
                    seqkind=" thread" if is_thread else "",
                    seqlabel=seq_label,
                    note=note, side=side))
            label = ('<div class="group-head"><span class="group-label">%s</span>%s</div>' % (
                html.escape(group.get("label","")),
                '<button class="act copy-thread" type="button">Copy whole thread</button>' if group["kind"]=="thread" else "")
            ) if group.get("label") or group["kind"]=="thread" else ""
            groups.append('<div class="group %s">%s%s</div>' % (group["kind"], label, "\n".join(cards)))
        out.append('<section id="%s"><div class="sec-head"><h2>%s</h2><span class="blurb">%s</span></div>%s</section>'
                   % (camp["id"], html.escape(camp["title"]), html.escape(camp["blurb"]), "\n".join(groups)))
    return "\n".join(out)

TEMPLATE = pathlib.Path(__file__).with_name("_shell.html").read_text(encoding="utf-8")
pathlib.Path(__file__).with_name("index.html").write_text(
    TEMPLATE.replace("<!--BODY-->", build()), encoding="utf-8")
print("wrote index.html")
