;; Browser house v2: authenticated attempts, NOT contract-verified chess.
;; Immutable, no administrator, no external core dependency. Amounts microSTX.
(define-constant SELF (unwrap-panic (as-contract? () tx-sender)))
(define-constant AUTH (err u300))
(define-constant MISSING (err u301))
(define-constant TERMS (err u302))
(define-constant STATE (err u303))
(define-constant DEADLINE (err u304))
(define-constant BUDGET (err u305))
(define-constant STALE (err u306))
(define-data-var next-game uint u1)
(define-data-var reserved uint u0)
(define-map Heads uint (buff 32))
(define-constant EMPTY-HEAD 0x0000000000000000000000000000000000000000000000000000000000000000)
(define-map Games uint {mode:uint, creator: principal, policy: (string-ascii 4096), accept-by: uint, expires-at: uint, lease: uint, status: uint, next-seq: uint})
(define-map Seats {game: uint, white: bool} {funder: principal, executor: principal, backup: principal, house: bool, profile: (buff 32), allowance: uint, cap: uint, epoch:uint, until:uint, consent:bool, released:bool, deposited:uint, reserved:uint, paid:uint, refunded:uint, attempts:uint})
(define-map Entries {game: uint, seq: uint} {white: bool, executor: principal, epoch: uint, move: (string-ascii 5), height: uint})
(define-map Hints {game: uint, publisher: principal} {id: uint, hash: (buff 32)})
(define-private (min (a uint) (b uint)) (if (< a b) a b))
(define-private (direct) (is-eq tx-sender contract-caller))
(define-private (wallet (who principal)) (match (principal-destruct? who) p (is-none (get name p)) e false))
(define-private (valid (s {funder: principal, executor: principal, backup: principal, house: bool, profile: (buff 32), allowance: uint, cap: uint}) (mode uint))
 (and (wallet (get funder s)) (wallet (get executor s)) (wallet (get backup s)) (is-eq (len (get profile s)) u32)
 (if (get house s) (if (is-eq mode u1) (and (is-eq (get allowance s) u0) (is-eq (get cap s) u0)) (and (> (get allowance s) u0) (<= (get allowance s) u1000000) (>= (get cap s) (get allowance s)) (<= (get cap s) u100000000)))
 (and (is-eq (get allowance s) u0) (is-eq (get cap s) u0) (is-eq (get funder s) (get executor s))))))
(define-private (save-seat (g uint) (w bool) (s {funder: principal, executor: principal, backup: principal, house: bool, profile: (buff 32), allowance: uint, cap: uint}))
 (map-set Seats {game:g, white:w} (merge s {epoch:u0, until:u0, consent:false, released:false, deposited:u0, reserved:u0, paid:u0, refunded:u0, attempts:u0})))
(define-private (pay (amount uint) (to principal))
 (if (is-eq amount u0) (ok true) (match (as-contract? ((with-stx amount)) (try! (stx-transfer? amount tx-sender to))) value (ok value) violation (err u307))))
(define-public (create-match (white {funder: principal, executor: principal, backup: principal, house: bool, profile: (buff 32), allowance: uint, cap: uint}) (black {funder: principal, executor: principal, backup: principal, house: bool, profile: (buff 32), allowance: uint, cap: uint}) (policy (string-ascii 4096)) (accept-by uint) (expires-at uint) (lease uint) (mode uint))
 (let ((g (var-get next-game)))
 (asserts! (direct) AUTH)
 (asserts! (and (valid white mode) (valid black mode) (or (and (is-eq mode u1) (not (is-eq (get house white) (get house black)))) (and (is-eq mode u2) (get house white) (get house black))) (is-eq (get executor white) (get executor black)) (> (len policy) u0)) TERMS)
 (asserts! (and (> accept-by stacks-block-height) (> expires-at accept-by) (<= expires-at (+ stacks-block-height u43200)) (>= lease u10) (<= lease u1440)) DEADLINE)
 (save-seat g true white) (save-seat g false black)
 (map-set Games g {mode:mode,creator:tx-sender, policy:policy, accept-by:accept-by, expires-at:expires-at, lease:lease, status:u0, next-seq:u0})
 (var-set next-game (+ g u1)) (ok g)))
(define-public (fund-seat (game uint) (white bool) (amount uint))
 (let ((m (unwrap! (map-get? Games game) MISSING)) (k {game:game,white:white}) (s (unwrap! (map-get? Seats k) MISSING)))
 (asserts! (and (direct) (is-eq tx-sender (get funder s))) AUTH)
 (asserts! (and (< (get status m) u2) (not (get released s))) STATE)
 (asserts! (< stacks-block-height (if (is-eq (get status m) u0) (get accept-by m) (get expires-at m))) DEADLINE)
 (asserts! (and (<= (+ (get deposited s) amount) (get cap s)) (or (> amount u0) (is-eq (get allowance s) u0))) BUDGET)
 (if (> amount u0) (try! (stx-transfer? amount tx-sender SELF)) true)
 (map-set Seats k (merge s {consent:true, deposited:(+ (get deposited s) amount),reserved:(+ (get reserved s) amount)}))
 (var-set reserved (+ (var-get reserved) amount)) (ok true)))
(define-private (start-seat (game uint) (white bool) (until uint))
 (let ((k {game:game,white:white}) (s (unwrap-panic (map-get? Seats k)))) (map-set Seats k (merge s {until:until}))))
(define-public (activate (game uint))
 (let ((m (unwrap! (map-get? Games game) MISSING)) (w (unwrap! (map-get? Seats {game:game,white:true}) MISSING)) (b (unwrap! (map-get? Seats {game:game,white:false}) MISSING)))
 (asserts! (is-eq (get status m) u0) STATE) (asserts! (< stacks-block-height (get accept-by m)) DEADLINE)
 (asserts! (and (get consent w) (get consent b) (>= (get reserved w) (get allowance w)) (>= (get reserved b) (get allowance b))) BUDGET)
 (start-seat game true (+ stacks-block-height (get lease m))) (start-seat game false (+ stacks-block-height (get lease m)))
 (map-set Games game (merge m {status:u1})) (ok true)))
(define-private (append-attempt (game uint) (white bool) (epoch uint) (move (string-ascii 5)))
 (let ((m (unwrap! (map-get? Games game) MISSING)) (k {game:game,white:white}) (s (unwrap! (map-get? Seats k) MISSING)) (seq (get next-seq m))
       (entry {white:white,executor:tx-sender,epoch:epoch,move:move,height:stacks-block-height}))
 (asserts! (and (< seq u4096) (< (get attempts s) u2048) (or (is-eq (len move) u4) (is-eq (len move) u5))) STALE)
 (map-set Entries {game:game,seq:seq} entry)
 (map-set Heads game (sha256 (concat (default-to EMPTY-HEAD (map-get? Heads game)) (sha256 (unwrap-panic (to-consensus-buff? entry))))))
 (map-set Games game (merge m {next-seq:(+ seq u1)}))
 (map-set Seats k (merge s {attempts:(+ (get attempts s) u1)})) (ok true)))
(define-private (append-batch (move {white:bool,move:(string-ascii 5)}) (state (response {game:uint,we:uint,be:uint,used-white:bool,used-black:bool} uint)))
 (let ((s (try! state))) (try! (append-attempt (get game s) (get white move) (if (get white move) (get we s) (get be s)) (get move move))) (ok (merge s {used-white:(or (get used-white s) (get white move)),used-black:(or (get used-black s) (not (get white move)))}))))
(define-private (charge-batch-seat (game uint) (white bool))
 (let ((k {game:game,white:white}) (s (unwrap! (map-get? Seats k) MISSING)) (amount (get allowance s)))
 (asserts! (>= (get reserved s) amount) BUDGET)
 (map-set Seats k (merge s {reserved:(- (get reserved s) amount),paid:(+ (get paid s) amount)}))
 (var-set reserved (- (var-get reserved) amount)) (try! (pay amount tx-sender)) (ok true)))
(define-public (submit-batch (game uint) (white-epoch uint) (black-epoch uint) (seq uint) (head (buff 32)) (moves (list 8 {white:bool,move:(string-ascii 5)})))
 (let ((m (unwrap! (map-get? Games game) MISSING)) (w (unwrap! (map-get? Seats {game:game,white:true}) MISSING)) (b (unwrap! (map-get? Seats {game:game,white:false}) MISSING)))
 (asserts! (and (direct) (is-eq tx-sender (get executor w)) (is-eq tx-sender (get executor b)) (is-eq white-epoch (get epoch w)) (is-eq black-epoch (get epoch b))) AUTH)
 (asserts! (and (is-eq (get status m) u1) (not (get released w)) (not (get released b))) STATE)
 (asserts! (and (< stacks-block-height (get expires-at m)) (or (is-eq (get mode m) u1) (and (< stacks-block-height (get until w)) (< stacks-block-height (get until b))))) DEADLINE)
 (asserts! (and (<= (len moves) (if (is-eq (get mode m) u1) u3 u8)) (> (len moves) u0) (is-eq seq (get next-seq m)) (is-eq head (default-to EMPTY-HEAD (map-get? Heads game)))) STALE)
 (let ((used (try! (fold append-batch moves (ok {game:game,we:white-epoch,be:black-epoch,used-white:false,used-black:false})))))
 (if (get used-white used) (try! (charge-batch-seat game true)) true)
 (if (get used-black used) (try! (charge-batch-seat game false)) true))
 (ok (get next-seq (unwrap-panic (map-get? Games game))))))
(define-read-only (get-head (game uint)) (default-to EMPTY-HEAD (map-get? Heads game)))
(define-public (renew-lease (game uint) (white bool) (epoch uint))
 (let ((m (unwrap! (map-get? Games game) MISSING)) (k {game:game,white:white}) (s (unwrap! (map-get? Seats k) MISSING)))
 (asserts! (and (direct) (is-eq (get mode m) u2) (get house s) (is-eq tx-sender (get executor s)) (is-eq epoch (get epoch s))) AUTH)
 (asserts! (and (is-eq (get status m) u1) (not (get released s))) STATE)
 (asserts! (and (< stacks-block-height (get until s)) (< stacks-block-height (get expires-at m))) DEADLINE)
 (map-set Seats k (merge s {until:(min (+ stacks-block-height (get lease m)) (get expires-at m))})) (ok true)))
(define-public (rotate-executor (game uint) (white bool) (executor principal))
 (let ((m (unwrap! (map-get? Games game) MISSING)) (k {game:game,white:white}) (s (unwrap! (map-get? Seats k) MISSING)))
 (asserts! (and (direct) (is-eq (get mode m) u2) (get house s) (is-eq tx-sender (get funder s)) (wallet executor)) AUTH)
 (asserts! (and (is-eq (get status m) u1) (not (get released s))) STATE) (asserts! (< stacks-block-height (get expires-at m)) DEADLINE)
 (map-set Seats k (merge s {executor:executor,epoch:(+ (get epoch s) u1),until:(min (+ stacks-block-height (get lease m)) (get expires-at m))})) (ok true)))
(define-public (activate-backup (game uint) (white bool) (epoch uint))
 (let ((m (unwrap! (map-get? Games game) MISSING)) (k {game:game,white:white}) (s (unwrap! (map-get? Seats k) MISSING)))
 (asserts! (and (direct) (is-eq (get mode m) u2) (get house s) (is-eq tx-sender (get backup s)) (is-eq epoch (get epoch s))) AUTH)
 (asserts! (and (is-eq (get status m) u1) (not (get released s))) STATE)
 (asserts! (and (>= stacks-block-height (get until s)) (< stacks-block-height (get expires-at m))) DEADLINE)
 (map-set Seats k (merge s {executor:tx-sender,epoch:(+ epoch u1),until:(min (+ stacks-block-height (get lease m)) (get expires-at m))})) (ok true)))
(define-public (release-seat (game uint) (white bool) (epoch uint))
 (let ((m (unwrap! (map-get? Games game) MISSING)) (k {game:game,white:white}) (s (unwrap! (map-get? Seats k) MISSING)))
 (asserts! (and (direct) (is-eq tx-sender (get executor s)) (is-eq epoch (get epoch s))) AUTH)
 (asserts! (is-eq (get status m) u1) STATE)
 (map-set Seats k (merge s {released:true,epoch:(+ (get epoch s) u1)})) (ok true)))
(define-public (cancel-pending (game uint))
 (let ((m (unwrap! (map-get? Games game) MISSING)) (w (unwrap! (map-get? Seats {game:game,white:true}) MISSING)) (b (unwrap! (map-get? Seats {game:game,white:false}) MISSING)))
 (asserts! (and (direct) (or (is-eq tx-sender (get creator m)) (and (get consent w) (is-eq tx-sender (get funder w))) (and (get consent b) (is-eq tx-sender (get funder b))))) AUTH)
 (asserts! (is-eq (get status m) u0) STATE) (map-set Games game (merge m {status:u2})) (ok true)))
(define-public (expire-match (game uint))
 (let ((m (unwrap! (map-get? Games game) MISSING)))
 (asserts! (>= stacks-block-height (if (is-eq (get status m) u0) (get accept-by m) (get expires-at m))) DEADLINE)
 (map-set Games game (merge m {status:u2})) (ok true)))
(define-public (refund-seat (game uint) (white bool))
 (let ((m (unwrap! (map-get? Games game) MISSING)) (k {game:game,white:white}) (s (unwrap! (map-get? Seats k) MISSING)) (amount (get reserved s)))
 (asserts! (or (is-eq (get status m) u2) (get released s)) STATE) (asserts! (> amount u0) BUDGET)
 (map-set Seats k (merge s {reserved:u0,refunded:(+ (get refunded s) amount)})) (var-set reserved (- (var-get reserved) amount))
 (try! (pay amount (get funder s))) (ok amount)))
(define-public (publish-archive (game uint) (id uint) (hash (buff 32)))
 (begin (asserts! (is-some (map-get? Games game)) MISSING) (asserts! (and (> id u0) (is-eq (len hash) u32)) TERMS)
 (map-set Hints {game:game,publisher:tx-sender} {id:id,hash:hash}) (ok true)))
(define-read-only (get-game (game uint)) (map-get? Games game))
(define-read-only (get-seat (game uint) (white bool)) (map-get? Seats {game:game,white:white}))
(define-read-only (get-entry (game uint) (seq uint)) (map-get? Entries {game:game,seq:seq}))
(define-read-only (get-hint (game uint) (publisher principal)) (map-get? Hints {game:game,publisher:publisher}))
(define-read-only (get-total-reserved) (var-get reserved))
(define-read-only (is-solvent) (>= (stx-get-balance SELF) (var-get reserved)))

;; Bounded pagination avoids a network round trip per historical attempt.
(define-private (page-entry (offset uint) (state {game:uint, start:uint, rows:(list 50 (optional {white: bool, executor: principal, epoch: uint, move: (string-ascii 5), height: uint}))}))
 (merge state {rows:(unwrap-panic (as-max-len? (append (get rows state) (map-get? Entries {game:(get game state),seq:(+ (get start state) offset)})) u50))}))
(define-read-only (get-entries (game uint) (start uint))
 (get rows (fold page-entry (list u0 u1 u2 u3 u4 u5 u6 u7 u8 u9 u10 u11 u12 u13 u14 u15 u16 u17 u18 u19 u20 u21 u22 u23 u24 u25 u26 u27 u28 u29 u30 u31 u32 u33 u34 u35 u36 u37 u38 u39 u40 u41 u42 u43 u44 u45 u46 u47 u48 u49) {game:game,start:start,rows:(list)})))

;; One shared executor can release both seats; this makes no chess-result claim.
(define-public (release-batch (game uint) (white-epoch uint) (black-epoch uint))
 (let ((m (unwrap! (map-get? Games game) MISSING)) (w (unwrap! (map-get? Seats {game:game,white:true}) MISSING)) (b (unwrap! (map-get? Seats {game:game,white:false}) MISSING)))
 (asserts! (and (direct) (is-eq (get mode m) u2) (is-eq tx-sender (get executor w)) (is-eq tx-sender (get executor b)) (is-eq white-epoch (get epoch w)) (is-eq black-epoch (get epoch b))) AUTH)
 (asserts! (is-eq (get status m) u1) STATE)
 (map-set Seats {game:game,white:true} (merge w {released:true,epoch:(+ white-epoch u1)}))
 (map-set Seats {game:game,white:false} (merge b {released:true,epoch:(+ black-epoch u1)})) (ok true)))

;; Consent is always the funder's own transaction. Activate only when both are ready.
(define-private (activate-ready (game uint))
 (let ((m (unwrap! (map-get? Games game) MISSING)) (w (unwrap! (map-get? Seats {game:game,white:true}) MISSING)) (b (unwrap! (map-get? Seats {game:game,white:false}) MISSING)))
 (if (and (is-eq (get status m) u0) (get consent w) (get consent b) (>= (get reserved w) (get allowance w)) (>= (get reserved b) (get allowance b))) (activate game) (ok true))))
(define-public (accept-and-fund (game uint) (white bool) (amount uint))
 (begin (try! (fund-seat game white amount)) (activate-ready game)))
;; Bootstrap is an explicit sender transfer, only in creation; never an escrow grant.
(define-public (create-and-fund (white {funder:principal,executor:principal,backup:principal,house:bool,profile:(buff 32),allowance:uint,cap:uint}) (black {funder:principal,executor:principal,backup:principal,house:bool,profile:(buff 32),allowance:uint,cap:uint}) (policy (string-ascii 4096)) (accept-by uint) (expires-at uint) (lease uint) (mode uint) (white-amount uint) (black-amount uint) (bootstrap uint))
 (let ((own-white (is-eq tx-sender (get funder white))) (own-black (is-eq tx-sender (get funder black))))
 (asserts! (and (direct) (or own-white own-black) (or own-white (is-eq white-amount u0)) (or own-black (is-eq black-amount u0))) AUTH)
 (asserts! (and (<= bootstrap u1000000) (or (is-eq mode u2) (is-eq bootstrap u0))) BUDGET)
 (let ((game (try! (create-match white black policy accept-by expires-at lease mode))))
 (if (and own-white (or (> white-amount u0) (is-eq (get allowance white) u0))) (try! (fund-seat game true white-amount)) true)
 (if (and own-black (or (> black-amount u0) (is-eq (get allowance black) u0))) (try! (fund-seat game false black-amount)) true)
 (if (> bootstrap u0) (try! (stx-transfer? bootstrap tx-sender (get executor white))) true)
 (try! (activate-ready game)) (ok game))))
