;; Wallet-paid endorsements; no transfers, platform fees or administrative controls.
;; Canonical IDs include legacy inscriptions. The app separately verifies song content.
(define-map likes {id: uint, listener: principal} bool)
(define-map totals uint uint)
(define-read-only (get-config)
 (ok {version: u1, core: 'SP3JNSEXAZP4BDSHV0DN3M8R3P0MY0EEBQQZX743X.xtrata-v3-2-3, batch-limit: u25, platform-fee: u0}))
(define-read-only (get-liked (id uint) (listener principal)) (default-to false (map-get? likes {id: id, listener: listener})))
(define-read-only (get-total (id uint)) (default-to u0 (map-get? totals id)))
(define-private (minted (id uint))
 (or
  (is-some (unwrap-panic (contract-call? 'SP3JNSEXAZP4BDSHV0DN3M8R3P0MY0EEBQQZX743X.xtrata-v3-2-3 get-owner id)))
  (is-some (unwrap-panic (contract-call? 'SP3JNSEXAZP4BDSHV0DN3M8R3P0MY0EEBQQZX743X.xtrata-v2-1-0 get-owner id)))
  (is-some (unwrap-panic (contract-call? 'SP3JNSEXAZP4BDSHV0DN3M8R3P0MY0EEBQQZX743X.xtrata-v1-1-1 get-owner id)))))
(define-private (apply-like (id uint) (liked bool))
 (let ((old (get-liked id tx-sender)) (total (get-total id)))
  (asserts! (or (not liked) (minted id)) (err u101))
  (if (is-eq old liked) (ok false)
   (begin
    (if liked (map-set likes {id: id, listener: tx-sender} true) (map-delete likes {id: id, listener: tx-sender}))
    (map-set totals id (if liked (+ total u1) (- total u1)))
    (print {event: "radio-like", version: u1, id: id, listener: tx-sender, liked: liked, total: (get-total id)})
    (ok true)))))
(define-public (set-liked (id uint) (liked bool))
 (begin (asserts! (is-eq tx-sender contract-caller) (err u100)) (apply-like id liked)))
(define-private (batch-step (item {id: uint, liked: bool}) (result (response uint uint)))
 (let ((changed (try! result)) (did-change (try! (apply-like (get id item) (get liked item)))))
  (ok (+ changed (if did-change u1 u0)))))
(define-public (set-likes (items (list 25 {id: uint, liked: bool})))
 (begin (asserts! (is-eq tx-sender contract-caller) (err u100))
  (asserts! (> (len items) u0) (err u102)) (fold batch-step items (ok u0))))
(define-private (read-step (id uint) (state {listener: principal, rows: (list 25 {id: uint, liked: bool, total: uint})}))
 {listener: (get listener state), rows: (unwrap-panic (as-max-len?
  (append (get rows state) {id: id, liked: (get-liked id (get listener state)), total: (get-total id)}) u25))})
(define-read-only (get-state (ids (list 25 uint)) (listener principal))
 (ok (get rows (fold read-step ids {listener: listener, rows: (list)}))))
